package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for addcavity kernel
var addcavity_code cu.Function

// Stores the arguments for addcavity kernel invocation
type addcavity_args_t struct{
	 arg_tx unsafe.Pointer
	 arg_ty unsafe.Pointer
	 arg_tz unsafe.Pointer
	 arg_wc unsafe.Pointer
	 arg_wc_mul float32
	 arg_kappa unsafe.Pointer
	 arg_kappa_mul float32
	 arg_brms_x unsafe.Pointer
	 arg_brms_y unsafe.Pointer
	 arg_brms_z unsafe.Pointer
	 arg_x0 float32
	 arg_p0 float32
	 arg_msat_cell float32
	 arg_ctime float32
	 arg_sn float32
	 arg_cn float32
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 arg_PBC byte
	 argptr [20]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for addcavity kernel invocation
var addcavity_args addcavity_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 addcavity_args.argptr[0] = unsafe.Pointer(&addcavity_args.arg_tx)
	 addcavity_args.argptr[1] = unsafe.Pointer(&addcavity_args.arg_ty)
	 addcavity_args.argptr[2] = unsafe.Pointer(&addcavity_args.arg_tz)
	 addcavity_args.argptr[3] = unsafe.Pointer(&addcavity_args.arg_wc)
	 addcavity_args.argptr[4] = unsafe.Pointer(&addcavity_args.arg_wc_mul)
	 addcavity_args.argptr[5] = unsafe.Pointer(&addcavity_args.arg_kappa)
	 addcavity_args.argptr[6] = unsafe.Pointer(&addcavity_args.arg_kappa_mul)
	 addcavity_args.argptr[7] = unsafe.Pointer(&addcavity_args.arg_brms_x)
	 addcavity_args.argptr[8] = unsafe.Pointer(&addcavity_args.arg_brms_y)
	 addcavity_args.argptr[9] = unsafe.Pointer(&addcavity_args.arg_brms_z)
	 addcavity_args.argptr[10] = unsafe.Pointer(&addcavity_args.arg_x0)
	 addcavity_args.argptr[11] = unsafe.Pointer(&addcavity_args.arg_p0)
	 addcavity_args.argptr[12] = unsafe.Pointer(&addcavity_args.arg_msat_cell)
	 addcavity_args.argptr[13] = unsafe.Pointer(&addcavity_args.arg_ctime)
	 addcavity_args.argptr[14] = unsafe.Pointer(&addcavity_args.arg_sn)
	 addcavity_args.argptr[15] = unsafe.Pointer(&addcavity_args.arg_cn)
	 addcavity_args.argptr[16] = unsafe.Pointer(&addcavity_args.arg_Nx)
	 addcavity_args.argptr[17] = unsafe.Pointer(&addcavity_args.arg_Ny)
	 addcavity_args.argptr[18] = unsafe.Pointer(&addcavity_args.arg_Nz)
	 addcavity_args.argptr[19] = unsafe.Pointer(&addcavity_args.arg_PBC)
	 }

// Wrapper for addcavity CUDA kernel, asynchronous.
func k_addcavity_async ( tx unsafe.Pointer, ty unsafe.Pointer, tz unsafe.Pointer, wc unsafe.Pointer, wc_mul float32, kappa unsafe.Pointer, kappa_mul float32, brms_x unsafe.Pointer, brms_y unsafe.Pointer, brms_z unsafe.Pointer, x0 float32, p0 float32, msat_cell float32, ctime float32, sn float32, cn float32, Nx int, Ny int, Nz int, PBC byte,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("addcavity")
	}

	addcavity_args.Lock()
	defer addcavity_args.Unlock()

	if addcavity_code == 0{
		addcavity_code = fatbinLoad(addcavity_map, "addcavity")
	}

	 addcavity_args.arg_tx = tx
	 addcavity_args.arg_ty = ty
	 addcavity_args.arg_tz = tz
	 addcavity_args.arg_wc = wc
	 addcavity_args.arg_wc_mul = wc_mul
	 addcavity_args.arg_kappa = kappa
	 addcavity_args.arg_kappa_mul = kappa_mul
	 addcavity_args.arg_brms_x = brms_x
	 addcavity_args.arg_brms_y = brms_y
	 addcavity_args.arg_brms_z = brms_z
	 addcavity_args.arg_x0 = x0
	 addcavity_args.arg_p0 = p0
	 addcavity_args.arg_msat_cell = msat_cell
	 addcavity_args.arg_ctime = ctime
	 addcavity_args.arg_sn = sn
	 addcavity_args.arg_cn = cn
	 addcavity_args.arg_Nx = Nx
	 addcavity_args.arg_Ny = Ny
	 addcavity_args.arg_Nz = Nz
	 addcavity_args.arg_PBC = PBC
	

	args := addcavity_args.argptr[:]
	cu.LaunchKernel(addcavity_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("addcavity")
	}
}

// maps compute capability on PTX code for addcavity kernel.
var addcavity_map = map[int]string{ 0: "" ,
50: addcavity_ptx_50 ,
52: addcavity_ptx_52 ,
53: addcavity_ptx_53 ,
60: addcavity_ptx_60 ,
61: addcavity_ptx_61 ,
70: addcavity_ptx_70 ,
75: addcavity_ptx_75  }

// addcavity PTX code for various compute capabilities.
const(
  addcavity_ptx_50 = `
.version 6.4
.target sm_50
.address_size 64

	// .globl	addcavity
.const .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry addcavity(
	.param .u64 addcavity_param_0,
	.param .u64 addcavity_param_1,
	.param .u64 addcavity_param_2,
	.param .u64 addcavity_param_3,
	.param .f32 addcavity_param_4,
	.param .u64 addcavity_param_5,
	.param .f32 addcavity_param_6,
	.param .u64 addcavity_param_7,
	.param .u64 addcavity_param_8,
	.param .u64 addcavity_param_9,
	.param .f32 addcavity_param_10,
	.param .f32 addcavity_param_11,
	.param .f32 addcavity_param_12,
	.param .f32 addcavity_param_13,
	.param .f32 addcavity_param_14,
	.param .f32 addcavity_param_15,
	.param .u32 addcavity_param_16,
	.param .u32 addcavity_param_17,
	.param .u32 addcavity_param_18,
	.param .u8 addcavity_param_19
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<36>;
	.reg .f32 	%f<143>;
	.reg .b32 	%r<201>;
	.reg .b64 	%rd<49>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd13, [addcavity_param_0];
	ld.param.u64 	%rd14, [addcavity_param_1];
	ld.param.u64 	%rd15, [addcavity_param_2];
	ld.param.u64 	%rd16, [addcavity_param_3];
	ld.param.f32 	%f129, [addcavity_param_4];
	ld.param.u64 	%rd17, [addcavity_param_5];
	ld.param.f32 	%f130, [addcavity_param_6];
	ld.param.u64 	%rd18, [addcavity_param_7];
	ld.param.u64 	%rd19, [addcavity_param_8];
	ld.param.u64 	%rd20, [addcavity_param_9];
	ld.param.f32 	%f47, [addcavity_param_10];
	ld.param.f32 	%f48, [addcavity_param_11];
	ld.param.f32 	%f49, [addcavity_param_12];
	ld.param.f32 	%f50, [addcavity_param_13];
	ld.param.f32 	%f51, [addcavity_param_14];
	ld.param.f32 	%f52, [addcavity_param_15];
	ld.param.u32 	%r76, [addcavity_param_16];
	ld.param.u32 	%r77, [addcavity_param_17];
	ld.param.u32 	%r78, [addcavity_param_18];
	mov.u32 	%r79, %ntid.x;
	mov.u32 	%r80, %ctaid.x;
	mov.u32 	%r81, %tid.x;
	mad.lo.s32 	%r1, %r79, %r80, %r81;
	mov.u32 	%r82, %ntid.y;
	mov.u32 	%r83, %ctaid.y;
	mov.u32 	%r84, %tid.y;
	mad.lo.s32 	%r2, %r82, %r83, %r84;
	mov.u32 	%r85, %ntid.z;
	mov.u32 	%r86, %ctaid.z;
	mov.u32 	%r87, %tid.z;
	mad.lo.s32 	%r3, %r85, %r86, %r87;
	setp.ge.s32	%p1, %r2, %r77;
	setp.ge.s32	%p2, %r1, %r76;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r78;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_52;

	mad.lo.s32 	%r88, %r3, %r77, %r2;
	mad.lo.s32 	%r4, %r88, %r76, %r1;
	setp.eq.s64	%p6, %rd16, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd21, %rd16;
	mul.wide.s32 	%rd22, %r4, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.nc.f32 	%f53, [%rd23];
	mul.f32 	%f129, %f53, %f129;

BB0_3:
	setp.eq.s64	%p7, %rd17, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd24, %rd17;
	mul.wide.s32 	%rd25, %r4, 4;
	add.s64 	%rd26, %rd24, %rd25;
	ld.global.nc.f32 	%f54, [%rd26];
	mul.f32 	%f130, %f54, %f130;

BB0_5:
	mul.f32 	%f5, %f130, %f50;
	neg.f32 	%f55, %f5;
	mul.f32 	%f56, %f5, 0fBFB8AA3B;
	cvt.rzi.f32.f32	%f57, %f56;
	mov.f32 	%f58, 0fBF317200;
	fma.rn.f32 	%f59, %f57, %f58, %f55;
	mov.f32 	%f60, 0fB5BFBE8E;
	fma.rn.f32 	%f61, %f57, %f60, %f59;
	mul.f32 	%f62, %f61, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f6, %f62;
	add.f32 	%f63, %f57, 0f00000000;
	ex2.approx.f32 	%f7, %f63;
	add.u64 	%rd1, %SPL, 0;
	mul.f32 	%f137, %f129, %f50;
	abs.f32 	%f9, %f137;
	setp.neu.f32	%p8, %f9, 0f7F800000;
	mov.f32 	%f131, %f137;
	@%p8 bra 	BB0_7;

	mov.f32 	%f64, 0f00000000;
	mul.rn.f32 	%f131, %f137, %f64;

BB0_7:
	mul.f32 	%f65, %f131, 0f3F22F983;
	cvt.rni.s32.f32	%r190, %f65;
	cvt.rn.f32.s32	%f66, %r190;
	neg.f32 	%f67, %f66;
	mov.f32 	%f68, 0f3FC90FDA;
	fma.rn.f32 	%f69, %f67, %f68, %f131;
	mov.f32 	%f70, 0f33A22168;
	fma.rn.f32 	%f71, %f67, %f70, %f69;
	mov.f32 	%f72, 0f27C234C5;
	fma.rn.f32 	%f132, %f67, %f72, %f71;
	abs.f32 	%f73, %f131;
	add.s64 	%rd2, %rd1, 24;
	setp.lt.f32	%p9, %f5, 0fC2D20000;
	setp.gt.f32	%p10, %f5, 0f42D20000;
	mul.f32 	%f74, %f6, %f7;
	selp.f32	%f75, 0f00000000, %f74, %p10;
	selp.f32	%f13, 0f7F800000, %f75, %p9;
	setp.leu.f32	%p11, %f73, 0f47CE4780;
	@%p11 bra 	BB0_18;

	mov.b32 	 %r6, %f131;
	shr.u32 	%r7, %r6, 23;
	shl.b32 	%r91, %r6, 8;
	or.b32  	%r8, %r91, -2147483648;
	mov.u32 	%r182, 0;
	mov.u64 	%rd45, __cudart_i2opi_f;
	mov.u32 	%r181, -6;
	mov.u64 	%rd46, %rd1;

BB0_9:
	.pragma "nounroll";
	ld.const.u32 	%r94, [%rd45];
	// inline asm
	{
	mad.lo.cc.u32   %r92, %r94, %r8, %r182;
	madc.hi.u32     %r182, %r94, %r8,  0;
	}
	// inline asm
	st.local.u32 	[%rd46], %r92;
	add.s64 	%rd46, %rd46, 4;
	add.s64 	%rd45, %rd45, 4;
	add.s32 	%r181, %r181, 1;
	setp.ne.s32	%p12, %r181, 0;
	@%p12 bra 	BB0_9;

	and.b32  	%r97, %r7, 255;
	add.s32 	%r98, %r97, -128;
	shr.u32 	%r99, %r98, 5;
	and.b32  	%r13, %r6, -2147483648;
	st.local.u32 	[%rd2], %r182;
	mov.u32 	%r100, 6;
	sub.s32 	%r101, %r100, %r99;
	mul.wide.s32 	%rd29, %r101, 4;
	add.s64 	%rd7, %rd1, %rd29;
	ld.local.u32 	%r183, [%rd7];
	ld.local.u32 	%r184, [%rd7+-4];
	and.b32  	%r16, %r7, 31;
	setp.eq.s32	%p13, %r16, 0;
	@%p13 bra 	BB0_12;

	mov.u32 	%r102, 32;
	sub.s32 	%r103, %r102, %r16;
	shr.u32 	%r104, %r184, %r103;
	shl.b32 	%r105, %r183, %r16;
	add.s32 	%r183, %r104, %r105;
	ld.local.u32 	%r106, [%rd7+-8];
	shr.u32 	%r107, %r106, %r103;
	shl.b32 	%r108, %r184, %r16;
	add.s32 	%r184, %r107, %r108;

BB0_12:
	shr.u32 	%r109, %r184, 30;
	shl.b32 	%r110, %r183, 2;
	add.s32 	%r185, %r109, %r110;
	shl.b32 	%r22, %r184, 2;
	shr.u32 	%r111, %r185, 31;
	shr.u32 	%r112, %r183, 30;
	add.s32 	%r23, %r111, %r112;
	setp.eq.s32	%p14, %r111, 0;
	@%p14 bra 	BB0_13;

	not.b32 	%r113, %r185;
	neg.s32 	%r187, %r22;
	setp.eq.s32	%p15, %r22, 0;
	selp.u32	%r114, 1, 0, %p15;
	add.s32 	%r185, %r114, %r113;
	xor.b32  	%r186, %r13, -2147483648;
	bra.uni 	BB0_15;

BB0_13:
	mov.u32 	%r186, %r13;
	mov.u32 	%r187, %r22;

BB0_15:
	clz.b32 	%r189, %r185;
	setp.eq.s32	%p16, %r189, 0;
	shl.b32 	%r115, %r185, %r189;
	mov.u32 	%r116, 32;
	sub.s32 	%r117, %r116, %r189;
	shr.u32 	%r118, %r187, %r117;
	add.s32 	%r119, %r118, %r115;
	selp.b32	%r31, %r185, %r119, %p16;
	mov.u32 	%r120, -921707870;
	mul.hi.u32 	%r188, %r31, %r120;
	setp.eq.s32	%p17, %r13, 0;
	neg.s32 	%r121, %r23;
	selp.b32	%r190, %r23, %r121, %p17;
	setp.lt.s32	%p18, %r188, 1;
	@%p18 bra 	BB0_17;

	mul.lo.s32 	%r122, %r31, -921707870;
	shr.u32 	%r123, %r122, 31;
	shl.b32 	%r124, %r188, 1;
	add.s32 	%r188, %r123, %r124;
	add.s32 	%r189, %r189, 1;

BB0_17:
	mov.u32 	%r125, 126;
	sub.s32 	%r126, %r125, %r189;
	shl.b32 	%r127, %r126, 23;
	add.s32 	%r128, %r188, 1;
	shr.u32 	%r129, %r128, 7;
	add.s32 	%r130, %r129, 1;
	shr.u32 	%r131, %r130, 1;
	add.s32 	%r132, %r131, %r127;
	or.b32  	%r133, %r132, %r186;
	mov.b32 	 %f132, %r133;

BB0_18:
	mul.rn.f32 	%f16, %f132, %f132;
	add.s32 	%r39, %r190, 1;
	and.b32  	%r40, %r39, 1;
	setp.eq.s32	%p19, %r40, 0;
	@%p19 bra 	BB0_20;

	mov.f32 	%f76, 0fBAB6061A;
	mov.f32 	%f77, 0f37CCF5CE;
	fma.rn.f32 	%f133, %f77, %f16, %f76;
	bra.uni 	BB0_21;

BB0_20:
	mov.f32 	%f78, 0f3C08839E;
	mov.f32 	%f79, 0fB94CA1F9;
	fma.rn.f32 	%f133, %f79, %f16, %f78;

BB0_21:
	@%p19 bra 	BB0_23;

	mov.f32 	%f80, 0f3D2AAAA5;
	fma.rn.f32 	%f81, %f133, %f16, %f80;
	mov.f32 	%f82, 0fBF000000;
	fma.rn.f32 	%f134, %f81, %f16, %f82;
	bra.uni 	BB0_24;

BB0_23:
	mov.f32 	%f83, 0fBE2AAAA3;
	fma.rn.f32 	%f84, %f133, %f16, %f83;
	mov.f32 	%f85, 0f00000000;
	fma.rn.f32 	%f134, %f84, %f16, %f85;

BB0_24:
	fma.rn.f32 	%f135, %f134, %f132, %f132;
	@%p19 bra 	BB0_26;

	mov.f32 	%f86, 0f3F800000;
	fma.rn.f32 	%f135, %f134, %f16, %f86;

BB0_26:
	and.b32  	%r134, %r39, 2;
	setp.eq.s32	%p22, %r134, 0;
	@%p22 bra 	BB0_28;

	mov.f32 	%f87, 0f00000000;
	mov.f32 	%f88, 0fBF800000;
	fma.rn.f32 	%f135, %f135, %f88, %f87;

BB0_28:
	@%p8 bra 	BB0_30;

	mov.f32 	%f89, 0f00000000;
	mul.rn.f32 	%f137, %f137, %f89;

BB0_30:
	mul.f32 	%f90, %f137, 0f3F22F983;
	cvt.rni.s32.f32	%r200, %f90;
	cvt.rn.f32.s32	%f91, %r200;
	neg.f32 	%f92, %f91;
	fma.rn.f32 	%f94, %f92, %f68, %f137;
	fma.rn.f32 	%f96, %f92, %f70, %f94;
	fma.rn.f32 	%f138, %f92, %f72, %f96;
	abs.f32 	%f98, %f137;
	setp.leu.f32	%p24, %f98, 0f47CE4780;
	@%p24 bra 	BB0_41;

	mov.b32 	 %r42, %f137;
	shr.u32 	%r43, %r42, 23;
	shl.b32 	%r137, %r42, 8;
	or.b32  	%r44, %r137, -2147483648;
	mov.u32 	%r192, 0;
	mov.u64 	%rd47, __cudart_i2opi_f;
	mov.u32 	%r191, -6;
	mov.u64 	%rd48, %rd1;

BB0_32:
	.pragma "nounroll";
	ld.const.u32 	%r140, [%rd47];
	// inline asm
	{
	mad.lo.cc.u32   %r138, %r140, %r44, %r192;
	madc.hi.u32     %r192, %r140, %r44,  0;
	}
	// inline asm
	st.local.u32 	[%rd48], %r138;
	add.s64 	%rd48, %rd48, 4;
	add.s64 	%rd47, %rd47, 4;
	add.s32 	%r191, %r191, 1;
	setp.ne.s32	%p25, %r191, 0;
	@%p25 bra 	BB0_32;

	and.b32  	%r143, %r43, 255;
	add.s32 	%r144, %r143, -128;
	shr.u32 	%r145, %r144, 5;
	and.b32  	%r49, %r42, -2147483648;
	st.local.u32 	[%rd2], %r192;
	mov.u32 	%r146, 6;
	sub.s32 	%r147, %r146, %r145;
	mul.wide.s32 	%rd31, %r147, 4;
	add.s64 	%rd12, %rd1, %rd31;
	ld.local.u32 	%r193, [%rd12];
	ld.local.u32 	%r194, [%rd12+-4];
	and.b32  	%r52, %r43, 31;
	setp.eq.s32	%p26, %r52, 0;
	@%p26 bra 	BB0_35;

	mov.u32 	%r148, 32;
	sub.s32 	%r149, %r148, %r52;
	shr.u32 	%r150, %r194, %r149;
	shl.b32 	%r151, %r193, %r52;
	add.s32 	%r193, %r150, %r151;
	ld.local.u32 	%r152, [%rd12+-8];
	shr.u32 	%r153, %r152, %r149;
	shl.b32 	%r154, %r194, %r52;
	add.s32 	%r194, %r153, %r154;

BB0_35:
	shr.u32 	%r155, %r194, 30;
	shl.b32 	%r156, %r193, 2;
	add.s32 	%r195, %r155, %r156;
	shl.b32 	%r58, %r194, 2;
	shr.u32 	%r157, %r195, 31;
	shr.u32 	%r158, %r193, 30;
	add.s32 	%r59, %r157, %r158;
	setp.eq.s32	%p27, %r157, 0;
	@%p27 bra 	BB0_36;

	not.b32 	%r159, %r195;
	neg.s32 	%r197, %r58;
	setp.eq.s32	%p28, %r58, 0;
	selp.u32	%r160, 1, 0, %p28;
	add.s32 	%r195, %r160, %r159;
	xor.b32  	%r196, %r49, -2147483648;
	bra.uni 	BB0_38;

BB0_36:
	mov.u32 	%r196, %r49;
	mov.u32 	%r197, %r58;

BB0_38:
	clz.b32 	%r199, %r195;
	setp.eq.s32	%p29, %r199, 0;
	shl.b32 	%r161, %r195, %r199;
	mov.u32 	%r162, 32;
	sub.s32 	%r163, %r162, %r199;
	shr.u32 	%r164, %r197, %r163;
	add.s32 	%r165, %r164, %r161;
	selp.b32	%r67, %r195, %r165, %p29;
	mov.u32 	%r166, -921707870;
	mul.hi.u32 	%r198, %r67, %r166;
	setp.eq.s32	%p30, %r49, 0;
	neg.s32 	%r167, %r59;
	selp.b32	%r200, %r59, %r167, %p30;
	setp.lt.s32	%p31, %r198, 1;
	@%p31 bra 	BB0_40;

	mul.lo.s32 	%r168, %r67, -921707870;
	shr.u32 	%r169, %r168, 31;
	shl.b32 	%r170, %r198, 1;
	add.s32 	%r198, %r169, %r170;
	add.s32 	%r199, %r199, 1;

BB0_40:
	mov.u32 	%r171, 126;
	sub.s32 	%r172, %r171, %r199;
	shl.b32 	%r173, %r172, 23;
	add.s32 	%r174, %r198, 1;
	shr.u32 	%r175, %r174, 7;
	add.s32 	%r176, %r175, 1;
	shr.u32 	%r177, %r176, 1;
	add.s32 	%r178, %r177, %r173;
	or.b32  	%r179, %r178, %r196;
	mov.b32 	 %f138, %r179;

BB0_41:
	mul.rn.f32 	%f33, %f138, %f138;
	and.b32  	%r75, %r200, 1;
	setp.eq.s32	%p32, %r75, 0;
	@%p32 bra 	BB0_43;

	mov.f32 	%f99, 0fBAB6061A;
	mov.f32 	%f100, 0f37CCF5CE;
	fma.rn.f32 	%f139, %f100, %f33, %f99;
	bra.uni 	BB0_44;

BB0_43:
	mov.f32 	%f101, 0f3C08839E;
	mov.f32 	%f102, 0fB94CA1F9;
	fma.rn.f32 	%f139, %f102, %f33, %f101;

BB0_44:
	@%p32 bra 	BB0_46;

	mov.f32 	%f103, 0f3D2AAAA5;
	fma.rn.f32 	%f104, %f139, %f33, %f103;
	mov.f32 	%f105, 0fBF000000;
	fma.rn.f32 	%f140, %f104, %f33, %f105;
	bra.uni 	BB0_47;

BB0_46:
	mov.f32 	%f106, 0fBE2AAAA3;
	fma.rn.f32 	%f107, %f139, %f33, %f106;
	mov.f32 	%f108, 0f00000000;
	fma.rn.f32 	%f140, %f107, %f33, %f108;

BB0_47:
	fma.rn.f32 	%f141, %f140, %f138, %f138;
	@%p32 bra 	BB0_49;

	mov.f32 	%f109, 0f3F800000;
	fma.rn.f32 	%f141, %f140, %f33, %f109;

BB0_49:
	and.b32  	%r180, %r200, 2;
	setp.eq.s32	%p35, %r180, 0;
	@%p35 bra 	BB0_51;

	mov.f32 	%f110, 0f00000000;
	mov.f32 	%f111, 0fBF800000;
	fma.rn.f32 	%f141, %f141, %f111, %f110;

BB0_51:
	cvta.to.global.u64 	%rd32, %rd15;
	cvta.to.global.u64 	%rd33, %rd14;
	cvta.to.global.u64 	%rd34, %rd13;
	cvta.to.global.u64 	%rd35, %rd20;
	cvta.to.global.u64 	%rd36, %rd19;
	cvta.to.global.u64 	%rd37, %rd18;
	mul.f32 	%f112, %f49, %f52;
	sub.f32 	%f113, %f48, %f112;
	mul.f32 	%f114, %f113, %f141;
	mul.f32 	%f115, %f49, %f51;
	sub.f32 	%f116, %f47, %f115;
	mul.f32 	%f117, %f116, %f135;
	sub.f32 	%f118, %f117, %f114;
	mul.f32 	%f119, %f13, %f118;
	mul.wide.s32 	%rd38, %r4, 4;
	add.s64 	%rd39, %rd37, %rd38;
	ld.global.nc.f32 	%f120, [%rd39];
	add.s64 	%rd40, %rd36, %rd38;
	ld.global.nc.f32 	%f121, [%rd40];
	add.s64 	%rd41, %rd35, %rd38;
	ld.global.nc.f32 	%f122, [%rd41];
	add.s64 	%rd42, %rd34, %rd38;
	ld.global.f32 	%f123, [%rd42];
	fma.rn.f32 	%f124, %f120, %f119, %f123;
	st.global.f32 	[%rd42], %f124;
	add.s64 	%rd43, %rd33, %rd38;
	ld.global.f32 	%f125, [%rd43];
	fma.rn.f32 	%f126, %f121, %f119, %f125;
	st.global.f32 	[%rd43], %f126;
	add.s64 	%rd44, %rd32, %rd38;
	ld.global.f32 	%f127, [%rd44];
	fma.rn.f32 	%f128, %f122, %f119, %f127;
	st.global.f32 	[%rd44], %f128;

BB0_52:
	ret;
}


`
   addcavity_ptx_52 = `
.version 6.4
.target sm_52
.address_size 64

	// .globl	addcavity
.const .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry addcavity(
	.param .u64 addcavity_param_0,
	.param .u64 addcavity_param_1,
	.param .u64 addcavity_param_2,
	.param .u64 addcavity_param_3,
	.param .f32 addcavity_param_4,
	.param .u64 addcavity_param_5,
	.param .f32 addcavity_param_6,
	.param .u64 addcavity_param_7,
	.param .u64 addcavity_param_8,
	.param .u64 addcavity_param_9,
	.param .f32 addcavity_param_10,
	.param .f32 addcavity_param_11,
	.param .f32 addcavity_param_12,
	.param .f32 addcavity_param_13,
	.param .f32 addcavity_param_14,
	.param .f32 addcavity_param_15,
	.param .u32 addcavity_param_16,
	.param .u32 addcavity_param_17,
	.param .u32 addcavity_param_18,
	.param .u8 addcavity_param_19
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<36>;
	.reg .f32 	%f<143>;
	.reg .b32 	%r<201>;
	.reg .b64 	%rd<49>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd13, [addcavity_param_0];
	ld.param.u64 	%rd14, [addcavity_param_1];
	ld.param.u64 	%rd15, [addcavity_param_2];
	ld.param.u64 	%rd16, [addcavity_param_3];
	ld.param.f32 	%f129, [addcavity_param_4];
	ld.param.u64 	%rd17, [addcavity_param_5];
	ld.param.f32 	%f130, [addcavity_param_6];
	ld.param.u64 	%rd18, [addcavity_param_7];
	ld.param.u64 	%rd19, [addcavity_param_8];
	ld.param.u64 	%rd20, [addcavity_param_9];
	ld.param.f32 	%f47, [addcavity_param_10];
	ld.param.f32 	%f48, [addcavity_param_11];
	ld.param.f32 	%f49, [addcavity_param_12];
	ld.param.f32 	%f50, [addcavity_param_13];
	ld.param.f32 	%f51, [addcavity_param_14];
	ld.param.f32 	%f52, [addcavity_param_15];
	ld.param.u32 	%r76, [addcavity_param_16];
	ld.param.u32 	%r77, [addcavity_param_17];
	ld.param.u32 	%r78, [addcavity_param_18];
	mov.u32 	%r79, %ntid.x;
	mov.u32 	%r80, %ctaid.x;
	mov.u32 	%r81, %tid.x;
	mad.lo.s32 	%r1, %r79, %r80, %r81;
	mov.u32 	%r82, %ntid.y;
	mov.u32 	%r83, %ctaid.y;
	mov.u32 	%r84, %tid.y;
	mad.lo.s32 	%r2, %r82, %r83, %r84;
	mov.u32 	%r85, %ntid.z;
	mov.u32 	%r86, %ctaid.z;
	mov.u32 	%r87, %tid.z;
	mad.lo.s32 	%r3, %r85, %r86, %r87;
	setp.ge.s32	%p1, %r2, %r77;
	setp.ge.s32	%p2, %r1, %r76;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r78;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_52;

	mad.lo.s32 	%r88, %r3, %r77, %r2;
	mad.lo.s32 	%r4, %r88, %r76, %r1;
	setp.eq.s64	%p6, %rd16, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd21, %rd16;
	mul.wide.s32 	%rd22, %r4, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.nc.f32 	%f53, [%rd23];
	mul.f32 	%f129, %f53, %f129;

BB0_3:
	setp.eq.s64	%p7, %rd17, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd24, %rd17;
	mul.wide.s32 	%rd25, %r4, 4;
	add.s64 	%rd26, %rd24, %rd25;
	ld.global.nc.f32 	%f54, [%rd26];
	mul.f32 	%f130, %f54, %f130;

BB0_5:
	mul.f32 	%f5, %f130, %f50;
	neg.f32 	%f55, %f5;
	mul.f32 	%f56, %f5, 0fBFB8AA3B;
	cvt.rzi.f32.f32	%f57, %f56;
	mov.f32 	%f58, 0fBF317200;
	fma.rn.f32 	%f59, %f57, %f58, %f55;
	mov.f32 	%f60, 0fB5BFBE8E;
	fma.rn.f32 	%f61, %f57, %f60, %f59;
	mul.f32 	%f62, %f61, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f6, %f62;
	add.f32 	%f63, %f57, 0f00000000;
	ex2.approx.f32 	%f7, %f63;
	add.u64 	%rd1, %SPL, 0;
	mul.f32 	%f137, %f129, %f50;
	abs.f32 	%f9, %f137;
	setp.neu.f32	%p8, %f9, 0f7F800000;
	mov.f32 	%f131, %f137;
	@%p8 bra 	BB0_7;

	mov.f32 	%f64, 0f00000000;
	mul.rn.f32 	%f131, %f137, %f64;

BB0_7:
	mul.f32 	%f65, %f131, 0f3F22F983;
	cvt.rni.s32.f32	%r190, %f65;
	cvt.rn.f32.s32	%f66, %r190;
	neg.f32 	%f67, %f66;
	mov.f32 	%f68, 0f3FC90FDA;
	fma.rn.f32 	%f69, %f67, %f68, %f131;
	mov.f32 	%f70, 0f33A22168;
	fma.rn.f32 	%f71, %f67, %f70, %f69;
	mov.f32 	%f72, 0f27C234C5;
	fma.rn.f32 	%f132, %f67, %f72, %f71;
	abs.f32 	%f73, %f131;
	add.s64 	%rd2, %rd1, 24;
	setp.lt.f32	%p9, %f5, 0fC2D20000;
	setp.gt.f32	%p10, %f5, 0f42D20000;
	mul.f32 	%f74, %f6, %f7;
	selp.f32	%f75, 0f00000000, %f74, %p10;
	selp.f32	%f13, 0f7F800000, %f75, %p9;
	setp.leu.f32	%p11, %f73, 0f47CE4780;
	@%p11 bra 	BB0_18;

	mov.b32 	 %r6, %f131;
	shr.u32 	%r7, %r6, 23;
	shl.b32 	%r91, %r6, 8;
	or.b32  	%r8, %r91, -2147483648;
	mov.u32 	%r182, 0;
	mov.u64 	%rd45, __cudart_i2opi_f;
	mov.u32 	%r181, -6;
	mov.u64 	%rd46, %rd1;

BB0_9:
	.pragma "nounroll";
	ld.const.u32 	%r94, [%rd45];
	// inline asm
	{
	mad.lo.cc.u32   %r92, %r94, %r8, %r182;
	madc.hi.u32     %r182, %r94, %r8,  0;
	}
	// inline asm
	st.local.u32 	[%rd46], %r92;
	add.s64 	%rd46, %rd46, 4;
	add.s64 	%rd45, %rd45, 4;
	add.s32 	%r181, %r181, 1;
	setp.ne.s32	%p12, %r181, 0;
	@%p12 bra 	BB0_9;

	and.b32  	%r97, %r7, 255;
	add.s32 	%r98, %r97, -128;
	shr.u32 	%r99, %r98, 5;
	and.b32  	%r13, %r6, -2147483648;
	st.local.u32 	[%rd2], %r182;
	mov.u32 	%r100, 6;
	sub.s32 	%r101, %r100, %r99;
	mul.wide.s32 	%rd29, %r101, 4;
	add.s64 	%rd7, %rd1, %rd29;
	ld.local.u32 	%r183, [%rd7];
	ld.local.u32 	%r184, [%rd7+-4];
	and.b32  	%r16, %r7, 31;
	setp.eq.s32	%p13, %r16, 0;
	@%p13 bra 	BB0_12;

	mov.u32 	%r102, 32;
	sub.s32 	%r103, %r102, %r16;
	shr.u32 	%r104, %r184, %r103;
	shl.b32 	%r105, %r183, %r16;
	add.s32 	%r183, %r104, %r105;
	ld.local.u32 	%r106, [%rd7+-8];
	shr.u32 	%r107, %r106, %r103;
	shl.b32 	%r108, %r184, %r16;
	add.s32 	%r184, %r107, %r108;

BB0_12:
	shr.u32 	%r109, %r184, 30;
	shl.b32 	%r110, %r183, 2;
	add.s32 	%r185, %r109, %r110;
	shl.b32 	%r22, %r184, 2;
	shr.u32 	%r111, %r185, 31;
	shr.u32 	%r112, %r183, 30;
	add.s32 	%r23, %r111, %r112;
	setp.eq.s32	%p14, %r111, 0;
	@%p14 bra 	BB0_13;

	not.b32 	%r113, %r185;
	neg.s32 	%r187, %r22;
	setp.eq.s32	%p15, %r22, 0;
	selp.u32	%r114, 1, 0, %p15;
	add.s32 	%r185, %r114, %r113;
	xor.b32  	%r186, %r13, -2147483648;
	bra.uni 	BB0_15;

BB0_13:
	mov.u32 	%r186, %r13;
	mov.u32 	%r187, %r22;

BB0_15:
	clz.b32 	%r189, %r185;
	setp.eq.s32	%p16, %r189, 0;
	shl.b32 	%r115, %r185, %r189;
	mov.u32 	%r116, 32;
	sub.s32 	%r117, %r116, %r189;
	shr.u32 	%r118, %r187, %r117;
	add.s32 	%r119, %r118, %r115;
	selp.b32	%r31, %r185, %r119, %p16;
	mov.u32 	%r120, -921707870;
	mul.hi.u32 	%r188, %r31, %r120;
	setp.eq.s32	%p17, %r13, 0;
	neg.s32 	%r121, %r23;
	selp.b32	%r190, %r23, %r121, %p17;
	setp.lt.s32	%p18, %r188, 1;
	@%p18 bra 	BB0_17;

	mul.lo.s32 	%r122, %r31, -921707870;
	shr.u32 	%r123, %r122, 31;
	shl.b32 	%r124, %r188, 1;
	add.s32 	%r188, %r123, %r124;
	add.s32 	%r189, %r189, 1;

BB0_17:
	mov.u32 	%r125, 126;
	sub.s32 	%r126, %r125, %r189;
	shl.b32 	%r127, %r126, 23;
	add.s32 	%r128, %r188, 1;
	shr.u32 	%r129, %r128, 7;
	add.s32 	%r130, %r129, 1;
	shr.u32 	%r131, %r130, 1;
	add.s32 	%r132, %r131, %r127;
	or.b32  	%r133, %r132, %r186;
	mov.b32 	 %f132, %r133;

BB0_18:
	mul.rn.f32 	%f16, %f132, %f132;
	add.s32 	%r39, %r190, 1;
	and.b32  	%r40, %r39, 1;
	setp.eq.s32	%p19, %r40, 0;
	@%p19 bra 	BB0_20;

	mov.f32 	%f76, 0fBAB6061A;
	mov.f32 	%f77, 0f37CCF5CE;
	fma.rn.f32 	%f133, %f77, %f16, %f76;
	bra.uni 	BB0_21;

BB0_20:
	mov.f32 	%f78, 0f3C08839E;
	mov.f32 	%f79, 0fB94CA1F9;
	fma.rn.f32 	%f133, %f79, %f16, %f78;

BB0_21:
	@%p19 bra 	BB0_23;

	mov.f32 	%f80, 0f3D2AAAA5;
	fma.rn.f32 	%f81, %f133, %f16, %f80;
	mov.f32 	%f82, 0fBF000000;
	fma.rn.f32 	%f134, %f81, %f16, %f82;
	bra.uni 	BB0_24;

BB0_23:
	mov.f32 	%f83, 0fBE2AAAA3;
	fma.rn.f32 	%f84, %f133, %f16, %f83;
	mov.f32 	%f85, 0f00000000;
	fma.rn.f32 	%f134, %f84, %f16, %f85;

BB0_24:
	fma.rn.f32 	%f135, %f134, %f132, %f132;
	@%p19 bra 	BB0_26;

	mov.f32 	%f86, 0f3F800000;
	fma.rn.f32 	%f135, %f134, %f16, %f86;

BB0_26:
	and.b32  	%r134, %r39, 2;
	setp.eq.s32	%p22, %r134, 0;
	@%p22 bra 	BB0_28;

	mov.f32 	%f87, 0f00000000;
	mov.f32 	%f88, 0fBF800000;
	fma.rn.f32 	%f135, %f135, %f88, %f87;

BB0_28:
	@%p8 bra 	BB0_30;

	mov.f32 	%f89, 0f00000000;
	mul.rn.f32 	%f137, %f137, %f89;

BB0_30:
	mul.f32 	%f90, %f137, 0f3F22F983;
	cvt.rni.s32.f32	%r200, %f90;
	cvt.rn.f32.s32	%f91, %r200;
	neg.f32 	%f92, %f91;
	fma.rn.f32 	%f94, %f92, %f68, %f137;
	fma.rn.f32 	%f96, %f92, %f70, %f94;
	fma.rn.f32 	%f138, %f92, %f72, %f96;
	abs.f32 	%f98, %f137;
	setp.leu.f32	%p24, %f98, 0f47CE4780;
	@%p24 bra 	BB0_41;

	mov.b32 	 %r42, %f137;
	shr.u32 	%r43, %r42, 23;
	shl.b32 	%r137, %r42, 8;
	or.b32  	%r44, %r137, -2147483648;
	mov.u32 	%r192, 0;
	mov.u64 	%rd47, __cudart_i2opi_f;
	mov.u32 	%r191, -6;
	mov.u64 	%rd48, %rd1;

BB0_32:
	.pragma "nounroll";
	ld.const.u32 	%r140, [%rd47];
	// inline asm
	{
	mad.lo.cc.u32   %r138, %r140, %r44, %r192;
	madc.hi.u32     %r192, %r140, %r44,  0;
	}
	// inline asm
	st.local.u32 	[%rd48], %r138;
	add.s64 	%rd48, %rd48, 4;
	add.s64 	%rd47, %rd47, 4;
	add.s32 	%r191, %r191, 1;
	setp.ne.s32	%p25, %r191, 0;
	@%p25 bra 	BB0_32;

	and.b32  	%r143, %r43, 255;
	add.s32 	%r144, %r143, -128;
	shr.u32 	%r145, %r144, 5;
	and.b32  	%r49, %r42, -2147483648;
	st.local.u32 	[%rd2], %r192;
	mov.u32 	%r146, 6;
	sub.s32 	%r147, %r146, %r145;
	mul.wide.s32 	%rd31, %r147, 4;
	add.s64 	%rd12, %rd1, %rd31;
	ld.local.u32 	%r193, [%rd12];
	ld.local.u32 	%r194, [%rd12+-4];
	and.b32  	%r52, %r43, 31;
	setp.eq.s32	%p26, %r52, 0;
	@%p26 bra 	BB0_35;

	mov.u32 	%r148, 32;
	sub.s32 	%r149, %r148, %r52;
	shr.u32 	%r150, %r194, %r149;
	shl.b32 	%r151, %r193, %r52;
	add.s32 	%r193, %r150, %r151;
	ld.local.u32 	%r152, [%rd12+-8];
	shr.u32 	%r153, %r152, %r149;
	shl.b32 	%r154, %r194, %r52;
	add.s32 	%r194, %r153, %r154;

BB0_35:
	shr.u32 	%r155, %r194, 30;
	shl.b32 	%r156, %r193, 2;
	add.s32 	%r195, %r155, %r156;
	shl.b32 	%r58, %r194, 2;
	shr.u32 	%r157, %r195, 31;
	shr.u32 	%r158, %r193, 30;
	add.s32 	%r59, %r157, %r158;
	setp.eq.s32	%p27, %r157, 0;
	@%p27 bra 	BB0_36;

	not.b32 	%r159, %r195;
	neg.s32 	%r197, %r58;
	setp.eq.s32	%p28, %r58, 0;
	selp.u32	%r160, 1, 0, %p28;
	add.s32 	%r195, %r160, %r159;
	xor.b32  	%r196, %r49, -2147483648;
	bra.uni 	BB0_38;

BB0_36:
	mov.u32 	%r196, %r49;
	mov.u32 	%r197, %r58;

BB0_38:
	clz.b32 	%r199, %r195;
	setp.eq.s32	%p29, %r199, 0;
	shl.b32 	%r161, %r195, %r199;
	mov.u32 	%r162, 32;
	sub.s32 	%r163, %r162, %r199;
	shr.u32 	%r164, %r197, %r163;
	add.s32 	%r165, %r164, %r161;
	selp.b32	%r67, %r195, %r165, %p29;
	mov.u32 	%r166, -921707870;
	mul.hi.u32 	%r198, %r67, %r166;
	setp.eq.s32	%p30, %r49, 0;
	neg.s32 	%r167, %r59;
	selp.b32	%r200, %r59, %r167, %p30;
	setp.lt.s32	%p31, %r198, 1;
	@%p31 bra 	BB0_40;

	mul.lo.s32 	%r168, %r67, -921707870;
	shr.u32 	%r169, %r168, 31;
	shl.b32 	%r170, %r198, 1;
	add.s32 	%r198, %r169, %r170;
	add.s32 	%r199, %r199, 1;

BB0_40:
	mov.u32 	%r171, 126;
	sub.s32 	%r172, %r171, %r199;
	shl.b32 	%r173, %r172, 23;
	add.s32 	%r174, %r198, 1;
	shr.u32 	%r175, %r174, 7;
	add.s32 	%r176, %r175, 1;
	shr.u32 	%r177, %r176, 1;
	add.s32 	%r178, %r177, %r173;
	or.b32  	%r179, %r178, %r196;
	mov.b32 	 %f138, %r179;

BB0_41:
	mul.rn.f32 	%f33, %f138, %f138;
	and.b32  	%r75, %r200, 1;
	setp.eq.s32	%p32, %r75, 0;
	@%p32 bra 	BB0_43;

	mov.f32 	%f99, 0fBAB6061A;
	mov.f32 	%f100, 0f37CCF5CE;
	fma.rn.f32 	%f139, %f100, %f33, %f99;
	bra.uni 	BB0_44;

BB0_43:
	mov.f32 	%f101, 0f3C08839E;
	mov.f32 	%f102, 0fB94CA1F9;
	fma.rn.f32 	%f139, %f102, %f33, %f101;

BB0_44:
	@%p32 bra 	BB0_46;

	mov.f32 	%f103, 0f3D2AAAA5;
	fma.rn.f32 	%f104, %f139, %f33, %f103;
	mov.f32 	%f105, 0fBF000000;
	fma.rn.f32 	%f140, %f104, %f33, %f105;
	bra.uni 	BB0_47;

BB0_46:
	mov.f32 	%f106, 0fBE2AAAA3;
	fma.rn.f32 	%f107, %f139, %f33, %f106;
	mov.f32 	%f108, 0f00000000;
	fma.rn.f32 	%f140, %f107, %f33, %f108;

BB0_47:
	fma.rn.f32 	%f141, %f140, %f138, %f138;
	@%p32 bra 	BB0_49;

	mov.f32 	%f109, 0f3F800000;
	fma.rn.f32 	%f141, %f140, %f33, %f109;

BB0_49:
	and.b32  	%r180, %r200, 2;
	setp.eq.s32	%p35, %r180, 0;
	@%p35 bra 	BB0_51;

	mov.f32 	%f110, 0f00000000;
	mov.f32 	%f111, 0fBF800000;
	fma.rn.f32 	%f141, %f141, %f111, %f110;

BB0_51:
	cvta.to.global.u64 	%rd32, %rd15;
	cvta.to.global.u64 	%rd33, %rd14;
	cvta.to.global.u64 	%rd34, %rd13;
	cvta.to.global.u64 	%rd35, %rd20;
	cvta.to.global.u64 	%rd36, %rd19;
	cvta.to.global.u64 	%rd37, %rd18;
	mul.f32 	%f112, %f49, %f52;
	sub.f32 	%f113, %f48, %f112;
	mul.f32 	%f114, %f113, %f141;
	mul.f32 	%f115, %f49, %f51;
	sub.f32 	%f116, %f47, %f115;
	mul.f32 	%f117, %f116, %f135;
	sub.f32 	%f118, %f117, %f114;
	mul.f32 	%f119, %f13, %f118;
	mul.wide.s32 	%rd38, %r4, 4;
	add.s64 	%rd39, %rd37, %rd38;
	ld.global.nc.f32 	%f120, [%rd39];
	add.s64 	%rd40, %rd36, %rd38;
	ld.global.nc.f32 	%f121, [%rd40];
	add.s64 	%rd41, %rd35, %rd38;
	ld.global.nc.f32 	%f122, [%rd41];
	add.s64 	%rd42, %rd34, %rd38;
	ld.global.f32 	%f123, [%rd42];
	fma.rn.f32 	%f124, %f120, %f119, %f123;
	st.global.f32 	[%rd42], %f124;
	add.s64 	%rd43, %rd33, %rd38;
	ld.global.f32 	%f125, [%rd43];
	fma.rn.f32 	%f126, %f121, %f119, %f125;
	st.global.f32 	[%rd43], %f126;
	add.s64 	%rd44, %rd32, %rd38;
	ld.global.f32 	%f127, [%rd44];
	fma.rn.f32 	%f128, %f122, %f119, %f127;
	st.global.f32 	[%rd44], %f128;

BB0_52:
	ret;
}


`
   addcavity_ptx_53 = `
.version 6.4
.target sm_53
.address_size 64

	// .globl	addcavity
.const .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry addcavity(
	.param .u64 addcavity_param_0,
	.param .u64 addcavity_param_1,
	.param .u64 addcavity_param_2,
	.param .u64 addcavity_param_3,
	.param .f32 addcavity_param_4,
	.param .u64 addcavity_param_5,
	.param .f32 addcavity_param_6,
	.param .u64 addcavity_param_7,
	.param .u64 addcavity_param_8,
	.param .u64 addcavity_param_9,
	.param .f32 addcavity_param_10,
	.param .f32 addcavity_param_11,
	.param .f32 addcavity_param_12,
	.param .f32 addcavity_param_13,
	.param .f32 addcavity_param_14,
	.param .f32 addcavity_param_15,
	.param .u32 addcavity_param_16,
	.param .u32 addcavity_param_17,
	.param .u32 addcavity_param_18,
	.param .u8 addcavity_param_19
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<36>;
	.reg .f32 	%f<143>;
	.reg .b32 	%r<201>;
	.reg .b64 	%rd<49>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd13, [addcavity_param_0];
	ld.param.u64 	%rd14, [addcavity_param_1];
	ld.param.u64 	%rd15, [addcavity_param_2];
	ld.param.u64 	%rd16, [addcavity_param_3];
	ld.param.f32 	%f129, [addcavity_param_4];
	ld.param.u64 	%rd17, [addcavity_param_5];
	ld.param.f32 	%f130, [addcavity_param_6];
	ld.param.u64 	%rd18, [addcavity_param_7];
	ld.param.u64 	%rd19, [addcavity_param_8];
	ld.param.u64 	%rd20, [addcavity_param_9];
	ld.param.f32 	%f47, [addcavity_param_10];
	ld.param.f32 	%f48, [addcavity_param_11];
	ld.param.f32 	%f49, [addcavity_param_12];
	ld.param.f32 	%f50, [addcavity_param_13];
	ld.param.f32 	%f51, [addcavity_param_14];
	ld.param.f32 	%f52, [addcavity_param_15];
	ld.param.u32 	%r76, [addcavity_param_16];
	ld.param.u32 	%r77, [addcavity_param_17];
	ld.param.u32 	%r78, [addcavity_param_18];
	mov.u32 	%r79, %ntid.x;
	mov.u32 	%r80, %ctaid.x;
	mov.u32 	%r81, %tid.x;
	mad.lo.s32 	%r1, %r79, %r80, %r81;
	mov.u32 	%r82, %ntid.y;
	mov.u32 	%r83, %ctaid.y;
	mov.u32 	%r84, %tid.y;
	mad.lo.s32 	%r2, %r82, %r83, %r84;
	mov.u32 	%r85, %ntid.z;
	mov.u32 	%r86, %ctaid.z;
	mov.u32 	%r87, %tid.z;
	mad.lo.s32 	%r3, %r85, %r86, %r87;
	setp.ge.s32	%p1, %r2, %r77;
	setp.ge.s32	%p2, %r1, %r76;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r78;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_52;

	mad.lo.s32 	%r88, %r3, %r77, %r2;
	mad.lo.s32 	%r4, %r88, %r76, %r1;
	setp.eq.s64	%p6, %rd16, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd21, %rd16;
	mul.wide.s32 	%rd22, %r4, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.nc.f32 	%f53, [%rd23];
	mul.f32 	%f129, %f53, %f129;

BB0_3:
	setp.eq.s64	%p7, %rd17, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd24, %rd17;
	mul.wide.s32 	%rd25, %r4, 4;
	add.s64 	%rd26, %rd24, %rd25;
	ld.global.nc.f32 	%f54, [%rd26];
	mul.f32 	%f130, %f54, %f130;

BB0_5:
	mul.f32 	%f5, %f130, %f50;
	neg.f32 	%f55, %f5;
	mul.f32 	%f56, %f5, 0fBFB8AA3B;
	cvt.rzi.f32.f32	%f57, %f56;
	mov.f32 	%f58, 0fBF317200;
	fma.rn.f32 	%f59, %f57, %f58, %f55;
	mov.f32 	%f60, 0fB5BFBE8E;
	fma.rn.f32 	%f61, %f57, %f60, %f59;
	mul.f32 	%f62, %f61, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f6, %f62;
	add.f32 	%f63, %f57, 0f00000000;
	ex2.approx.f32 	%f7, %f63;
	add.u64 	%rd1, %SPL, 0;
	mul.f32 	%f137, %f129, %f50;
	abs.f32 	%f9, %f137;
	setp.neu.f32	%p8, %f9, 0f7F800000;
	mov.f32 	%f131, %f137;
	@%p8 bra 	BB0_7;

	mov.f32 	%f64, 0f00000000;
	mul.rn.f32 	%f131, %f137, %f64;

BB0_7:
	mul.f32 	%f65, %f131, 0f3F22F983;
	cvt.rni.s32.f32	%r190, %f65;
	cvt.rn.f32.s32	%f66, %r190;
	neg.f32 	%f67, %f66;
	mov.f32 	%f68, 0f3FC90FDA;
	fma.rn.f32 	%f69, %f67, %f68, %f131;
	mov.f32 	%f70, 0f33A22168;
	fma.rn.f32 	%f71, %f67, %f70, %f69;
	mov.f32 	%f72, 0f27C234C5;
	fma.rn.f32 	%f132, %f67, %f72, %f71;
	abs.f32 	%f73, %f131;
	add.s64 	%rd2, %rd1, 24;
	setp.lt.f32	%p9, %f5, 0fC2D20000;
	setp.gt.f32	%p10, %f5, 0f42D20000;
	mul.f32 	%f74, %f6, %f7;
	selp.f32	%f75, 0f00000000, %f74, %p10;
	selp.f32	%f13, 0f7F800000, %f75, %p9;
	setp.leu.f32	%p11, %f73, 0f47CE4780;
	@%p11 bra 	BB0_18;

	mov.b32 	 %r6, %f131;
	shr.u32 	%r7, %r6, 23;
	shl.b32 	%r91, %r6, 8;
	or.b32  	%r8, %r91, -2147483648;
	mov.u32 	%r182, 0;
	mov.u64 	%rd45, __cudart_i2opi_f;
	mov.u32 	%r181, -6;
	mov.u64 	%rd46, %rd1;

BB0_9:
	.pragma "nounroll";
	ld.const.u32 	%r94, [%rd45];
	// inline asm
	{
	mad.lo.cc.u32   %r92, %r94, %r8, %r182;
	madc.hi.u32     %r182, %r94, %r8,  0;
	}
	// inline asm
	st.local.u32 	[%rd46], %r92;
	add.s64 	%rd46, %rd46, 4;
	add.s64 	%rd45, %rd45, 4;
	add.s32 	%r181, %r181, 1;
	setp.ne.s32	%p12, %r181, 0;
	@%p12 bra 	BB0_9;

	and.b32  	%r97, %r7, 255;
	add.s32 	%r98, %r97, -128;
	shr.u32 	%r99, %r98, 5;
	and.b32  	%r13, %r6, -2147483648;
	st.local.u32 	[%rd2], %r182;
	mov.u32 	%r100, 6;
	sub.s32 	%r101, %r100, %r99;
	mul.wide.s32 	%rd29, %r101, 4;
	add.s64 	%rd7, %rd1, %rd29;
	ld.local.u32 	%r183, [%rd7];
	ld.local.u32 	%r184, [%rd7+-4];
	and.b32  	%r16, %r7, 31;
	setp.eq.s32	%p13, %r16, 0;
	@%p13 bra 	BB0_12;

	mov.u32 	%r102, 32;
	sub.s32 	%r103, %r102, %r16;
	shr.u32 	%r104, %r184, %r103;
	shl.b32 	%r105, %r183, %r16;
	add.s32 	%r183, %r104, %r105;
	ld.local.u32 	%r106, [%rd7+-8];
	shr.u32 	%r107, %r106, %r103;
	shl.b32 	%r108, %r184, %r16;
	add.s32 	%r184, %r107, %r108;

BB0_12:
	shr.u32 	%r109, %r184, 30;
	shl.b32 	%r110, %r183, 2;
	add.s32 	%r185, %r109, %r110;
	shl.b32 	%r22, %r184, 2;
	shr.u32 	%r111, %r185, 31;
	shr.u32 	%r112, %r183, 30;
	add.s32 	%r23, %r111, %r112;
	setp.eq.s32	%p14, %r111, 0;
	@%p14 bra 	BB0_13;

	not.b32 	%r113, %r185;
	neg.s32 	%r187, %r22;
	setp.eq.s32	%p15, %r22, 0;
	selp.u32	%r114, 1, 0, %p15;
	add.s32 	%r185, %r114, %r113;
	xor.b32  	%r186, %r13, -2147483648;
	bra.uni 	BB0_15;

BB0_13:
	mov.u32 	%r186, %r13;
	mov.u32 	%r187, %r22;

BB0_15:
	clz.b32 	%r189, %r185;
	setp.eq.s32	%p16, %r189, 0;
	shl.b32 	%r115, %r185, %r189;
	mov.u32 	%r116, 32;
	sub.s32 	%r117, %r116, %r189;
	shr.u32 	%r118, %r187, %r117;
	add.s32 	%r119, %r118, %r115;
	selp.b32	%r31, %r185, %r119, %p16;
	mov.u32 	%r120, -921707870;
	mul.hi.u32 	%r188, %r31, %r120;
	setp.eq.s32	%p17, %r13, 0;
	neg.s32 	%r121, %r23;
	selp.b32	%r190, %r23, %r121, %p17;
	setp.lt.s32	%p18, %r188, 1;
	@%p18 bra 	BB0_17;

	mul.lo.s32 	%r122, %r31, -921707870;
	shr.u32 	%r123, %r122, 31;
	shl.b32 	%r124, %r188, 1;
	add.s32 	%r188, %r123, %r124;
	add.s32 	%r189, %r189, 1;

BB0_17:
	mov.u32 	%r125, 126;
	sub.s32 	%r126, %r125, %r189;
	shl.b32 	%r127, %r126, 23;
	add.s32 	%r128, %r188, 1;
	shr.u32 	%r129, %r128, 7;
	add.s32 	%r130, %r129, 1;
	shr.u32 	%r131, %r130, 1;
	add.s32 	%r132, %r131, %r127;
	or.b32  	%r133, %r132, %r186;
	mov.b32 	 %f132, %r133;

BB0_18:
	mul.rn.f32 	%f16, %f132, %f132;
	add.s32 	%r39, %r190, 1;
	and.b32  	%r40, %r39, 1;
	setp.eq.s32	%p19, %r40, 0;
	@%p19 bra 	BB0_20;

	mov.f32 	%f76, 0fBAB6061A;
	mov.f32 	%f77, 0f37CCF5CE;
	fma.rn.f32 	%f133, %f77, %f16, %f76;
	bra.uni 	BB0_21;

BB0_20:
	mov.f32 	%f78, 0f3C08839E;
	mov.f32 	%f79, 0fB94CA1F9;
	fma.rn.f32 	%f133, %f79, %f16, %f78;

BB0_21:
	@%p19 bra 	BB0_23;

	mov.f32 	%f80, 0f3D2AAAA5;
	fma.rn.f32 	%f81, %f133, %f16, %f80;
	mov.f32 	%f82, 0fBF000000;
	fma.rn.f32 	%f134, %f81, %f16, %f82;
	bra.uni 	BB0_24;

BB0_23:
	mov.f32 	%f83, 0fBE2AAAA3;
	fma.rn.f32 	%f84, %f133, %f16, %f83;
	mov.f32 	%f85, 0f00000000;
	fma.rn.f32 	%f134, %f84, %f16, %f85;

BB0_24:
	fma.rn.f32 	%f135, %f134, %f132, %f132;
	@%p19 bra 	BB0_26;

	mov.f32 	%f86, 0f3F800000;
	fma.rn.f32 	%f135, %f134, %f16, %f86;

BB0_26:
	and.b32  	%r134, %r39, 2;
	setp.eq.s32	%p22, %r134, 0;
	@%p22 bra 	BB0_28;

	mov.f32 	%f87, 0f00000000;
	mov.f32 	%f88, 0fBF800000;
	fma.rn.f32 	%f135, %f135, %f88, %f87;

BB0_28:
	@%p8 bra 	BB0_30;

	mov.f32 	%f89, 0f00000000;
	mul.rn.f32 	%f137, %f137, %f89;

BB0_30:
	mul.f32 	%f90, %f137, 0f3F22F983;
	cvt.rni.s32.f32	%r200, %f90;
	cvt.rn.f32.s32	%f91, %r200;
	neg.f32 	%f92, %f91;
	fma.rn.f32 	%f94, %f92, %f68, %f137;
	fma.rn.f32 	%f96, %f92, %f70, %f94;
	fma.rn.f32 	%f138, %f92, %f72, %f96;
	abs.f32 	%f98, %f137;
	setp.leu.f32	%p24, %f98, 0f47CE4780;
	@%p24 bra 	BB0_41;

	mov.b32 	 %r42, %f137;
	shr.u32 	%r43, %r42, 23;
	shl.b32 	%r137, %r42, 8;
	or.b32  	%r44, %r137, -2147483648;
	mov.u32 	%r192, 0;
	mov.u64 	%rd47, __cudart_i2opi_f;
	mov.u32 	%r191, -6;
	mov.u64 	%rd48, %rd1;

BB0_32:
	.pragma "nounroll";
	ld.const.u32 	%r140, [%rd47];
	// inline asm
	{
	mad.lo.cc.u32   %r138, %r140, %r44, %r192;
	madc.hi.u32     %r192, %r140, %r44,  0;
	}
	// inline asm
	st.local.u32 	[%rd48], %r138;
	add.s64 	%rd48, %rd48, 4;
	add.s64 	%rd47, %rd47, 4;
	add.s32 	%r191, %r191, 1;
	setp.ne.s32	%p25, %r191, 0;
	@%p25 bra 	BB0_32;

	and.b32  	%r143, %r43, 255;
	add.s32 	%r144, %r143, -128;
	shr.u32 	%r145, %r144, 5;
	and.b32  	%r49, %r42, -2147483648;
	st.local.u32 	[%rd2], %r192;
	mov.u32 	%r146, 6;
	sub.s32 	%r147, %r146, %r145;
	mul.wide.s32 	%rd31, %r147, 4;
	add.s64 	%rd12, %rd1, %rd31;
	ld.local.u32 	%r193, [%rd12];
	ld.local.u32 	%r194, [%rd12+-4];
	and.b32  	%r52, %r43, 31;
	setp.eq.s32	%p26, %r52, 0;
	@%p26 bra 	BB0_35;

	mov.u32 	%r148, 32;
	sub.s32 	%r149, %r148, %r52;
	shr.u32 	%r150, %r194, %r149;
	shl.b32 	%r151, %r193, %r52;
	add.s32 	%r193, %r150, %r151;
	ld.local.u32 	%r152, [%rd12+-8];
	shr.u32 	%r153, %r152, %r149;
	shl.b32 	%r154, %r194, %r52;
	add.s32 	%r194, %r153, %r154;

BB0_35:
	shr.u32 	%r155, %r194, 30;
	shl.b32 	%r156, %r193, 2;
	add.s32 	%r195, %r155, %r156;
	shl.b32 	%r58, %r194, 2;
	shr.u32 	%r157, %r195, 31;
	shr.u32 	%r158, %r193, 30;
	add.s32 	%r59, %r157, %r158;
	setp.eq.s32	%p27, %r157, 0;
	@%p27 bra 	BB0_36;

	not.b32 	%r159, %r195;
	neg.s32 	%r197, %r58;
	setp.eq.s32	%p28, %r58, 0;
	selp.u32	%r160, 1, 0, %p28;
	add.s32 	%r195, %r160, %r159;
	xor.b32  	%r196, %r49, -2147483648;
	bra.uni 	BB0_38;

BB0_36:
	mov.u32 	%r196, %r49;
	mov.u32 	%r197, %r58;

BB0_38:
	clz.b32 	%r199, %r195;
	setp.eq.s32	%p29, %r199, 0;
	shl.b32 	%r161, %r195, %r199;
	mov.u32 	%r162, 32;
	sub.s32 	%r163, %r162, %r199;
	shr.u32 	%r164, %r197, %r163;
	add.s32 	%r165, %r164, %r161;
	selp.b32	%r67, %r195, %r165, %p29;
	mov.u32 	%r166, -921707870;
	mul.hi.u32 	%r198, %r67, %r166;
	setp.eq.s32	%p30, %r49, 0;
	neg.s32 	%r167, %r59;
	selp.b32	%r200, %r59, %r167, %p30;
	setp.lt.s32	%p31, %r198, 1;
	@%p31 bra 	BB0_40;

	mul.lo.s32 	%r168, %r67, -921707870;
	shr.u32 	%r169, %r168, 31;
	shl.b32 	%r170, %r198, 1;
	add.s32 	%r198, %r169, %r170;
	add.s32 	%r199, %r199, 1;

BB0_40:
	mov.u32 	%r171, 126;
	sub.s32 	%r172, %r171, %r199;
	shl.b32 	%r173, %r172, 23;
	add.s32 	%r174, %r198, 1;
	shr.u32 	%r175, %r174, 7;
	add.s32 	%r176, %r175, 1;
	shr.u32 	%r177, %r176, 1;
	add.s32 	%r178, %r177, %r173;
	or.b32  	%r179, %r178, %r196;
	mov.b32 	 %f138, %r179;

BB0_41:
	mul.rn.f32 	%f33, %f138, %f138;
	and.b32  	%r75, %r200, 1;
	setp.eq.s32	%p32, %r75, 0;
	@%p32 bra 	BB0_43;

	mov.f32 	%f99, 0fBAB6061A;
	mov.f32 	%f100, 0f37CCF5CE;
	fma.rn.f32 	%f139, %f100, %f33, %f99;
	bra.uni 	BB0_44;

BB0_43:
	mov.f32 	%f101, 0f3C08839E;
	mov.f32 	%f102, 0fB94CA1F9;
	fma.rn.f32 	%f139, %f102, %f33, %f101;

BB0_44:
	@%p32 bra 	BB0_46;

	mov.f32 	%f103, 0f3D2AAAA5;
	fma.rn.f32 	%f104, %f139, %f33, %f103;
	mov.f32 	%f105, 0fBF000000;
	fma.rn.f32 	%f140, %f104, %f33, %f105;
	bra.uni 	BB0_47;

BB0_46:
	mov.f32 	%f106, 0fBE2AAAA3;
	fma.rn.f32 	%f107, %f139, %f33, %f106;
	mov.f32 	%f108, 0f00000000;
	fma.rn.f32 	%f140, %f107, %f33, %f108;

BB0_47:
	fma.rn.f32 	%f141, %f140, %f138, %f138;
	@%p32 bra 	BB0_49;

	mov.f32 	%f109, 0f3F800000;
	fma.rn.f32 	%f141, %f140, %f33, %f109;

BB0_49:
	and.b32  	%r180, %r200, 2;
	setp.eq.s32	%p35, %r180, 0;
	@%p35 bra 	BB0_51;

	mov.f32 	%f110, 0f00000000;
	mov.f32 	%f111, 0fBF800000;
	fma.rn.f32 	%f141, %f141, %f111, %f110;

BB0_51:
	cvta.to.global.u64 	%rd32, %rd15;
	cvta.to.global.u64 	%rd33, %rd14;
	cvta.to.global.u64 	%rd34, %rd13;
	cvta.to.global.u64 	%rd35, %rd20;
	cvta.to.global.u64 	%rd36, %rd19;
	cvta.to.global.u64 	%rd37, %rd18;
	mul.f32 	%f112, %f49, %f52;
	sub.f32 	%f113, %f48, %f112;
	mul.f32 	%f114, %f113, %f141;
	mul.f32 	%f115, %f49, %f51;
	sub.f32 	%f116, %f47, %f115;
	mul.f32 	%f117, %f116, %f135;
	sub.f32 	%f118, %f117, %f114;
	mul.f32 	%f119, %f13, %f118;
	mul.wide.s32 	%rd38, %r4, 4;
	add.s64 	%rd39, %rd37, %rd38;
	ld.global.nc.f32 	%f120, [%rd39];
	add.s64 	%rd40, %rd36, %rd38;
	ld.global.nc.f32 	%f121, [%rd40];
	add.s64 	%rd41, %rd35, %rd38;
	ld.global.nc.f32 	%f122, [%rd41];
	add.s64 	%rd42, %rd34, %rd38;
	ld.global.f32 	%f123, [%rd42];
	fma.rn.f32 	%f124, %f120, %f119, %f123;
	st.global.f32 	[%rd42], %f124;
	add.s64 	%rd43, %rd33, %rd38;
	ld.global.f32 	%f125, [%rd43];
	fma.rn.f32 	%f126, %f121, %f119, %f125;
	st.global.f32 	[%rd43], %f126;
	add.s64 	%rd44, %rd32, %rd38;
	ld.global.f32 	%f127, [%rd44];
	fma.rn.f32 	%f128, %f122, %f119, %f127;
	st.global.f32 	[%rd44], %f128;

BB0_52:
	ret;
}


`
   addcavity_ptx_60 = `
.version 6.4
.target sm_60
.address_size 64

	// .globl	addcavity
.const .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry addcavity(
	.param .u64 addcavity_param_0,
	.param .u64 addcavity_param_1,
	.param .u64 addcavity_param_2,
	.param .u64 addcavity_param_3,
	.param .f32 addcavity_param_4,
	.param .u64 addcavity_param_5,
	.param .f32 addcavity_param_6,
	.param .u64 addcavity_param_7,
	.param .u64 addcavity_param_8,
	.param .u64 addcavity_param_9,
	.param .f32 addcavity_param_10,
	.param .f32 addcavity_param_11,
	.param .f32 addcavity_param_12,
	.param .f32 addcavity_param_13,
	.param .f32 addcavity_param_14,
	.param .f32 addcavity_param_15,
	.param .u32 addcavity_param_16,
	.param .u32 addcavity_param_17,
	.param .u32 addcavity_param_18,
	.param .u8 addcavity_param_19
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<36>;
	.reg .f32 	%f<143>;
	.reg .b32 	%r<201>;
	.reg .b64 	%rd<49>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd13, [addcavity_param_0];
	ld.param.u64 	%rd14, [addcavity_param_1];
	ld.param.u64 	%rd15, [addcavity_param_2];
	ld.param.u64 	%rd16, [addcavity_param_3];
	ld.param.f32 	%f129, [addcavity_param_4];
	ld.param.u64 	%rd17, [addcavity_param_5];
	ld.param.f32 	%f130, [addcavity_param_6];
	ld.param.u64 	%rd18, [addcavity_param_7];
	ld.param.u64 	%rd19, [addcavity_param_8];
	ld.param.u64 	%rd20, [addcavity_param_9];
	ld.param.f32 	%f47, [addcavity_param_10];
	ld.param.f32 	%f48, [addcavity_param_11];
	ld.param.f32 	%f49, [addcavity_param_12];
	ld.param.f32 	%f50, [addcavity_param_13];
	ld.param.f32 	%f51, [addcavity_param_14];
	ld.param.f32 	%f52, [addcavity_param_15];
	ld.param.u32 	%r76, [addcavity_param_16];
	ld.param.u32 	%r77, [addcavity_param_17];
	ld.param.u32 	%r78, [addcavity_param_18];
	mov.u32 	%r79, %ntid.x;
	mov.u32 	%r80, %ctaid.x;
	mov.u32 	%r81, %tid.x;
	mad.lo.s32 	%r1, %r79, %r80, %r81;
	mov.u32 	%r82, %ntid.y;
	mov.u32 	%r83, %ctaid.y;
	mov.u32 	%r84, %tid.y;
	mad.lo.s32 	%r2, %r82, %r83, %r84;
	mov.u32 	%r85, %ntid.z;
	mov.u32 	%r86, %ctaid.z;
	mov.u32 	%r87, %tid.z;
	mad.lo.s32 	%r3, %r85, %r86, %r87;
	setp.ge.s32	%p1, %r2, %r77;
	setp.ge.s32	%p2, %r1, %r76;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r78;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_52;

	mad.lo.s32 	%r88, %r3, %r77, %r2;
	mad.lo.s32 	%r4, %r88, %r76, %r1;
	setp.eq.s64	%p6, %rd16, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd21, %rd16;
	mul.wide.s32 	%rd22, %r4, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.nc.f32 	%f53, [%rd23];
	mul.f32 	%f129, %f53, %f129;

BB0_3:
	setp.eq.s64	%p7, %rd17, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd24, %rd17;
	mul.wide.s32 	%rd25, %r4, 4;
	add.s64 	%rd26, %rd24, %rd25;
	ld.global.nc.f32 	%f54, [%rd26];
	mul.f32 	%f130, %f54, %f130;

BB0_5:
	mul.f32 	%f5, %f130, %f50;
	neg.f32 	%f55, %f5;
	mul.f32 	%f56, %f5, 0fBFB8AA3B;
	cvt.rzi.f32.f32	%f57, %f56;
	mov.f32 	%f58, 0fBF317200;
	fma.rn.f32 	%f59, %f57, %f58, %f55;
	mov.f32 	%f60, 0fB5BFBE8E;
	fma.rn.f32 	%f61, %f57, %f60, %f59;
	mul.f32 	%f62, %f61, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f6, %f62;
	add.f32 	%f63, %f57, 0f00000000;
	ex2.approx.f32 	%f7, %f63;
	add.u64 	%rd1, %SPL, 0;
	mul.f32 	%f137, %f129, %f50;
	abs.f32 	%f9, %f137;
	setp.neu.f32	%p8, %f9, 0f7F800000;
	mov.f32 	%f131, %f137;
	@%p8 bra 	BB0_7;

	mov.f32 	%f64, 0f00000000;
	mul.rn.f32 	%f131, %f137, %f64;

BB0_7:
	mul.f32 	%f65, %f131, 0f3F22F983;
	cvt.rni.s32.f32	%r190, %f65;
	cvt.rn.f32.s32	%f66, %r190;
	neg.f32 	%f67, %f66;
	mov.f32 	%f68, 0f3FC90FDA;
	fma.rn.f32 	%f69, %f67, %f68, %f131;
	mov.f32 	%f70, 0f33A22168;
	fma.rn.f32 	%f71, %f67, %f70, %f69;
	mov.f32 	%f72, 0f27C234C5;
	fma.rn.f32 	%f132, %f67, %f72, %f71;
	abs.f32 	%f73, %f131;
	add.s64 	%rd2, %rd1, 24;
	setp.lt.f32	%p9, %f5, 0fC2D20000;
	setp.gt.f32	%p10, %f5, 0f42D20000;
	mul.f32 	%f74, %f6, %f7;
	selp.f32	%f75, 0f00000000, %f74, %p10;
	selp.f32	%f13, 0f7F800000, %f75, %p9;
	setp.leu.f32	%p11, %f73, 0f47CE4780;
	@%p11 bra 	BB0_18;

	mov.b32 	 %r6, %f131;
	shr.u32 	%r7, %r6, 23;
	shl.b32 	%r91, %r6, 8;
	or.b32  	%r8, %r91, -2147483648;
	mov.u32 	%r182, 0;
	mov.u64 	%rd45, __cudart_i2opi_f;
	mov.u32 	%r181, -6;
	mov.u64 	%rd46, %rd1;

BB0_9:
	.pragma "nounroll";
	ld.const.u32 	%r94, [%rd45];
	// inline asm
	{
	mad.lo.cc.u32   %r92, %r94, %r8, %r182;
	madc.hi.u32     %r182, %r94, %r8,  0;
	}
	// inline asm
	st.local.u32 	[%rd46], %r92;
	add.s64 	%rd46, %rd46, 4;
	add.s64 	%rd45, %rd45, 4;
	add.s32 	%r181, %r181, 1;
	setp.ne.s32	%p12, %r181, 0;
	@%p12 bra 	BB0_9;

	and.b32  	%r97, %r7, 255;
	add.s32 	%r98, %r97, -128;
	shr.u32 	%r99, %r98, 5;
	and.b32  	%r13, %r6, -2147483648;
	st.local.u32 	[%rd2], %r182;
	mov.u32 	%r100, 6;
	sub.s32 	%r101, %r100, %r99;
	mul.wide.s32 	%rd29, %r101, 4;
	add.s64 	%rd7, %rd1, %rd29;
	ld.local.u32 	%r183, [%rd7];
	ld.local.u32 	%r184, [%rd7+-4];
	and.b32  	%r16, %r7, 31;
	setp.eq.s32	%p13, %r16, 0;
	@%p13 bra 	BB0_12;

	mov.u32 	%r102, 32;
	sub.s32 	%r103, %r102, %r16;
	shr.u32 	%r104, %r184, %r103;
	shl.b32 	%r105, %r183, %r16;
	add.s32 	%r183, %r104, %r105;
	ld.local.u32 	%r106, [%rd7+-8];
	shr.u32 	%r107, %r106, %r103;
	shl.b32 	%r108, %r184, %r16;
	add.s32 	%r184, %r107, %r108;

BB0_12:
	shr.u32 	%r109, %r184, 30;
	shl.b32 	%r110, %r183, 2;
	add.s32 	%r185, %r109, %r110;
	shl.b32 	%r22, %r184, 2;
	shr.u32 	%r111, %r185, 31;
	shr.u32 	%r112, %r183, 30;
	add.s32 	%r23, %r111, %r112;
	setp.eq.s32	%p14, %r111, 0;
	@%p14 bra 	BB0_13;

	not.b32 	%r113, %r185;
	neg.s32 	%r187, %r22;
	setp.eq.s32	%p15, %r22, 0;
	selp.u32	%r114, 1, 0, %p15;
	add.s32 	%r185, %r114, %r113;
	xor.b32  	%r186, %r13, -2147483648;
	bra.uni 	BB0_15;

BB0_13:
	mov.u32 	%r186, %r13;
	mov.u32 	%r187, %r22;

BB0_15:
	clz.b32 	%r189, %r185;
	setp.eq.s32	%p16, %r189, 0;
	shl.b32 	%r115, %r185, %r189;
	mov.u32 	%r116, 32;
	sub.s32 	%r117, %r116, %r189;
	shr.u32 	%r118, %r187, %r117;
	add.s32 	%r119, %r118, %r115;
	selp.b32	%r31, %r185, %r119, %p16;
	mov.u32 	%r120, -921707870;
	mul.hi.u32 	%r188, %r31, %r120;
	setp.eq.s32	%p17, %r13, 0;
	neg.s32 	%r121, %r23;
	selp.b32	%r190, %r23, %r121, %p17;
	setp.lt.s32	%p18, %r188, 1;
	@%p18 bra 	BB0_17;

	mul.lo.s32 	%r122, %r31, -921707870;
	shr.u32 	%r123, %r122, 31;
	shl.b32 	%r124, %r188, 1;
	add.s32 	%r188, %r123, %r124;
	add.s32 	%r189, %r189, 1;

BB0_17:
	mov.u32 	%r125, 126;
	sub.s32 	%r126, %r125, %r189;
	shl.b32 	%r127, %r126, 23;
	add.s32 	%r128, %r188, 1;
	shr.u32 	%r129, %r128, 7;
	add.s32 	%r130, %r129, 1;
	shr.u32 	%r131, %r130, 1;
	add.s32 	%r132, %r131, %r127;
	or.b32  	%r133, %r132, %r186;
	mov.b32 	 %f132, %r133;

BB0_18:
	mul.rn.f32 	%f16, %f132, %f132;
	add.s32 	%r39, %r190, 1;
	and.b32  	%r40, %r39, 1;
	setp.eq.s32	%p19, %r40, 0;
	@%p19 bra 	BB0_20;

	mov.f32 	%f76, 0fBAB6061A;
	mov.f32 	%f77, 0f37CCF5CE;
	fma.rn.f32 	%f133, %f77, %f16, %f76;
	bra.uni 	BB0_21;

BB0_20:
	mov.f32 	%f78, 0f3C08839E;
	mov.f32 	%f79, 0fB94CA1F9;
	fma.rn.f32 	%f133, %f79, %f16, %f78;

BB0_21:
	@%p19 bra 	BB0_23;

	mov.f32 	%f80, 0f3D2AAAA5;
	fma.rn.f32 	%f81, %f133, %f16, %f80;
	mov.f32 	%f82, 0fBF000000;
	fma.rn.f32 	%f134, %f81, %f16, %f82;
	bra.uni 	BB0_24;

BB0_23:
	mov.f32 	%f83, 0fBE2AAAA3;
	fma.rn.f32 	%f84, %f133, %f16, %f83;
	mov.f32 	%f85, 0f00000000;
	fma.rn.f32 	%f134, %f84, %f16, %f85;

BB0_24:
	fma.rn.f32 	%f135, %f134, %f132, %f132;
	@%p19 bra 	BB0_26;

	mov.f32 	%f86, 0f3F800000;
	fma.rn.f32 	%f135, %f134, %f16, %f86;

BB0_26:
	and.b32  	%r134, %r39, 2;
	setp.eq.s32	%p22, %r134, 0;
	@%p22 bra 	BB0_28;

	mov.f32 	%f87, 0f00000000;
	mov.f32 	%f88, 0fBF800000;
	fma.rn.f32 	%f135, %f135, %f88, %f87;

BB0_28:
	@%p8 bra 	BB0_30;

	mov.f32 	%f89, 0f00000000;
	mul.rn.f32 	%f137, %f137, %f89;

BB0_30:
	mul.f32 	%f90, %f137, 0f3F22F983;
	cvt.rni.s32.f32	%r200, %f90;
	cvt.rn.f32.s32	%f91, %r200;
	neg.f32 	%f92, %f91;
	fma.rn.f32 	%f94, %f92, %f68, %f137;
	fma.rn.f32 	%f96, %f92, %f70, %f94;
	fma.rn.f32 	%f138, %f92, %f72, %f96;
	abs.f32 	%f98, %f137;
	setp.leu.f32	%p24, %f98, 0f47CE4780;
	@%p24 bra 	BB0_41;

	mov.b32 	 %r42, %f137;
	shr.u32 	%r43, %r42, 23;
	shl.b32 	%r137, %r42, 8;
	or.b32  	%r44, %r137, -2147483648;
	mov.u32 	%r192, 0;
	mov.u64 	%rd47, __cudart_i2opi_f;
	mov.u32 	%r191, -6;
	mov.u64 	%rd48, %rd1;

BB0_32:
	.pragma "nounroll";
	ld.const.u32 	%r140, [%rd47];
	// inline asm
	{
	mad.lo.cc.u32   %r138, %r140, %r44, %r192;
	madc.hi.u32     %r192, %r140, %r44,  0;
	}
	// inline asm
	st.local.u32 	[%rd48], %r138;
	add.s64 	%rd48, %rd48, 4;
	add.s64 	%rd47, %rd47, 4;
	add.s32 	%r191, %r191, 1;
	setp.ne.s32	%p25, %r191, 0;
	@%p25 bra 	BB0_32;

	and.b32  	%r143, %r43, 255;
	add.s32 	%r144, %r143, -128;
	shr.u32 	%r145, %r144, 5;
	and.b32  	%r49, %r42, -2147483648;
	st.local.u32 	[%rd2], %r192;
	mov.u32 	%r146, 6;
	sub.s32 	%r147, %r146, %r145;
	mul.wide.s32 	%rd31, %r147, 4;
	add.s64 	%rd12, %rd1, %rd31;
	ld.local.u32 	%r193, [%rd12];
	ld.local.u32 	%r194, [%rd12+-4];
	and.b32  	%r52, %r43, 31;
	setp.eq.s32	%p26, %r52, 0;
	@%p26 bra 	BB0_35;

	mov.u32 	%r148, 32;
	sub.s32 	%r149, %r148, %r52;
	shr.u32 	%r150, %r194, %r149;
	shl.b32 	%r151, %r193, %r52;
	add.s32 	%r193, %r150, %r151;
	ld.local.u32 	%r152, [%rd12+-8];
	shr.u32 	%r153, %r152, %r149;
	shl.b32 	%r154, %r194, %r52;
	add.s32 	%r194, %r153, %r154;

BB0_35:
	shr.u32 	%r155, %r194, 30;
	shl.b32 	%r156, %r193, 2;
	add.s32 	%r195, %r155, %r156;
	shl.b32 	%r58, %r194, 2;
	shr.u32 	%r157, %r195, 31;
	shr.u32 	%r158, %r193, 30;
	add.s32 	%r59, %r157, %r158;
	setp.eq.s32	%p27, %r157, 0;
	@%p27 bra 	BB0_36;

	not.b32 	%r159, %r195;
	neg.s32 	%r197, %r58;
	setp.eq.s32	%p28, %r58, 0;
	selp.u32	%r160, 1, 0, %p28;
	add.s32 	%r195, %r160, %r159;
	xor.b32  	%r196, %r49, -2147483648;
	bra.uni 	BB0_38;

BB0_36:
	mov.u32 	%r196, %r49;
	mov.u32 	%r197, %r58;

BB0_38:
	clz.b32 	%r199, %r195;
	setp.eq.s32	%p29, %r199, 0;
	shl.b32 	%r161, %r195, %r199;
	mov.u32 	%r162, 32;
	sub.s32 	%r163, %r162, %r199;
	shr.u32 	%r164, %r197, %r163;
	add.s32 	%r165, %r164, %r161;
	selp.b32	%r67, %r195, %r165, %p29;
	mov.u32 	%r166, -921707870;
	mul.hi.u32 	%r198, %r67, %r166;
	setp.eq.s32	%p30, %r49, 0;
	neg.s32 	%r167, %r59;
	selp.b32	%r200, %r59, %r167, %p30;
	setp.lt.s32	%p31, %r198, 1;
	@%p31 bra 	BB0_40;

	mul.lo.s32 	%r168, %r67, -921707870;
	shr.u32 	%r169, %r168, 31;
	shl.b32 	%r170, %r198, 1;
	add.s32 	%r198, %r169, %r170;
	add.s32 	%r199, %r199, 1;

BB0_40:
	mov.u32 	%r171, 126;
	sub.s32 	%r172, %r171, %r199;
	shl.b32 	%r173, %r172, 23;
	add.s32 	%r174, %r198, 1;
	shr.u32 	%r175, %r174, 7;
	add.s32 	%r176, %r175, 1;
	shr.u32 	%r177, %r176, 1;
	add.s32 	%r178, %r177, %r173;
	or.b32  	%r179, %r178, %r196;
	mov.b32 	 %f138, %r179;

BB0_41:
	mul.rn.f32 	%f33, %f138, %f138;
	and.b32  	%r75, %r200, 1;
	setp.eq.s32	%p32, %r75, 0;
	@%p32 bra 	BB0_43;

	mov.f32 	%f99, 0fBAB6061A;
	mov.f32 	%f100, 0f37CCF5CE;
	fma.rn.f32 	%f139, %f100, %f33, %f99;
	bra.uni 	BB0_44;

BB0_43:
	mov.f32 	%f101, 0f3C08839E;
	mov.f32 	%f102, 0fB94CA1F9;
	fma.rn.f32 	%f139, %f102, %f33, %f101;

BB0_44:
	@%p32 bra 	BB0_46;

	mov.f32 	%f103, 0f3D2AAAA5;
	fma.rn.f32 	%f104, %f139, %f33, %f103;
	mov.f32 	%f105, 0fBF000000;
	fma.rn.f32 	%f140, %f104, %f33, %f105;
	bra.uni 	BB0_47;

BB0_46:
	mov.f32 	%f106, 0fBE2AAAA3;
	fma.rn.f32 	%f107, %f139, %f33, %f106;
	mov.f32 	%f108, 0f00000000;
	fma.rn.f32 	%f140, %f107, %f33, %f108;

BB0_47:
	fma.rn.f32 	%f141, %f140, %f138, %f138;
	@%p32 bra 	BB0_49;

	mov.f32 	%f109, 0f3F800000;
	fma.rn.f32 	%f141, %f140, %f33, %f109;

BB0_49:
	and.b32  	%r180, %r200, 2;
	setp.eq.s32	%p35, %r180, 0;
	@%p35 bra 	BB0_51;

	mov.f32 	%f110, 0f00000000;
	mov.f32 	%f111, 0fBF800000;
	fma.rn.f32 	%f141, %f141, %f111, %f110;

BB0_51:
	cvta.to.global.u64 	%rd32, %rd15;
	cvta.to.global.u64 	%rd33, %rd14;
	cvta.to.global.u64 	%rd34, %rd13;
	cvta.to.global.u64 	%rd35, %rd20;
	cvta.to.global.u64 	%rd36, %rd19;
	cvta.to.global.u64 	%rd37, %rd18;
	mul.f32 	%f112, %f49, %f52;
	sub.f32 	%f113, %f48, %f112;
	mul.f32 	%f114, %f113, %f141;
	mul.f32 	%f115, %f49, %f51;
	sub.f32 	%f116, %f47, %f115;
	mul.f32 	%f117, %f116, %f135;
	sub.f32 	%f118, %f117, %f114;
	mul.f32 	%f119, %f13, %f118;
	mul.wide.s32 	%rd38, %r4, 4;
	add.s64 	%rd39, %rd37, %rd38;
	ld.global.nc.f32 	%f120, [%rd39];
	add.s64 	%rd40, %rd36, %rd38;
	ld.global.nc.f32 	%f121, [%rd40];
	add.s64 	%rd41, %rd35, %rd38;
	ld.global.nc.f32 	%f122, [%rd41];
	add.s64 	%rd42, %rd34, %rd38;
	ld.global.f32 	%f123, [%rd42];
	fma.rn.f32 	%f124, %f120, %f119, %f123;
	st.global.f32 	[%rd42], %f124;
	add.s64 	%rd43, %rd33, %rd38;
	ld.global.f32 	%f125, [%rd43];
	fma.rn.f32 	%f126, %f121, %f119, %f125;
	st.global.f32 	[%rd43], %f126;
	add.s64 	%rd44, %rd32, %rd38;
	ld.global.f32 	%f127, [%rd44];
	fma.rn.f32 	%f128, %f122, %f119, %f127;
	st.global.f32 	[%rd44], %f128;

BB0_52:
	ret;
}


`
   addcavity_ptx_61 = `
.version 6.4
.target sm_61
.address_size 64

	// .globl	addcavity
.const .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry addcavity(
	.param .u64 addcavity_param_0,
	.param .u64 addcavity_param_1,
	.param .u64 addcavity_param_2,
	.param .u64 addcavity_param_3,
	.param .f32 addcavity_param_4,
	.param .u64 addcavity_param_5,
	.param .f32 addcavity_param_6,
	.param .u64 addcavity_param_7,
	.param .u64 addcavity_param_8,
	.param .u64 addcavity_param_9,
	.param .f32 addcavity_param_10,
	.param .f32 addcavity_param_11,
	.param .f32 addcavity_param_12,
	.param .f32 addcavity_param_13,
	.param .f32 addcavity_param_14,
	.param .f32 addcavity_param_15,
	.param .u32 addcavity_param_16,
	.param .u32 addcavity_param_17,
	.param .u32 addcavity_param_18,
	.param .u8 addcavity_param_19
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<36>;
	.reg .f32 	%f<143>;
	.reg .b32 	%r<201>;
	.reg .b64 	%rd<49>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd13, [addcavity_param_0];
	ld.param.u64 	%rd14, [addcavity_param_1];
	ld.param.u64 	%rd15, [addcavity_param_2];
	ld.param.u64 	%rd16, [addcavity_param_3];
	ld.param.f32 	%f129, [addcavity_param_4];
	ld.param.u64 	%rd17, [addcavity_param_5];
	ld.param.f32 	%f130, [addcavity_param_6];
	ld.param.u64 	%rd18, [addcavity_param_7];
	ld.param.u64 	%rd19, [addcavity_param_8];
	ld.param.u64 	%rd20, [addcavity_param_9];
	ld.param.f32 	%f47, [addcavity_param_10];
	ld.param.f32 	%f48, [addcavity_param_11];
	ld.param.f32 	%f49, [addcavity_param_12];
	ld.param.f32 	%f50, [addcavity_param_13];
	ld.param.f32 	%f51, [addcavity_param_14];
	ld.param.f32 	%f52, [addcavity_param_15];
	ld.param.u32 	%r76, [addcavity_param_16];
	ld.param.u32 	%r77, [addcavity_param_17];
	ld.param.u32 	%r78, [addcavity_param_18];
	mov.u32 	%r79, %ntid.x;
	mov.u32 	%r80, %ctaid.x;
	mov.u32 	%r81, %tid.x;
	mad.lo.s32 	%r1, %r79, %r80, %r81;
	mov.u32 	%r82, %ntid.y;
	mov.u32 	%r83, %ctaid.y;
	mov.u32 	%r84, %tid.y;
	mad.lo.s32 	%r2, %r82, %r83, %r84;
	mov.u32 	%r85, %ntid.z;
	mov.u32 	%r86, %ctaid.z;
	mov.u32 	%r87, %tid.z;
	mad.lo.s32 	%r3, %r85, %r86, %r87;
	setp.ge.s32	%p1, %r2, %r77;
	setp.ge.s32	%p2, %r1, %r76;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r78;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_52;

	mad.lo.s32 	%r88, %r3, %r77, %r2;
	mad.lo.s32 	%r4, %r88, %r76, %r1;
	setp.eq.s64	%p6, %rd16, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd21, %rd16;
	mul.wide.s32 	%rd22, %r4, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.nc.f32 	%f53, [%rd23];
	mul.f32 	%f129, %f53, %f129;

BB0_3:
	setp.eq.s64	%p7, %rd17, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd24, %rd17;
	mul.wide.s32 	%rd25, %r4, 4;
	add.s64 	%rd26, %rd24, %rd25;
	ld.global.nc.f32 	%f54, [%rd26];
	mul.f32 	%f130, %f54, %f130;

BB0_5:
	mul.f32 	%f5, %f130, %f50;
	neg.f32 	%f55, %f5;
	mul.f32 	%f56, %f5, 0fBFB8AA3B;
	cvt.rzi.f32.f32	%f57, %f56;
	mov.f32 	%f58, 0fBF317200;
	fma.rn.f32 	%f59, %f57, %f58, %f55;
	mov.f32 	%f60, 0fB5BFBE8E;
	fma.rn.f32 	%f61, %f57, %f60, %f59;
	mul.f32 	%f62, %f61, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f6, %f62;
	add.f32 	%f63, %f57, 0f00000000;
	ex2.approx.f32 	%f7, %f63;
	add.u64 	%rd1, %SPL, 0;
	mul.f32 	%f137, %f129, %f50;
	abs.f32 	%f9, %f137;
	setp.neu.f32	%p8, %f9, 0f7F800000;
	mov.f32 	%f131, %f137;
	@%p8 bra 	BB0_7;

	mov.f32 	%f64, 0f00000000;
	mul.rn.f32 	%f131, %f137, %f64;

BB0_7:
	mul.f32 	%f65, %f131, 0f3F22F983;
	cvt.rni.s32.f32	%r190, %f65;
	cvt.rn.f32.s32	%f66, %r190;
	neg.f32 	%f67, %f66;
	mov.f32 	%f68, 0f3FC90FDA;
	fma.rn.f32 	%f69, %f67, %f68, %f131;
	mov.f32 	%f70, 0f33A22168;
	fma.rn.f32 	%f71, %f67, %f70, %f69;
	mov.f32 	%f72, 0f27C234C5;
	fma.rn.f32 	%f132, %f67, %f72, %f71;
	abs.f32 	%f73, %f131;
	add.s64 	%rd2, %rd1, 24;
	setp.lt.f32	%p9, %f5, 0fC2D20000;
	setp.gt.f32	%p10, %f5, 0f42D20000;
	mul.f32 	%f74, %f6, %f7;
	selp.f32	%f75, 0f00000000, %f74, %p10;
	selp.f32	%f13, 0f7F800000, %f75, %p9;
	setp.leu.f32	%p11, %f73, 0f47CE4780;
	@%p11 bra 	BB0_18;

	mov.b32 	 %r6, %f131;
	shr.u32 	%r7, %r6, 23;
	shl.b32 	%r91, %r6, 8;
	or.b32  	%r8, %r91, -2147483648;
	mov.u32 	%r182, 0;
	mov.u64 	%rd45, __cudart_i2opi_f;
	mov.u32 	%r181, -6;
	mov.u64 	%rd46, %rd1;

BB0_9:
	.pragma "nounroll";
	ld.const.u32 	%r94, [%rd45];
	// inline asm
	{
	mad.lo.cc.u32   %r92, %r94, %r8, %r182;
	madc.hi.u32     %r182, %r94, %r8,  0;
	}
	// inline asm
	st.local.u32 	[%rd46], %r92;
	add.s64 	%rd46, %rd46, 4;
	add.s64 	%rd45, %rd45, 4;
	add.s32 	%r181, %r181, 1;
	setp.ne.s32	%p12, %r181, 0;
	@%p12 bra 	BB0_9;

	and.b32  	%r97, %r7, 255;
	add.s32 	%r98, %r97, -128;
	shr.u32 	%r99, %r98, 5;
	and.b32  	%r13, %r6, -2147483648;
	st.local.u32 	[%rd2], %r182;
	mov.u32 	%r100, 6;
	sub.s32 	%r101, %r100, %r99;
	mul.wide.s32 	%rd29, %r101, 4;
	add.s64 	%rd7, %rd1, %rd29;
	ld.local.u32 	%r183, [%rd7];
	ld.local.u32 	%r184, [%rd7+-4];
	and.b32  	%r16, %r7, 31;
	setp.eq.s32	%p13, %r16, 0;
	@%p13 bra 	BB0_12;

	mov.u32 	%r102, 32;
	sub.s32 	%r103, %r102, %r16;
	shr.u32 	%r104, %r184, %r103;
	shl.b32 	%r105, %r183, %r16;
	add.s32 	%r183, %r104, %r105;
	ld.local.u32 	%r106, [%rd7+-8];
	shr.u32 	%r107, %r106, %r103;
	shl.b32 	%r108, %r184, %r16;
	add.s32 	%r184, %r107, %r108;

BB0_12:
	shr.u32 	%r109, %r184, 30;
	shl.b32 	%r110, %r183, 2;
	add.s32 	%r185, %r109, %r110;
	shl.b32 	%r22, %r184, 2;
	shr.u32 	%r111, %r185, 31;
	shr.u32 	%r112, %r183, 30;
	add.s32 	%r23, %r111, %r112;
	setp.eq.s32	%p14, %r111, 0;
	@%p14 bra 	BB0_13;

	not.b32 	%r113, %r185;
	neg.s32 	%r187, %r22;
	setp.eq.s32	%p15, %r22, 0;
	selp.u32	%r114, 1, 0, %p15;
	add.s32 	%r185, %r114, %r113;
	xor.b32  	%r186, %r13, -2147483648;
	bra.uni 	BB0_15;

BB0_13:
	mov.u32 	%r186, %r13;
	mov.u32 	%r187, %r22;

BB0_15:
	clz.b32 	%r189, %r185;
	setp.eq.s32	%p16, %r189, 0;
	shl.b32 	%r115, %r185, %r189;
	mov.u32 	%r116, 32;
	sub.s32 	%r117, %r116, %r189;
	shr.u32 	%r118, %r187, %r117;
	add.s32 	%r119, %r118, %r115;
	selp.b32	%r31, %r185, %r119, %p16;
	mov.u32 	%r120, -921707870;
	mul.hi.u32 	%r188, %r31, %r120;
	setp.eq.s32	%p17, %r13, 0;
	neg.s32 	%r121, %r23;
	selp.b32	%r190, %r23, %r121, %p17;
	setp.lt.s32	%p18, %r188, 1;
	@%p18 bra 	BB0_17;

	mul.lo.s32 	%r122, %r31, -921707870;
	shr.u32 	%r123, %r122, 31;
	shl.b32 	%r124, %r188, 1;
	add.s32 	%r188, %r123, %r124;
	add.s32 	%r189, %r189, 1;

BB0_17:
	mov.u32 	%r125, 126;
	sub.s32 	%r126, %r125, %r189;
	shl.b32 	%r127, %r126, 23;
	add.s32 	%r128, %r188, 1;
	shr.u32 	%r129, %r128, 7;
	add.s32 	%r130, %r129, 1;
	shr.u32 	%r131, %r130, 1;
	add.s32 	%r132, %r131, %r127;
	or.b32  	%r133, %r132, %r186;
	mov.b32 	 %f132, %r133;

BB0_18:
	mul.rn.f32 	%f16, %f132, %f132;
	add.s32 	%r39, %r190, 1;
	and.b32  	%r40, %r39, 1;
	setp.eq.s32	%p19, %r40, 0;
	@%p19 bra 	BB0_20;

	mov.f32 	%f76, 0fBAB6061A;
	mov.f32 	%f77, 0f37CCF5CE;
	fma.rn.f32 	%f133, %f77, %f16, %f76;
	bra.uni 	BB0_21;

BB0_20:
	mov.f32 	%f78, 0f3C08839E;
	mov.f32 	%f79, 0fB94CA1F9;
	fma.rn.f32 	%f133, %f79, %f16, %f78;

BB0_21:
	@%p19 bra 	BB0_23;

	mov.f32 	%f80, 0f3D2AAAA5;
	fma.rn.f32 	%f81, %f133, %f16, %f80;
	mov.f32 	%f82, 0fBF000000;
	fma.rn.f32 	%f134, %f81, %f16, %f82;
	bra.uni 	BB0_24;

BB0_23:
	mov.f32 	%f83, 0fBE2AAAA3;
	fma.rn.f32 	%f84, %f133, %f16, %f83;
	mov.f32 	%f85, 0f00000000;
	fma.rn.f32 	%f134, %f84, %f16, %f85;

BB0_24:
	fma.rn.f32 	%f135, %f134, %f132, %f132;
	@%p19 bra 	BB0_26;

	mov.f32 	%f86, 0f3F800000;
	fma.rn.f32 	%f135, %f134, %f16, %f86;

BB0_26:
	and.b32  	%r134, %r39, 2;
	setp.eq.s32	%p22, %r134, 0;
	@%p22 bra 	BB0_28;

	mov.f32 	%f87, 0f00000000;
	mov.f32 	%f88, 0fBF800000;
	fma.rn.f32 	%f135, %f135, %f88, %f87;

BB0_28:
	@%p8 bra 	BB0_30;

	mov.f32 	%f89, 0f00000000;
	mul.rn.f32 	%f137, %f137, %f89;

BB0_30:
	mul.f32 	%f90, %f137, 0f3F22F983;
	cvt.rni.s32.f32	%r200, %f90;
	cvt.rn.f32.s32	%f91, %r200;
	neg.f32 	%f92, %f91;
	fma.rn.f32 	%f94, %f92, %f68, %f137;
	fma.rn.f32 	%f96, %f92, %f70, %f94;
	fma.rn.f32 	%f138, %f92, %f72, %f96;
	abs.f32 	%f98, %f137;
	setp.leu.f32	%p24, %f98, 0f47CE4780;
	@%p24 bra 	BB0_41;

	mov.b32 	 %r42, %f137;
	shr.u32 	%r43, %r42, 23;
	shl.b32 	%r137, %r42, 8;
	or.b32  	%r44, %r137, -2147483648;
	mov.u32 	%r192, 0;
	mov.u64 	%rd47, __cudart_i2opi_f;
	mov.u32 	%r191, -6;
	mov.u64 	%rd48, %rd1;

BB0_32:
	.pragma "nounroll";
	ld.const.u32 	%r140, [%rd47];
	// inline asm
	{
	mad.lo.cc.u32   %r138, %r140, %r44, %r192;
	madc.hi.u32     %r192, %r140, %r44,  0;
	}
	// inline asm
	st.local.u32 	[%rd48], %r138;
	add.s64 	%rd48, %rd48, 4;
	add.s64 	%rd47, %rd47, 4;
	add.s32 	%r191, %r191, 1;
	setp.ne.s32	%p25, %r191, 0;
	@%p25 bra 	BB0_32;

	and.b32  	%r143, %r43, 255;
	add.s32 	%r144, %r143, -128;
	shr.u32 	%r145, %r144, 5;
	and.b32  	%r49, %r42, -2147483648;
	st.local.u32 	[%rd2], %r192;
	mov.u32 	%r146, 6;
	sub.s32 	%r147, %r146, %r145;
	mul.wide.s32 	%rd31, %r147, 4;
	add.s64 	%rd12, %rd1, %rd31;
	ld.local.u32 	%r193, [%rd12];
	ld.local.u32 	%r194, [%rd12+-4];
	and.b32  	%r52, %r43, 31;
	setp.eq.s32	%p26, %r52, 0;
	@%p26 bra 	BB0_35;

	mov.u32 	%r148, 32;
	sub.s32 	%r149, %r148, %r52;
	shr.u32 	%r150, %r194, %r149;
	shl.b32 	%r151, %r193, %r52;
	add.s32 	%r193, %r150, %r151;
	ld.local.u32 	%r152, [%rd12+-8];
	shr.u32 	%r153, %r152, %r149;
	shl.b32 	%r154, %r194, %r52;
	add.s32 	%r194, %r153, %r154;

BB0_35:
	shr.u32 	%r155, %r194, 30;
	shl.b32 	%r156, %r193, 2;
	add.s32 	%r195, %r155, %r156;
	shl.b32 	%r58, %r194, 2;
	shr.u32 	%r157, %r195, 31;
	shr.u32 	%r158, %r193, 30;
	add.s32 	%r59, %r157, %r158;
	setp.eq.s32	%p27, %r157, 0;
	@%p27 bra 	BB0_36;

	not.b32 	%r159, %r195;
	neg.s32 	%r197, %r58;
	setp.eq.s32	%p28, %r58, 0;
	selp.u32	%r160, 1, 0, %p28;
	add.s32 	%r195, %r160, %r159;
	xor.b32  	%r196, %r49, -2147483648;
	bra.uni 	BB0_38;

BB0_36:
	mov.u32 	%r196, %r49;
	mov.u32 	%r197, %r58;

BB0_38:
	clz.b32 	%r199, %r195;
	setp.eq.s32	%p29, %r199, 0;
	shl.b32 	%r161, %r195, %r199;
	mov.u32 	%r162, 32;
	sub.s32 	%r163, %r162, %r199;
	shr.u32 	%r164, %r197, %r163;
	add.s32 	%r165, %r164, %r161;
	selp.b32	%r67, %r195, %r165, %p29;
	mov.u32 	%r166, -921707870;
	mul.hi.u32 	%r198, %r67, %r166;
	setp.eq.s32	%p30, %r49, 0;
	neg.s32 	%r167, %r59;
	selp.b32	%r200, %r59, %r167, %p30;
	setp.lt.s32	%p31, %r198, 1;
	@%p31 bra 	BB0_40;

	mul.lo.s32 	%r168, %r67, -921707870;
	shr.u32 	%r169, %r168, 31;
	shl.b32 	%r170, %r198, 1;
	add.s32 	%r198, %r169, %r170;
	add.s32 	%r199, %r199, 1;

BB0_40:
	mov.u32 	%r171, 126;
	sub.s32 	%r172, %r171, %r199;
	shl.b32 	%r173, %r172, 23;
	add.s32 	%r174, %r198, 1;
	shr.u32 	%r175, %r174, 7;
	add.s32 	%r176, %r175, 1;
	shr.u32 	%r177, %r176, 1;
	add.s32 	%r178, %r177, %r173;
	or.b32  	%r179, %r178, %r196;
	mov.b32 	 %f138, %r179;

BB0_41:
	mul.rn.f32 	%f33, %f138, %f138;
	and.b32  	%r75, %r200, 1;
	setp.eq.s32	%p32, %r75, 0;
	@%p32 bra 	BB0_43;

	mov.f32 	%f99, 0fBAB6061A;
	mov.f32 	%f100, 0f37CCF5CE;
	fma.rn.f32 	%f139, %f100, %f33, %f99;
	bra.uni 	BB0_44;

BB0_43:
	mov.f32 	%f101, 0f3C08839E;
	mov.f32 	%f102, 0fB94CA1F9;
	fma.rn.f32 	%f139, %f102, %f33, %f101;

BB0_44:
	@%p32 bra 	BB0_46;

	mov.f32 	%f103, 0f3D2AAAA5;
	fma.rn.f32 	%f104, %f139, %f33, %f103;
	mov.f32 	%f105, 0fBF000000;
	fma.rn.f32 	%f140, %f104, %f33, %f105;
	bra.uni 	BB0_47;

BB0_46:
	mov.f32 	%f106, 0fBE2AAAA3;
	fma.rn.f32 	%f107, %f139, %f33, %f106;
	mov.f32 	%f108, 0f00000000;
	fma.rn.f32 	%f140, %f107, %f33, %f108;

BB0_47:
	fma.rn.f32 	%f141, %f140, %f138, %f138;
	@%p32 bra 	BB0_49;

	mov.f32 	%f109, 0f3F800000;
	fma.rn.f32 	%f141, %f140, %f33, %f109;

BB0_49:
	and.b32  	%r180, %r200, 2;
	setp.eq.s32	%p35, %r180, 0;
	@%p35 bra 	BB0_51;

	mov.f32 	%f110, 0f00000000;
	mov.f32 	%f111, 0fBF800000;
	fma.rn.f32 	%f141, %f141, %f111, %f110;

BB0_51:
	cvta.to.global.u64 	%rd32, %rd15;
	cvta.to.global.u64 	%rd33, %rd14;
	cvta.to.global.u64 	%rd34, %rd13;
	cvta.to.global.u64 	%rd35, %rd20;
	cvta.to.global.u64 	%rd36, %rd19;
	cvta.to.global.u64 	%rd37, %rd18;
	mul.f32 	%f112, %f49, %f52;
	sub.f32 	%f113, %f48, %f112;
	mul.f32 	%f114, %f113, %f141;
	mul.f32 	%f115, %f49, %f51;
	sub.f32 	%f116, %f47, %f115;
	mul.f32 	%f117, %f116, %f135;
	sub.f32 	%f118, %f117, %f114;
	mul.f32 	%f119, %f13, %f118;
	mul.wide.s32 	%rd38, %r4, 4;
	add.s64 	%rd39, %rd37, %rd38;
	ld.global.nc.f32 	%f120, [%rd39];
	add.s64 	%rd40, %rd36, %rd38;
	ld.global.nc.f32 	%f121, [%rd40];
	add.s64 	%rd41, %rd35, %rd38;
	ld.global.nc.f32 	%f122, [%rd41];
	add.s64 	%rd42, %rd34, %rd38;
	ld.global.f32 	%f123, [%rd42];
	fma.rn.f32 	%f124, %f120, %f119, %f123;
	st.global.f32 	[%rd42], %f124;
	add.s64 	%rd43, %rd33, %rd38;
	ld.global.f32 	%f125, [%rd43];
	fma.rn.f32 	%f126, %f121, %f119, %f125;
	st.global.f32 	[%rd43], %f126;
	add.s64 	%rd44, %rd32, %rd38;
	ld.global.f32 	%f127, [%rd44];
	fma.rn.f32 	%f128, %f122, %f119, %f127;
	st.global.f32 	[%rd44], %f128;

BB0_52:
	ret;
}


`
   addcavity_ptx_70 = `
.version 6.4
.target sm_70
.address_size 64

	// .globl	addcavity
.const .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry addcavity(
	.param .u64 addcavity_param_0,
	.param .u64 addcavity_param_1,
	.param .u64 addcavity_param_2,
	.param .u64 addcavity_param_3,
	.param .f32 addcavity_param_4,
	.param .u64 addcavity_param_5,
	.param .f32 addcavity_param_6,
	.param .u64 addcavity_param_7,
	.param .u64 addcavity_param_8,
	.param .u64 addcavity_param_9,
	.param .f32 addcavity_param_10,
	.param .f32 addcavity_param_11,
	.param .f32 addcavity_param_12,
	.param .f32 addcavity_param_13,
	.param .f32 addcavity_param_14,
	.param .f32 addcavity_param_15,
	.param .u32 addcavity_param_16,
	.param .u32 addcavity_param_17,
	.param .u32 addcavity_param_18,
	.param .u8 addcavity_param_19
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<36>;
	.reg .f32 	%f<143>;
	.reg .b32 	%r<201>;
	.reg .b64 	%rd<49>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd13, [addcavity_param_0];
	ld.param.u64 	%rd14, [addcavity_param_1];
	ld.param.u64 	%rd15, [addcavity_param_2];
	ld.param.u64 	%rd16, [addcavity_param_3];
	ld.param.f32 	%f129, [addcavity_param_4];
	ld.param.u64 	%rd17, [addcavity_param_5];
	ld.param.f32 	%f130, [addcavity_param_6];
	ld.param.u64 	%rd18, [addcavity_param_7];
	ld.param.u64 	%rd19, [addcavity_param_8];
	ld.param.u64 	%rd20, [addcavity_param_9];
	ld.param.f32 	%f47, [addcavity_param_10];
	ld.param.f32 	%f48, [addcavity_param_11];
	ld.param.f32 	%f49, [addcavity_param_12];
	ld.param.f32 	%f50, [addcavity_param_13];
	ld.param.f32 	%f51, [addcavity_param_14];
	ld.param.f32 	%f52, [addcavity_param_15];
	ld.param.u32 	%r76, [addcavity_param_16];
	ld.param.u32 	%r77, [addcavity_param_17];
	ld.param.u32 	%r78, [addcavity_param_18];
	mov.u32 	%r79, %ntid.x;
	mov.u32 	%r80, %ctaid.x;
	mov.u32 	%r81, %tid.x;
	mad.lo.s32 	%r1, %r79, %r80, %r81;
	mov.u32 	%r82, %ntid.y;
	mov.u32 	%r83, %ctaid.y;
	mov.u32 	%r84, %tid.y;
	mad.lo.s32 	%r2, %r82, %r83, %r84;
	mov.u32 	%r85, %ntid.z;
	mov.u32 	%r86, %ctaid.z;
	mov.u32 	%r87, %tid.z;
	mad.lo.s32 	%r3, %r85, %r86, %r87;
	setp.ge.s32	%p1, %r2, %r77;
	setp.ge.s32	%p2, %r1, %r76;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r78;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_52;

	mad.lo.s32 	%r88, %r3, %r77, %r2;
	mad.lo.s32 	%r4, %r88, %r76, %r1;
	setp.eq.s64	%p6, %rd16, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd21, %rd16;
	mul.wide.s32 	%rd22, %r4, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.nc.f32 	%f53, [%rd23];
	mul.f32 	%f129, %f53, %f129;

BB0_3:
	setp.eq.s64	%p7, %rd17, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd24, %rd17;
	mul.wide.s32 	%rd25, %r4, 4;
	add.s64 	%rd26, %rd24, %rd25;
	ld.global.nc.f32 	%f54, [%rd26];
	mul.f32 	%f130, %f54, %f130;

BB0_5:
	mul.f32 	%f5, %f130, %f50;
	neg.f32 	%f55, %f5;
	mul.f32 	%f56, %f5, 0fBFB8AA3B;
	cvt.rzi.f32.f32	%f57, %f56;
	mov.f32 	%f58, 0fBF317200;
	fma.rn.f32 	%f59, %f57, %f58, %f55;
	mov.f32 	%f60, 0fB5BFBE8E;
	fma.rn.f32 	%f61, %f57, %f60, %f59;
	mul.f32 	%f62, %f61, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f6, %f62;
	add.f32 	%f63, %f57, 0f00000000;
	ex2.approx.f32 	%f7, %f63;
	add.u64 	%rd1, %SPL, 0;
	mul.f32 	%f137, %f129, %f50;
	abs.f32 	%f9, %f137;
	setp.neu.f32	%p8, %f9, 0f7F800000;
	mov.f32 	%f131, %f137;
	@%p8 bra 	BB0_7;

	mov.f32 	%f64, 0f00000000;
	mul.rn.f32 	%f131, %f137, %f64;

BB0_7:
	mul.f32 	%f65, %f131, 0f3F22F983;
	cvt.rni.s32.f32	%r190, %f65;
	cvt.rn.f32.s32	%f66, %r190;
	neg.f32 	%f67, %f66;
	mov.f32 	%f68, 0f3FC90FDA;
	fma.rn.f32 	%f69, %f67, %f68, %f131;
	mov.f32 	%f70, 0f33A22168;
	fma.rn.f32 	%f71, %f67, %f70, %f69;
	mov.f32 	%f72, 0f27C234C5;
	fma.rn.f32 	%f132, %f67, %f72, %f71;
	abs.f32 	%f73, %f131;
	add.s64 	%rd2, %rd1, 24;
	setp.lt.f32	%p9, %f5, 0fC2D20000;
	setp.gt.f32	%p10, %f5, 0f42D20000;
	mul.f32 	%f74, %f6, %f7;
	selp.f32	%f75, 0f00000000, %f74, %p10;
	selp.f32	%f13, 0f7F800000, %f75, %p9;
	setp.leu.f32	%p11, %f73, 0f47CE4780;
	@%p11 bra 	BB0_18;

	mov.b32 	 %r6, %f131;
	shr.u32 	%r7, %r6, 23;
	shl.b32 	%r91, %r6, 8;
	or.b32  	%r8, %r91, -2147483648;
	mov.u32 	%r182, 0;
	mov.u64 	%rd45, __cudart_i2opi_f;
	mov.u32 	%r181, -6;
	mov.u64 	%rd46, %rd1;

BB0_9:
	.pragma "nounroll";
	ld.const.u32 	%r94, [%rd45];
	// inline asm
	{
	mad.lo.cc.u32   %r92, %r94, %r8, %r182;
	madc.hi.u32     %r182, %r94, %r8,  0;
	}
	// inline asm
	st.local.u32 	[%rd46], %r92;
	add.s64 	%rd46, %rd46, 4;
	add.s64 	%rd45, %rd45, 4;
	add.s32 	%r181, %r181, 1;
	setp.ne.s32	%p12, %r181, 0;
	@%p12 bra 	BB0_9;

	and.b32  	%r97, %r7, 255;
	add.s32 	%r98, %r97, -128;
	shr.u32 	%r99, %r98, 5;
	and.b32  	%r13, %r6, -2147483648;
	st.local.u32 	[%rd2], %r182;
	mov.u32 	%r100, 6;
	sub.s32 	%r101, %r100, %r99;
	mul.wide.s32 	%rd29, %r101, 4;
	add.s64 	%rd7, %rd1, %rd29;
	ld.local.u32 	%r183, [%rd7];
	ld.local.u32 	%r184, [%rd7+-4];
	and.b32  	%r16, %r7, 31;
	setp.eq.s32	%p13, %r16, 0;
	@%p13 bra 	BB0_12;

	mov.u32 	%r102, 32;
	sub.s32 	%r103, %r102, %r16;
	shr.u32 	%r104, %r184, %r103;
	shl.b32 	%r105, %r183, %r16;
	add.s32 	%r183, %r104, %r105;
	ld.local.u32 	%r106, [%rd7+-8];
	shr.u32 	%r107, %r106, %r103;
	shl.b32 	%r108, %r184, %r16;
	add.s32 	%r184, %r107, %r108;

BB0_12:
	shr.u32 	%r109, %r184, 30;
	shl.b32 	%r110, %r183, 2;
	add.s32 	%r185, %r109, %r110;
	shl.b32 	%r22, %r184, 2;
	shr.u32 	%r111, %r185, 31;
	shr.u32 	%r112, %r183, 30;
	add.s32 	%r23, %r111, %r112;
	setp.eq.s32	%p14, %r111, 0;
	@%p14 bra 	BB0_13;

	not.b32 	%r113, %r185;
	neg.s32 	%r187, %r22;
	setp.eq.s32	%p15, %r22, 0;
	selp.u32	%r114, 1, 0, %p15;
	add.s32 	%r185, %r114, %r113;
	xor.b32  	%r186, %r13, -2147483648;
	bra.uni 	BB0_15;

BB0_13:
	mov.u32 	%r186, %r13;
	mov.u32 	%r187, %r22;

BB0_15:
	clz.b32 	%r189, %r185;
	setp.eq.s32	%p16, %r189, 0;
	shl.b32 	%r115, %r185, %r189;
	mov.u32 	%r116, 32;
	sub.s32 	%r117, %r116, %r189;
	shr.u32 	%r118, %r187, %r117;
	add.s32 	%r119, %r118, %r115;
	selp.b32	%r31, %r185, %r119, %p16;
	mov.u32 	%r120, -921707870;
	mul.hi.u32 	%r188, %r31, %r120;
	setp.eq.s32	%p17, %r13, 0;
	neg.s32 	%r121, %r23;
	selp.b32	%r190, %r23, %r121, %p17;
	setp.lt.s32	%p18, %r188, 1;
	@%p18 bra 	BB0_17;

	mul.lo.s32 	%r122, %r31, -921707870;
	shr.u32 	%r123, %r122, 31;
	shl.b32 	%r124, %r188, 1;
	add.s32 	%r188, %r123, %r124;
	add.s32 	%r189, %r189, 1;

BB0_17:
	mov.u32 	%r125, 126;
	sub.s32 	%r126, %r125, %r189;
	shl.b32 	%r127, %r126, 23;
	add.s32 	%r128, %r188, 1;
	shr.u32 	%r129, %r128, 7;
	add.s32 	%r130, %r129, 1;
	shr.u32 	%r131, %r130, 1;
	add.s32 	%r132, %r131, %r127;
	or.b32  	%r133, %r132, %r186;
	mov.b32 	 %f132, %r133;

BB0_18:
	mul.rn.f32 	%f16, %f132, %f132;
	add.s32 	%r39, %r190, 1;
	and.b32  	%r40, %r39, 1;
	setp.eq.s32	%p19, %r40, 0;
	@%p19 bra 	BB0_20;

	mov.f32 	%f76, 0fBAB6061A;
	mov.f32 	%f77, 0f37CCF5CE;
	fma.rn.f32 	%f133, %f77, %f16, %f76;
	bra.uni 	BB0_21;

BB0_20:
	mov.f32 	%f78, 0f3C08839E;
	mov.f32 	%f79, 0fB94CA1F9;
	fma.rn.f32 	%f133, %f79, %f16, %f78;

BB0_21:
	@%p19 bra 	BB0_23;

	mov.f32 	%f80, 0f3D2AAAA5;
	fma.rn.f32 	%f81, %f133, %f16, %f80;
	mov.f32 	%f82, 0fBF000000;
	fma.rn.f32 	%f134, %f81, %f16, %f82;
	bra.uni 	BB0_24;

BB0_23:
	mov.f32 	%f83, 0fBE2AAAA3;
	fma.rn.f32 	%f84, %f133, %f16, %f83;
	mov.f32 	%f85, 0f00000000;
	fma.rn.f32 	%f134, %f84, %f16, %f85;

BB0_24:
	fma.rn.f32 	%f135, %f134, %f132, %f132;
	@%p19 bra 	BB0_26;

	mov.f32 	%f86, 0f3F800000;
	fma.rn.f32 	%f135, %f134, %f16, %f86;

BB0_26:
	and.b32  	%r134, %r39, 2;
	setp.eq.s32	%p22, %r134, 0;
	@%p22 bra 	BB0_28;

	mov.f32 	%f87, 0f00000000;
	mov.f32 	%f88, 0fBF800000;
	fma.rn.f32 	%f135, %f135, %f88, %f87;

BB0_28:
	@%p8 bra 	BB0_30;

	mov.f32 	%f89, 0f00000000;
	mul.rn.f32 	%f137, %f137, %f89;

BB0_30:
	mul.f32 	%f90, %f137, 0f3F22F983;
	cvt.rni.s32.f32	%r200, %f90;
	cvt.rn.f32.s32	%f91, %r200;
	neg.f32 	%f92, %f91;
	fma.rn.f32 	%f94, %f92, %f68, %f137;
	fma.rn.f32 	%f96, %f92, %f70, %f94;
	fma.rn.f32 	%f138, %f92, %f72, %f96;
	abs.f32 	%f98, %f137;
	setp.leu.f32	%p24, %f98, 0f47CE4780;
	@%p24 bra 	BB0_41;

	mov.b32 	 %r42, %f137;
	shr.u32 	%r43, %r42, 23;
	shl.b32 	%r137, %r42, 8;
	or.b32  	%r44, %r137, -2147483648;
	mov.u32 	%r192, 0;
	mov.u64 	%rd47, __cudart_i2opi_f;
	mov.u32 	%r191, -6;
	mov.u64 	%rd48, %rd1;

BB0_32:
	.pragma "nounroll";
	ld.const.u32 	%r140, [%rd47];
	// inline asm
	{
	mad.lo.cc.u32   %r138, %r140, %r44, %r192;
	madc.hi.u32     %r192, %r140, %r44,  0;
	}
	// inline asm
	st.local.u32 	[%rd48], %r138;
	add.s64 	%rd48, %rd48, 4;
	add.s64 	%rd47, %rd47, 4;
	add.s32 	%r191, %r191, 1;
	setp.ne.s32	%p25, %r191, 0;
	@%p25 bra 	BB0_32;

	and.b32  	%r143, %r43, 255;
	add.s32 	%r144, %r143, -128;
	shr.u32 	%r145, %r144, 5;
	and.b32  	%r49, %r42, -2147483648;
	st.local.u32 	[%rd2], %r192;
	mov.u32 	%r146, 6;
	sub.s32 	%r147, %r146, %r145;
	mul.wide.s32 	%rd31, %r147, 4;
	add.s64 	%rd12, %rd1, %rd31;
	ld.local.u32 	%r193, [%rd12];
	ld.local.u32 	%r194, [%rd12+-4];
	and.b32  	%r52, %r43, 31;
	setp.eq.s32	%p26, %r52, 0;
	@%p26 bra 	BB0_35;

	mov.u32 	%r148, 32;
	sub.s32 	%r149, %r148, %r52;
	shr.u32 	%r150, %r194, %r149;
	shl.b32 	%r151, %r193, %r52;
	add.s32 	%r193, %r150, %r151;
	ld.local.u32 	%r152, [%rd12+-8];
	shr.u32 	%r153, %r152, %r149;
	shl.b32 	%r154, %r194, %r52;
	add.s32 	%r194, %r153, %r154;

BB0_35:
	shr.u32 	%r155, %r194, 30;
	shl.b32 	%r156, %r193, 2;
	add.s32 	%r195, %r155, %r156;
	shl.b32 	%r58, %r194, 2;
	shr.u32 	%r157, %r195, 31;
	shr.u32 	%r158, %r193, 30;
	add.s32 	%r59, %r157, %r158;
	setp.eq.s32	%p27, %r157, 0;
	@%p27 bra 	BB0_36;

	not.b32 	%r159, %r195;
	neg.s32 	%r197, %r58;
	setp.eq.s32	%p28, %r58, 0;
	selp.u32	%r160, 1, 0, %p28;
	add.s32 	%r195, %r160, %r159;
	xor.b32  	%r196, %r49, -2147483648;
	bra.uni 	BB0_38;

BB0_36:
	mov.u32 	%r196, %r49;
	mov.u32 	%r197, %r58;

BB0_38:
	clz.b32 	%r199, %r195;
	setp.eq.s32	%p29, %r199, 0;
	shl.b32 	%r161, %r195, %r199;
	mov.u32 	%r162, 32;
	sub.s32 	%r163, %r162, %r199;
	shr.u32 	%r164, %r197, %r163;
	add.s32 	%r165, %r164, %r161;
	selp.b32	%r67, %r195, %r165, %p29;
	mov.u32 	%r166, -921707870;
	mul.hi.u32 	%r198, %r67, %r166;
	setp.eq.s32	%p30, %r49, 0;
	neg.s32 	%r167, %r59;
	selp.b32	%r200, %r59, %r167, %p30;
	setp.lt.s32	%p31, %r198, 1;
	@%p31 bra 	BB0_40;

	mul.lo.s32 	%r168, %r67, -921707870;
	shr.u32 	%r169, %r168, 31;
	shl.b32 	%r170, %r198, 1;
	add.s32 	%r198, %r169, %r170;
	add.s32 	%r199, %r199, 1;

BB0_40:
	mov.u32 	%r171, 126;
	sub.s32 	%r172, %r171, %r199;
	shl.b32 	%r173, %r172, 23;
	add.s32 	%r174, %r198, 1;
	shr.u32 	%r175, %r174, 7;
	add.s32 	%r176, %r175, 1;
	shr.u32 	%r177, %r176, 1;
	add.s32 	%r178, %r177, %r173;
	or.b32  	%r179, %r178, %r196;
	mov.b32 	 %f138, %r179;

BB0_41:
	mul.rn.f32 	%f33, %f138, %f138;
	and.b32  	%r75, %r200, 1;
	setp.eq.s32	%p32, %r75, 0;
	@%p32 bra 	BB0_43;

	mov.f32 	%f99, 0fBAB6061A;
	mov.f32 	%f100, 0f37CCF5CE;
	fma.rn.f32 	%f139, %f100, %f33, %f99;
	bra.uni 	BB0_44;

BB0_43:
	mov.f32 	%f101, 0f3C08839E;
	mov.f32 	%f102, 0fB94CA1F9;
	fma.rn.f32 	%f139, %f102, %f33, %f101;

BB0_44:
	@%p32 bra 	BB0_46;

	mov.f32 	%f103, 0f3D2AAAA5;
	fma.rn.f32 	%f104, %f139, %f33, %f103;
	mov.f32 	%f105, 0fBF000000;
	fma.rn.f32 	%f140, %f104, %f33, %f105;
	bra.uni 	BB0_47;

BB0_46:
	mov.f32 	%f106, 0fBE2AAAA3;
	fma.rn.f32 	%f107, %f139, %f33, %f106;
	mov.f32 	%f108, 0f00000000;
	fma.rn.f32 	%f140, %f107, %f33, %f108;

BB0_47:
	fma.rn.f32 	%f141, %f140, %f138, %f138;
	@%p32 bra 	BB0_49;

	mov.f32 	%f109, 0f3F800000;
	fma.rn.f32 	%f141, %f140, %f33, %f109;

BB0_49:
	and.b32  	%r180, %r200, 2;
	setp.eq.s32	%p35, %r180, 0;
	@%p35 bra 	BB0_51;

	mov.f32 	%f110, 0f00000000;
	mov.f32 	%f111, 0fBF800000;
	fma.rn.f32 	%f141, %f141, %f111, %f110;

BB0_51:
	cvta.to.global.u64 	%rd32, %rd15;
	cvta.to.global.u64 	%rd33, %rd14;
	cvta.to.global.u64 	%rd34, %rd13;
	cvta.to.global.u64 	%rd35, %rd20;
	cvta.to.global.u64 	%rd36, %rd19;
	cvta.to.global.u64 	%rd37, %rd18;
	mul.f32 	%f112, %f49, %f52;
	sub.f32 	%f113, %f48, %f112;
	mul.f32 	%f114, %f113, %f141;
	mul.f32 	%f115, %f49, %f51;
	sub.f32 	%f116, %f47, %f115;
	mul.f32 	%f117, %f116, %f135;
	sub.f32 	%f118, %f117, %f114;
	mul.f32 	%f119, %f13, %f118;
	mul.wide.s32 	%rd38, %r4, 4;
	add.s64 	%rd39, %rd37, %rd38;
	ld.global.nc.f32 	%f120, [%rd39];
	add.s64 	%rd40, %rd36, %rd38;
	ld.global.nc.f32 	%f121, [%rd40];
	add.s64 	%rd41, %rd35, %rd38;
	ld.global.nc.f32 	%f122, [%rd41];
	add.s64 	%rd42, %rd34, %rd38;
	ld.global.f32 	%f123, [%rd42];
	fma.rn.f32 	%f124, %f120, %f119, %f123;
	st.global.f32 	[%rd42], %f124;
	add.s64 	%rd43, %rd33, %rd38;
	ld.global.f32 	%f125, [%rd43];
	fma.rn.f32 	%f126, %f121, %f119, %f125;
	st.global.f32 	[%rd43], %f126;
	add.s64 	%rd44, %rd32, %rd38;
	ld.global.f32 	%f127, [%rd44];
	fma.rn.f32 	%f128, %f122, %f119, %f127;
	st.global.f32 	[%rd44], %f128;

BB0_52:
	ret;
}


`
   addcavity_ptx_75 = `
.version 6.4
.target sm_75
.address_size 64

	// .globl	addcavity
.const .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry addcavity(
	.param .u64 addcavity_param_0,
	.param .u64 addcavity_param_1,
	.param .u64 addcavity_param_2,
	.param .u64 addcavity_param_3,
	.param .f32 addcavity_param_4,
	.param .u64 addcavity_param_5,
	.param .f32 addcavity_param_6,
	.param .u64 addcavity_param_7,
	.param .u64 addcavity_param_8,
	.param .u64 addcavity_param_9,
	.param .f32 addcavity_param_10,
	.param .f32 addcavity_param_11,
	.param .f32 addcavity_param_12,
	.param .f32 addcavity_param_13,
	.param .f32 addcavity_param_14,
	.param .f32 addcavity_param_15,
	.param .u32 addcavity_param_16,
	.param .u32 addcavity_param_17,
	.param .u32 addcavity_param_18,
	.param .u8 addcavity_param_19
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<36>;
	.reg .f32 	%f<143>;
	.reg .b32 	%r<201>;
	.reg .b64 	%rd<49>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd13, [addcavity_param_0];
	ld.param.u64 	%rd14, [addcavity_param_1];
	ld.param.u64 	%rd15, [addcavity_param_2];
	ld.param.u64 	%rd16, [addcavity_param_3];
	ld.param.f32 	%f129, [addcavity_param_4];
	ld.param.u64 	%rd17, [addcavity_param_5];
	ld.param.f32 	%f130, [addcavity_param_6];
	ld.param.u64 	%rd18, [addcavity_param_7];
	ld.param.u64 	%rd19, [addcavity_param_8];
	ld.param.u64 	%rd20, [addcavity_param_9];
	ld.param.f32 	%f47, [addcavity_param_10];
	ld.param.f32 	%f48, [addcavity_param_11];
	ld.param.f32 	%f49, [addcavity_param_12];
	ld.param.f32 	%f50, [addcavity_param_13];
	ld.param.f32 	%f51, [addcavity_param_14];
	ld.param.f32 	%f52, [addcavity_param_15];
	ld.param.u32 	%r76, [addcavity_param_16];
	ld.param.u32 	%r77, [addcavity_param_17];
	ld.param.u32 	%r78, [addcavity_param_18];
	mov.u32 	%r79, %ntid.x;
	mov.u32 	%r80, %ctaid.x;
	mov.u32 	%r81, %tid.x;
	mad.lo.s32 	%r1, %r79, %r80, %r81;
	mov.u32 	%r82, %ntid.y;
	mov.u32 	%r83, %ctaid.y;
	mov.u32 	%r84, %tid.y;
	mad.lo.s32 	%r2, %r82, %r83, %r84;
	mov.u32 	%r85, %ntid.z;
	mov.u32 	%r86, %ctaid.z;
	mov.u32 	%r87, %tid.z;
	mad.lo.s32 	%r3, %r85, %r86, %r87;
	setp.ge.s32	%p1, %r2, %r77;
	setp.ge.s32	%p2, %r1, %r76;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r78;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_52;

	mad.lo.s32 	%r88, %r3, %r77, %r2;
	mad.lo.s32 	%r4, %r88, %r76, %r1;
	setp.eq.s64	%p6, %rd16, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd21, %rd16;
	mul.wide.s32 	%rd22, %r4, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.nc.f32 	%f53, [%rd23];
	mul.f32 	%f129, %f53, %f129;

BB0_3:
	setp.eq.s64	%p7, %rd17, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd24, %rd17;
	mul.wide.s32 	%rd25, %r4, 4;
	add.s64 	%rd26, %rd24, %rd25;
	ld.global.nc.f32 	%f54, [%rd26];
	mul.f32 	%f130, %f54, %f130;

BB0_5:
	mul.f32 	%f5, %f130, %f50;
	neg.f32 	%f55, %f5;
	mul.f32 	%f56, %f5, 0fBFB8AA3B;
	cvt.rzi.f32.f32	%f57, %f56;
	mov.f32 	%f58, 0fBF317200;
	fma.rn.f32 	%f59, %f57, %f58, %f55;
	mov.f32 	%f60, 0fB5BFBE8E;
	fma.rn.f32 	%f61, %f57, %f60, %f59;
	mul.f32 	%f62, %f61, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f6, %f62;
	add.f32 	%f63, %f57, 0f00000000;
	ex2.approx.f32 	%f7, %f63;
	add.u64 	%rd1, %SPL, 0;
	mul.f32 	%f137, %f129, %f50;
	abs.f32 	%f9, %f137;
	setp.neu.f32	%p8, %f9, 0f7F800000;
	mov.f32 	%f131, %f137;
	@%p8 bra 	BB0_7;

	mov.f32 	%f64, 0f00000000;
	mul.rn.f32 	%f131, %f137, %f64;

BB0_7:
	mul.f32 	%f65, %f131, 0f3F22F983;
	cvt.rni.s32.f32	%r190, %f65;
	cvt.rn.f32.s32	%f66, %r190;
	neg.f32 	%f67, %f66;
	mov.f32 	%f68, 0f3FC90FDA;
	fma.rn.f32 	%f69, %f67, %f68, %f131;
	mov.f32 	%f70, 0f33A22168;
	fma.rn.f32 	%f71, %f67, %f70, %f69;
	mov.f32 	%f72, 0f27C234C5;
	fma.rn.f32 	%f132, %f67, %f72, %f71;
	abs.f32 	%f73, %f131;
	add.s64 	%rd2, %rd1, 24;
	setp.lt.f32	%p9, %f5, 0fC2D20000;
	setp.gt.f32	%p10, %f5, 0f42D20000;
	mul.f32 	%f74, %f6, %f7;
	selp.f32	%f75, 0f00000000, %f74, %p10;
	selp.f32	%f13, 0f7F800000, %f75, %p9;
	setp.leu.f32	%p11, %f73, 0f47CE4780;
	@%p11 bra 	BB0_18;

	mov.b32 	 %r6, %f131;
	shr.u32 	%r7, %r6, 23;
	shl.b32 	%r91, %r6, 8;
	or.b32  	%r8, %r91, -2147483648;
	mov.u32 	%r182, 0;
	mov.u64 	%rd45, __cudart_i2opi_f;
	mov.u32 	%r181, -6;
	mov.u64 	%rd46, %rd1;

BB0_9:
	.pragma "nounroll";
	ld.const.u32 	%r94, [%rd45];
	// inline asm
	{
	mad.lo.cc.u32   %r92, %r94, %r8, %r182;
	madc.hi.u32     %r182, %r94, %r8,  0;
	}
	// inline asm
	st.local.u32 	[%rd46], %r92;
	add.s64 	%rd46, %rd46, 4;
	add.s64 	%rd45, %rd45, 4;
	add.s32 	%r181, %r181, 1;
	setp.ne.s32	%p12, %r181, 0;
	@%p12 bra 	BB0_9;

	and.b32  	%r97, %r7, 255;
	add.s32 	%r98, %r97, -128;
	shr.u32 	%r99, %r98, 5;
	and.b32  	%r13, %r6, -2147483648;
	st.local.u32 	[%rd2], %r182;
	mov.u32 	%r100, 6;
	sub.s32 	%r101, %r100, %r99;
	mul.wide.s32 	%rd29, %r101, 4;
	add.s64 	%rd7, %rd1, %rd29;
	ld.local.u32 	%r183, [%rd7];
	ld.local.u32 	%r184, [%rd7+-4];
	and.b32  	%r16, %r7, 31;
	setp.eq.s32	%p13, %r16, 0;
	@%p13 bra 	BB0_12;

	mov.u32 	%r102, 32;
	sub.s32 	%r103, %r102, %r16;
	shr.u32 	%r104, %r184, %r103;
	shl.b32 	%r105, %r183, %r16;
	add.s32 	%r183, %r104, %r105;
	ld.local.u32 	%r106, [%rd7+-8];
	shr.u32 	%r107, %r106, %r103;
	shl.b32 	%r108, %r184, %r16;
	add.s32 	%r184, %r107, %r108;

BB0_12:
	shr.u32 	%r109, %r184, 30;
	shl.b32 	%r110, %r183, 2;
	add.s32 	%r185, %r109, %r110;
	shl.b32 	%r22, %r184, 2;
	shr.u32 	%r111, %r185, 31;
	shr.u32 	%r112, %r183, 30;
	add.s32 	%r23, %r111, %r112;
	setp.eq.s32	%p14, %r111, 0;
	@%p14 bra 	BB0_13;

	not.b32 	%r113, %r185;
	neg.s32 	%r187, %r22;
	setp.eq.s32	%p15, %r22, 0;
	selp.u32	%r114, 1, 0, %p15;
	add.s32 	%r185, %r114, %r113;
	xor.b32  	%r186, %r13, -2147483648;
	bra.uni 	BB0_15;

BB0_13:
	mov.u32 	%r186, %r13;
	mov.u32 	%r187, %r22;

BB0_15:
	clz.b32 	%r189, %r185;
	setp.eq.s32	%p16, %r189, 0;
	shl.b32 	%r115, %r185, %r189;
	mov.u32 	%r116, 32;
	sub.s32 	%r117, %r116, %r189;
	shr.u32 	%r118, %r187, %r117;
	add.s32 	%r119, %r118, %r115;
	selp.b32	%r31, %r185, %r119, %p16;
	mov.u32 	%r120, -921707870;
	mul.hi.u32 	%r188, %r31, %r120;
	setp.eq.s32	%p17, %r13, 0;
	neg.s32 	%r121, %r23;
	selp.b32	%r190, %r23, %r121, %p17;
	setp.lt.s32	%p18, %r188, 1;
	@%p18 bra 	BB0_17;

	mul.lo.s32 	%r122, %r31, -921707870;
	shr.u32 	%r123, %r122, 31;
	shl.b32 	%r124, %r188, 1;
	add.s32 	%r188, %r123, %r124;
	add.s32 	%r189, %r189, 1;

BB0_17:
	mov.u32 	%r125, 126;
	sub.s32 	%r126, %r125, %r189;
	shl.b32 	%r127, %r126, 23;
	add.s32 	%r128, %r188, 1;
	shr.u32 	%r129, %r128, 7;
	add.s32 	%r130, %r129, 1;
	shr.u32 	%r131, %r130, 1;
	add.s32 	%r132, %r131, %r127;
	or.b32  	%r133, %r132, %r186;
	mov.b32 	 %f132, %r133;

BB0_18:
	mul.rn.f32 	%f16, %f132, %f132;
	add.s32 	%r39, %r190, 1;
	and.b32  	%r40, %r39, 1;
	setp.eq.s32	%p19, %r40, 0;
	@%p19 bra 	BB0_20;

	mov.f32 	%f76, 0fBAB6061A;
	mov.f32 	%f77, 0f37CCF5CE;
	fma.rn.f32 	%f133, %f77, %f16, %f76;
	bra.uni 	BB0_21;

BB0_20:
	mov.f32 	%f78, 0f3C08839E;
	mov.f32 	%f79, 0fB94CA1F9;
	fma.rn.f32 	%f133, %f79, %f16, %f78;

BB0_21:
	@%p19 bra 	BB0_23;

	mov.f32 	%f80, 0f3D2AAAA5;
	fma.rn.f32 	%f81, %f133, %f16, %f80;
	mov.f32 	%f82, 0fBF000000;
	fma.rn.f32 	%f134, %f81, %f16, %f82;
	bra.uni 	BB0_24;

BB0_23:
	mov.f32 	%f83, 0fBE2AAAA3;
	fma.rn.f32 	%f84, %f133, %f16, %f83;
	mov.f32 	%f85, 0f00000000;
	fma.rn.f32 	%f134, %f84, %f16, %f85;

BB0_24:
	fma.rn.f32 	%f135, %f134, %f132, %f132;
	@%p19 bra 	BB0_26;

	mov.f32 	%f86, 0f3F800000;
	fma.rn.f32 	%f135, %f134, %f16, %f86;

BB0_26:
	and.b32  	%r134, %r39, 2;
	setp.eq.s32	%p22, %r134, 0;
	@%p22 bra 	BB0_28;

	mov.f32 	%f87, 0f00000000;
	mov.f32 	%f88, 0fBF800000;
	fma.rn.f32 	%f135, %f135, %f88, %f87;

BB0_28:
	@%p8 bra 	BB0_30;

	mov.f32 	%f89, 0f00000000;
	mul.rn.f32 	%f137, %f137, %f89;

BB0_30:
	mul.f32 	%f90, %f137, 0f3F22F983;
	cvt.rni.s32.f32	%r200, %f90;
	cvt.rn.f32.s32	%f91, %r200;
	neg.f32 	%f92, %f91;
	fma.rn.f32 	%f94, %f92, %f68, %f137;
	fma.rn.f32 	%f96, %f92, %f70, %f94;
	fma.rn.f32 	%f138, %f92, %f72, %f96;
	abs.f32 	%f98, %f137;
	setp.leu.f32	%p24, %f98, 0f47CE4780;
	@%p24 bra 	BB0_41;

	mov.b32 	 %r42, %f137;
	shr.u32 	%r43, %r42, 23;
	shl.b32 	%r137, %r42, 8;
	or.b32  	%r44, %r137, -2147483648;
	mov.u32 	%r192, 0;
	mov.u64 	%rd47, __cudart_i2opi_f;
	mov.u32 	%r191, -6;
	mov.u64 	%rd48, %rd1;

BB0_32:
	.pragma "nounroll";
	ld.const.u32 	%r140, [%rd47];
	// inline asm
	{
	mad.lo.cc.u32   %r138, %r140, %r44, %r192;
	madc.hi.u32     %r192, %r140, %r44,  0;
	}
	// inline asm
	st.local.u32 	[%rd48], %r138;
	add.s64 	%rd48, %rd48, 4;
	add.s64 	%rd47, %rd47, 4;
	add.s32 	%r191, %r191, 1;
	setp.ne.s32	%p25, %r191, 0;
	@%p25 bra 	BB0_32;

	and.b32  	%r143, %r43, 255;
	add.s32 	%r144, %r143, -128;
	shr.u32 	%r145, %r144, 5;
	and.b32  	%r49, %r42, -2147483648;
	st.local.u32 	[%rd2], %r192;
	mov.u32 	%r146, 6;
	sub.s32 	%r147, %r146, %r145;
	mul.wide.s32 	%rd31, %r147, 4;
	add.s64 	%rd12, %rd1, %rd31;
	ld.local.u32 	%r193, [%rd12];
	ld.local.u32 	%r194, [%rd12+-4];
	and.b32  	%r52, %r43, 31;
	setp.eq.s32	%p26, %r52, 0;
	@%p26 bra 	BB0_35;

	mov.u32 	%r148, 32;
	sub.s32 	%r149, %r148, %r52;
	shr.u32 	%r150, %r194, %r149;
	shl.b32 	%r151, %r193, %r52;
	add.s32 	%r193, %r150, %r151;
	ld.local.u32 	%r152, [%rd12+-8];
	shr.u32 	%r153, %r152, %r149;
	shl.b32 	%r154, %r194, %r52;
	add.s32 	%r194, %r153, %r154;

BB0_35:
	shr.u32 	%r155, %r194, 30;
	shl.b32 	%r156, %r193, 2;
	add.s32 	%r195, %r155, %r156;
	shl.b32 	%r58, %r194, 2;
	shr.u32 	%r157, %r195, 31;
	shr.u32 	%r158, %r193, 30;
	add.s32 	%r59, %r157, %r158;
	setp.eq.s32	%p27, %r157, 0;
	@%p27 bra 	BB0_36;

	not.b32 	%r159, %r195;
	neg.s32 	%r197, %r58;
	setp.eq.s32	%p28, %r58, 0;
	selp.u32	%r160, 1, 0, %p28;
	add.s32 	%r195, %r160, %r159;
	xor.b32  	%r196, %r49, -2147483648;
	bra.uni 	BB0_38;

BB0_36:
	mov.u32 	%r196, %r49;
	mov.u32 	%r197, %r58;

BB0_38:
	clz.b32 	%r199, %r195;
	setp.eq.s32	%p29, %r199, 0;
	shl.b32 	%r161, %r195, %r199;
	mov.u32 	%r162, 32;
	sub.s32 	%r163, %r162, %r199;
	shr.u32 	%r164, %r197, %r163;
	add.s32 	%r165, %r164, %r161;
	selp.b32	%r67, %r195, %r165, %p29;
	mov.u32 	%r166, -921707870;
	mul.hi.u32 	%r198, %r67, %r166;
	setp.eq.s32	%p30, %r49, 0;
	neg.s32 	%r167, %r59;
	selp.b32	%r200, %r59, %r167, %p30;
	setp.lt.s32	%p31, %r198, 1;
	@%p31 bra 	BB0_40;

	mul.lo.s32 	%r168, %r67, -921707870;
	shr.u32 	%r169, %r168, 31;
	shl.b32 	%r170, %r198, 1;
	add.s32 	%r198, %r169, %r170;
	add.s32 	%r199, %r199, 1;

BB0_40:
	mov.u32 	%r171, 126;
	sub.s32 	%r172, %r171, %r199;
	shl.b32 	%r173, %r172, 23;
	add.s32 	%r174, %r198, 1;
	shr.u32 	%r175, %r174, 7;
	add.s32 	%r176, %r175, 1;
	shr.u32 	%r177, %r176, 1;
	add.s32 	%r178, %r177, %r173;
	or.b32  	%r179, %r178, %r196;
	mov.b32 	 %f138, %r179;

BB0_41:
	mul.rn.f32 	%f33, %f138, %f138;
	and.b32  	%r75, %r200, 1;
	setp.eq.s32	%p32, %r75, 0;
	@%p32 bra 	BB0_43;

	mov.f32 	%f99, 0fBAB6061A;
	mov.f32 	%f100, 0f37CCF5CE;
	fma.rn.f32 	%f139, %f100, %f33, %f99;
	bra.uni 	BB0_44;

BB0_43:
	mov.f32 	%f101, 0f3C08839E;
	mov.f32 	%f102, 0fB94CA1F9;
	fma.rn.f32 	%f139, %f102, %f33, %f101;

BB0_44:
	@%p32 bra 	BB0_46;

	mov.f32 	%f103, 0f3D2AAAA5;
	fma.rn.f32 	%f104, %f139, %f33, %f103;
	mov.f32 	%f105, 0fBF000000;
	fma.rn.f32 	%f140, %f104, %f33, %f105;
	bra.uni 	BB0_47;

BB0_46:
	mov.f32 	%f106, 0fBE2AAAA3;
	fma.rn.f32 	%f107, %f139, %f33, %f106;
	mov.f32 	%f108, 0f00000000;
	fma.rn.f32 	%f140, %f107, %f33, %f108;

BB0_47:
	fma.rn.f32 	%f141, %f140, %f138, %f138;
	@%p32 bra 	BB0_49;

	mov.f32 	%f109, 0f3F800000;
	fma.rn.f32 	%f141, %f140, %f33, %f109;

BB0_49:
	and.b32  	%r180, %r200, 2;
	setp.eq.s32	%p35, %r180, 0;
	@%p35 bra 	BB0_51;

	mov.f32 	%f110, 0f00000000;
	mov.f32 	%f111, 0fBF800000;
	fma.rn.f32 	%f141, %f141, %f111, %f110;

BB0_51:
	cvta.to.global.u64 	%rd32, %rd15;
	cvta.to.global.u64 	%rd33, %rd14;
	cvta.to.global.u64 	%rd34, %rd13;
	cvta.to.global.u64 	%rd35, %rd20;
	cvta.to.global.u64 	%rd36, %rd19;
	cvta.to.global.u64 	%rd37, %rd18;
	mul.f32 	%f112, %f49, %f52;
	sub.f32 	%f113, %f48, %f112;
	mul.f32 	%f114, %f113, %f141;
	mul.f32 	%f115, %f49, %f51;
	sub.f32 	%f116, %f47, %f115;
	mul.f32 	%f117, %f116, %f135;
	sub.f32 	%f118, %f117, %f114;
	mul.f32 	%f119, %f13, %f118;
	mul.wide.s32 	%rd38, %r4, 4;
	add.s64 	%rd39, %rd37, %rd38;
	ld.global.nc.f32 	%f120, [%rd39];
	add.s64 	%rd40, %rd36, %rd38;
	ld.global.nc.f32 	%f121, [%rd40];
	add.s64 	%rd41, %rd35, %rd38;
	ld.global.nc.f32 	%f122, [%rd41];
	add.s64 	%rd42, %rd34, %rd38;
	ld.global.f32 	%f123, [%rd42];
	fma.rn.f32 	%f124, %f120, %f119, %f123;
	st.global.f32 	[%rd42], %f124;
	add.s64 	%rd43, %rd33, %rd38;
	ld.global.f32 	%f125, [%rd43];
	fma.rn.f32 	%f126, %f121, %f119, %f125;
	st.global.f32 	[%rd43], %f126;
	add.s64 	%rd44, %rd32, %rd38;
	ld.global.f32 	%f127, [%rd44];
	fma.rn.f32 	%f128, %f122, %f119, %f127;
	st.global.f32 	[%rd44], %f128;

BB0_52:
	ret;
}


`
 )
