package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for lltorque2time kernel
var lltorque2time_code cu.Function

// Stores the arguments for lltorque2time kernel invocation
type lltorque2time_args_t struct{
	 arg_tx unsafe.Pointer
	 arg_ty unsafe.Pointer
	 arg_tz unsafe.Pointer
	 arg_mx unsafe.Pointer
	 arg_my unsafe.Pointer
	 arg_mz unsafe.Pointer
	 arg_hx unsafe.Pointer
	 arg_hy unsafe.Pointer
	 arg_hz unsafe.Pointer
	 arg_alpha_ unsafe.Pointer
	 arg_alpha_mul float32
	 arg_time float32
	 arg_brms_x float32
	 arg_brms_y float32
	 arg_brms_z float32
	 arg_rk_mx unsafe.Pointer
	 arg_rk_my unsafe.Pointer
	 arg_rk_mz unsafe.Pointer
	 arg_rk_mx_current unsafe.Pointer
	 arg_rk_my_current unsafe.Pointer
	 arg_rk_mz_current unsafe.Pointer
	 arg_N int
	 argptr [22]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for lltorque2time kernel invocation
var lltorque2time_args lltorque2time_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 lltorque2time_args.argptr[0] = unsafe.Pointer(&lltorque2time_args.arg_tx)
	 lltorque2time_args.argptr[1] = unsafe.Pointer(&lltorque2time_args.arg_ty)
	 lltorque2time_args.argptr[2] = unsafe.Pointer(&lltorque2time_args.arg_tz)
	 lltorque2time_args.argptr[3] = unsafe.Pointer(&lltorque2time_args.arg_mx)
	 lltorque2time_args.argptr[4] = unsafe.Pointer(&lltorque2time_args.arg_my)
	 lltorque2time_args.argptr[5] = unsafe.Pointer(&lltorque2time_args.arg_mz)
	 lltorque2time_args.argptr[6] = unsafe.Pointer(&lltorque2time_args.arg_hx)
	 lltorque2time_args.argptr[7] = unsafe.Pointer(&lltorque2time_args.arg_hy)
	 lltorque2time_args.argptr[8] = unsafe.Pointer(&lltorque2time_args.arg_hz)
	 lltorque2time_args.argptr[9] = unsafe.Pointer(&lltorque2time_args.arg_alpha_)
	 lltorque2time_args.argptr[10] = unsafe.Pointer(&lltorque2time_args.arg_alpha_mul)
	 lltorque2time_args.argptr[11] = unsafe.Pointer(&lltorque2time_args.arg_time)
	 lltorque2time_args.argptr[12] = unsafe.Pointer(&lltorque2time_args.arg_brms_x)
	 lltorque2time_args.argptr[13] = unsafe.Pointer(&lltorque2time_args.arg_brms_y)
	 lltorque2time_args.argptr[14] = unsafe.Pointer(&lltorque2time_args.arg_brms_z)
	 lltorque2time_args.argptr[15] = unsafe.Pointer(&lltorque2time_args.arg_rk_mx)
	 lltorque2time_args.argptr[16] = unsafe.Pointer(&lltorque2time_args.arg_rk_my)
	 lltorque2time_args.argptr[17] = unsafe.Pointer(&lltorque2time_args.arg_rk_mz)
	 lltorque2time_args.argptr[18] = unsafe.Pointer(&lltorque2time_args.arg_rk_mx_current)
	 lltorque2time_args.argptr[19] = unsafe.Pointer(&lltorque2time_args.arg_rk_my_current)
	 lltorque2time_args.argptr[20] = unsafe.Pointer(&lltorque2time_args.arg_rk_mz_current)
	 lltorque2time_args.argptr[21] = unsafe.Pointer(&lltorque2time_args.arg_N)
	 }

// Wrapper for lltorque2time CUDA kernel, asynchronous.
func k_lltorque2time_async ( tx unsafe.Pointer, ty unsafe.Pointer, tz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, hx unsafe.Pointer, hy unsafe.Pointer, hz unsafe.Pointer, alpha_ unsafe.Pointer, alpha_mul float32, time float32, brms_x float32, brms_y float32, brms_z float32, rk_mx unsafe.Pointer, rk_my unsafe.Pointer, rk_mz unsafe.Pointer, rk_mx_current unsafe.Pointer, rk_my_current unsafe.Pointer, rk_mz_current unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("lltorque2time")
	}

	lltorque2time_args.Lock()
	defer lltorque2time_args.Unlock()

	if lltorque2time_code == 0{
		lltorque2time_code = fatbinLoad(lltorque2time_map, "lltorque2time")
	}

	 lltorque2time_args.arg_tx = tx
	 lltorque2time_args.arg_ty = ty
	 lltorque2time_args.arg_tz = tz
	 lltorque2time_args.arg_mx = mx
	 lltorque2time_args.arg_my = my
	 lltorque2time_args.arg_mz = mz
	 lltorque2time_args.arg_hx = hx
	 lltorque2time_args.arg_hy = hy
	 lltorque2time_args.arg_hz = hz
	 lltorque2time_args.arg_alpha_ = alpha_
	 lltorque2time_args.arg_alpha_mul = alpha_mul
	 lltorque2time_args.arg_time = time
	 lltorque2time_args.arg_brms_x = brms_x
	 lltorque2time_args.arg_brms_y = brms_y
	 lltorque2time_args.arg_brms_z = brms_z
	 lltorque2time_args.arg_rk_mx = rk_mx
	 lltorque2time_args.arg_rk_my = rk_my
	 lltorque2time_args.arg_rk_mz = rk_mz
	 lltorque2time_args.arg_rk_mx_current = rk_mx_current
	 lltorque2time_args.arg_rk_my_current = rk_my_current
	 lltorque2time_args.arg_rk_mz_current = rk_mz_current
	 lltorque2time_args.arg_N = N
	

	args := lltorque2time_args.argptr[:]
	cu.LaunchKernel(lltorque2time_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("lltorque2time")
	}
}

// maps compute capability on PTX code for lltorque2time kernel.
var lltorque2time_map = map[int]string{ 0: "" ,
30: lltorque2time_ptx_30 ,
35: lltorque2time_ptx_35 ,
37: lltorque2time_ptx_37 ,
50: lltorque2time_ptx_50 ,
52: lltorque2time_ptx_52 ,
53: lltorque2time_ptx_53 ,
60: lltorque2time_ptx_60 ,
61: lltorque2time_ptx_61 ,
70: lltorque2time_ptx_70 ,
75: lltorque2time_ptx_75  }

// lltorque2time PTX code for various compute capabilities.
const(
  lltorque2time_ptx_30 = `
.version 6.4
.target sm_30
.address_size 64

	// .globl	lltorque2time
.const .align 8 .f64 MUB = 0d3B266C5568970564;
.const .align 8 .f64 HBAR = 0d38E185A7054E4C91;
.const .align 8 .f64 GS = 0d4000000000000000;

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u64 lltorque2time_param_6,
	.param .u64 lltorque2time_param_7,
	.param .u64 lltorque2time_param_8,
	.param .u64 lltorque2time_param_9,
	.param .f32 lltorque2time_param_10,
	.param .f32 lltorque2time_param_11,
	.param .f32 lltorque2time_param_12,
	.param .f32 lltorque2time_param_13,
	.param .f32 lltorque2time_param_14,
	.param .u64 lltorque2time_param_15,
	.param .u64 lltorque2time_param_16,
	.param .u64 lltorque2time_param_17,
	.param .u64 lltorque2time_param_18,
	.param .u64 lltorque2time_param_19,
	.param .u64 lltorque2time_param_20,
	.param .u32 lltorque2time_param_21
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<45>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd4, [lltorque2time_param_0];
	ld.param.u64 	%rd5, [lltorque2time_param_1];
	ld.param.u64 	%rd6, [lltorque2time_param_2];
	ld.param.u64 	%rd7, [lltorque2time_param_3];
	ld.param.u64 	%rd8, [lltorque2time_param_4];
	ld.param.u64 	%rd9, [lltorque2time_param_5];
	ld.param.u64 	%rd10, [lltorque2time_param_6];
	ld.param.u64 	%rd11, [lltorque2time_param_7];
	ld.param.u64 	%rd12, [lltorque2time_param_8];
	ld.param.u64 	%rd13, [lltorque2time_param_9];
	ld.param.f32 	%f86, [lltorque2time_param_10];
	ld.param.f32 	%f26, [lltorque2time_param_11];
	ld.param.f32 	%f27, [lltorque2time_param_12];
	ld.param.f32 	%f28, [lltorque2time_param_13];
	ld.param.f32 	%f29, [lltorque2time_param_14];
	ld.param.u64 	%rd14, [lltorque2time_param_15];
	ld.param.u64 	%rd15, [lltorque2time_param_16];
	ld.param.u64 	%rd16, [lltorque2time_param_17];
	ld.param.u64 	%rd17, [lltorque2time_param_18];
	ld.param.u64 	%rd18, [lltorque2time_param_19];
	ld.param.u32 	%r9, [lltorque2time_param_21];
	mov.u32 	%r10, %ctaid.y;
	mov.u32 	%r11, %nctaid.x;
	mov.u32 	%r12, %ctaid.x;
	mad.lo.s32 	%r13, %r11, %r10, %r12;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r1, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r1, %r9;
	@%p1 bra 	BB0_14;

	cvta.to.global.u64 	%rd19, %rd7;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.f32 	%f1, [%rd21];
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd20;
	ld.global.f32 	%f2, [%rd23];
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd20;
	ld.global.f32 	%f3, [%rd25];
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd20;
	ld.global.f32 	%f4, [%rd27];
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd20;
	ld.global.f32 	%f5, [%rd29];
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.f32 	%f6, [%rd31];
	setp.eq.s64	%p2, %rd13, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd20;
	ld.global.f32 	%f30, [%rd34];
	mul.f32 	%f86, %f30, %f86;

BB0_3:
	mul.f32 	%f32, %f3, %f5;
	mul.f32 	%f33, %f2, %f6;
	sub.f32 	%f9, %f33, %f32;
	mul.f32 	%f34, %f1, %f6;
	mul.f32 	%f35, %f3, %f4;
	sub.f32 	%f10, %f35, %f34;
	mul.f32 	%f36, %f2, %f4;
	mul.f32 	%f37, %f1, %f5;
	sub.f32 	%f11, %f37, %f36;
	fma.rn.f32 	%f12, %f86, %f86, 0f3F800000;
	cvta.to.global.u64 	%rd35, %rd17;
	add.s64 	%rd37, %rd35, %rd20;
	cvta.to.global.u64 	%rd38, %rd18;
	add.s64 	%rd39, %rd38, %rd20;
	ld.global.f32 	%f13, [%rd39];
	ld.global.f32 	%f14, [%rd37];
	cvta.to.global.u64 	%rd1, %rd14;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd16;
	mov.f32 	%f91, 0f00000000;
	setp.lt.s32	%p3, %r9, 1;
	@%p3 bra 	BB0_13;

	add.s64 	%rd41, %rd1, %rd20;
	ld.global.f32 	%f41, [%rd41];
	add.s64 	%rd42, %rd2, %rd20;
	ld.global.f32 	%f42, [%rd42];
	add.s64 	%rd43, %rd3, %rd20;
	ld.global.f32 	%f43, [%rd43];
	mul.f32 	%f44, %f41, %f26;
	mul.f32 	%f45, %f42, %f26;
	mul.f32 	%f46, %f45, %f28;
	fma.rn.f32 	%f47, %f44, %f27, %f46;
	mul.f32 	%f48, %f43, %f26;
	fma.rn.f32 	%f15, %f48, %f29, %f47;
	and.b32  	%r32, %r9, 3;
	mov.f32 	%f91, 0f00000000;
	mov.u32 	%r41, 1;
	mov.u32 	%r43, 0;
	setp.eq.s32	%p4, %r32, 0;
	@%p4 bra 	BB0_11;

	setp.eq.s32	%p5, %r32, 1;
	@%p5 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r41, %r43;
	bra.uni 	BB0_10;

BB0_7:
	setp.eq.s32	%p6, %r32, 2;
	@%p6 bra 	BB0_9;

	add.f32 	%f91, %f15, 0f00000000;
	mov.u32 	%r41, 2;

BB0_9:
	add.f32 	%f91, %f15, %f91;

BB0_10:
	add.f32 	%f91, %f15, %f91;
	add.s32 	%r43, %r41, 1;

BB0_11:
	setp.lt.u32	%p7, %r9, 4;
	@%p7 bra 	BB0_13;

BB0_12:
	add.f32 	%f49, %f15, %f91;
	add.f32 	%f50, %f15, %f49;
	add.f32 	%f51, %f15, %f50;
	add.f32 	%f91, %f15, %f51;
	add.s32 	%r43, %r43, 4;
	setp.lt.s32	%p8, %r43, %r9;
	@%p8 bra 	BB0_12;

BB0_13:
	mov.f32 	%f52, 0fBF800000;
	div.rn.f32 	%f53, %f52, %f12;
	mul.f32 	%f54, %f13, %f27;
	mul.f32 	%f55, %f13, %f28;
	mul.f32 	%f56, %f13, %f29;
	sub.f32 	%f57, %f56, %f55;
	add.f32 	%f58, %f57, %f57;
	mul.f32 	%f59, %f58, %f91;
	mul.f32 	%f60, %f14, %f29;
	sub.f32 	%f61, %f54, %f60;
	add.f32 	%f62, %f61, %f61;
	mul.f32 	%f63, %f62, %f91;
	mul.f32 	%f64, %f14, %f28;
	sub.f32 	%f65, %f64, %f54;
	add.f32 	%f66, %f65, %f65;
	mul.f32 	%f67, %f66, %f91;
	mul.f32 	%f68, %f3, %f10;
	mul.f32 	%f69, %f2, %f11;
	sub.f32 	%f70, %f69, %f68;
	mul.f32 	%f71, %f1, %f11;
	mul.f32 	%f72, %f3, %f9;
	sub.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f2, %f9;
	mul.f32 	%f75, %f1, %f10;
	sub.f32 	%f76, %f75, %f74;
	fma.rn.f32 	%f77, %f70, %f86, %f9;
	fma.rn.f32 	%f78, %f73, %f86, %f10;
	fma.rn.f32 	%f79, %f76, %f86, %f11;
	mul.f32 	%f80, %f53, %f77;
	mul.f32 	%f81, %f53, %f78;
	mul.f32 	%f82, %f53, %f79;
	sub.f32 	%f83, %f80, %f59;
	sub.f32 	%f84, %f81, %f63;
	sub.f32 	%f85, %f82, %f67;
	cvta.to.global.u64 	%rd44, %rd4;
	add.s64 	%rd46, %rd44, %rd20;
	st.global.f32 	[%rd46], %f83;
	cvta.to.global.u64 	%rd47, %rd5;
	add.s64 	%rd48, %rd47, %rd20;
	st.global.f32 	[%rd48], %f84;
	cvta.to.global.u64 	%rd49, %rd6;
	add.s64 	%rd50, %rd49, %rd20;
	st.global.f32 	[%rd50], %f85;

BB0_14:
	ret;
}


`
   lltorque2time_ptx_35 = `
.version 6.4
.target sm_35
.address_size 64

	// .globl	lltorque2time
.const .align 8 .f64 MUB = 0d3B266C5568970564;
.const .align 8 .f64 HBAR = 0d38E185A7054E4C91;
.const .align 8 .f64 GS = 0d4000000000000000;

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u64 lltorque2time_param_6,
	.param .u64 lltorque2time_param_7,
	.param .u64 lltorque2time_param_8,
	.param .u64 lltorque2time_param_9,
	.param .f32 lltorque2time_param_10,
	.param .f32 lltorque2time_param_11,
	.param .f32 lltorque2time_param_12,
	.param .f32 lltorque2time_param_13,
	.param .f32 lltorque2time_param_14,
	.param .u64 lltorque2time_param_15,
	.param .u64 lltorque2time_param_16,
	.param .u64 lltorque2time_param_17,
	.param .u64 lltorque2time_param_18,
	.param .u64 lltorque2time_param_19,
	.param .u64 lltorque2time_param_20,
	.param .u32 lltorque2time_param_21
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd4, [lltorque2time_param_0];
	ld.param.u64 	%rd5, [lltorque2time_param_1];
	ld.param.u64 	%rd6, [lltorque2time_param_2];
	ld.param.u64 	%rd7, [lltorque2time_param_3];
	ld.param.u64 	%rd8, [lltorque2time_param_4];
	ld.param.u64 	%rd9, [lltorque2time_param_5];
	ld.param.u64 	%rd10, [lltorque2time_param_6];
	ld.param.u64 	%rd11, [lltorque2time_param_7];
	ld.param.u64 	%rd12, [lltorque2time_param_8];
	ld.param.u64 	%rd13, [lltorque2time_param_9];
	ld.param.f32 	%f86, [lltorque2time_param_10];
	ld.param.f32 	%f26, [lltorque2time_param_11];
	ld.param.f32 	%f27, [lltorque2time_param_12];
	ld.param.f32 	%f28, [lltorque2time_param_13];
	ld.param.f32 	%f29, [lltorque2time_param_14];
	ld.param.u64 	%rd14, [lltorque2time_param_15];
	ld.param.u64 	%rd15, [lltorque2time_param_16];
	ld.param.u64 	%rd16, [lltorque2time_param_17];
	ld.param.u64 	%rd17, [lltorque2time_param_18];
	ld.param.u64 	%rd18, [lltorque2time_param_19];
	ld.param.u32 	%r8, [lltorque2time_param_21];
	mov.u32 	%r9, %nctaid.x;
	mov.u32 	%r10, %ctaid.y;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r1, %r12, %r13, %r14;
	setp.ge.s32	%p1, %r1, %r8;
	@%p1 bra 	BB0_14;

	cvta.to.global.u64 	%rd19, %rd7;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd20;
	ld.global.nc.f32 	%f2, [%rd23];
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd20;
	ld.global.nc.f32 	%f3, [%rd25];
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd20;
	ld.global.nc.f32 	%f4, [%rd27];
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd20;
	ld.global.nc.f32 	%f5, [%rd29];
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.nc.f32 	%f6, [%rd31];
	setp.eq.s64	%p2, %rd13, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd20;
	ld.global.nc.f32 	%f30, [%rd34];
	mul.f32 	%f86, %f30, %f86;

BB0_3:
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd35, %rd18;
	cvta.to.global.u64 	%rd36, %rd17;
	mul.f32 	%f32, %f3, %f5;
	mul.f32 	%f33, %f2, %f6;
	sub.f32 	%f9, %f33, %f32;
	mul.f32 	%f34, %f1, %f6;
	mul.f32 	%f35, %f3, %f4;
	sub.f32 	%f10, %f35, %f34;
	mul.f32 	%f36, %f2, %f4;
	mul.f32 	%f37, %f1, %f5;
	sub.f32 	%f11, %f37, %f36;
	fma.rn.f32 	%f12, %f86, %f86, 0f3F800000;
	add.s64 	%rd38, %rd35, %rd20;
	ld.global.nc.f32 	%f13, [%rd38];
	add.s64 	%rd39, %rd36, %rd20;
	ld.global.nc.f32 	%f14, [%rd39];
	mov.f32 	%f91, 0f00000000;
	setp.lt.s32	%p3, %r8, 1;
	@%p3 bra 	BB0_13;

	add.s64 	%rd41, %rd3, %rd20;
	ld.global.nc.f32 	%f41, [%rd41];
	add.s64 	%rd42, %rd2, %rd20;
	ld.global.nc.f32 	%f42, [%rd42];
	add.s64 	%rd43, %rd1, %rd20;
	ld.global.nc.f32 	%f43, [%rd43];
	mul.f32 	%f44, %f41, %f26;
	mul.f32 	%f45, %f42, %f26;
	mul.f32 	%f46, %f45, %f28;
	fma.rn.f32 	%f47, %f44, %f27, %f46;
	mul.f32 	%f48, %f43, %f26;
	fma.rn.f32 	%f15, %f48, %f29, %f47;
	and.b32  	%r18, %r8, 3;
	mov.f32 	%f91, 0f00000000;
	mov.u32 	%r20, 1;
	mov.u32 	%r22, 0;
	setp.eq.s32	%p4, %r18, 0;
	@%p4 bra 	BB0_11;

	setp.eq.s32	%p5, %r18, 1;
	@%p5 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r20, %r22;
	bra.uni 	BB0_10;

BB0_7:
	setp.eq.s32	%p6, %r18, 2;
	@%p6 bra 	BB0_9;

	add.f32 	%f91, %f15, 0f00000000;
	mov.u32 	%r20, 2;

BB0_9:
	add.f32 	%f91, %f15, %f91;

BB0_10:
	add.f32 	%f91, %f15, %f91;
	add.s32 	%r22, %r20, 1;

BB0_11:
	setp.lt.u32	%p7, %r8, 4;
	@%p7 bra 	BB0_13;

BB0_12:
	add.f32 	%f49, %f15, %f91;
	add.f32 	%f50, %f15, %f49;
	add.f32 	%f51, %f15, %f50;
	add.f32 	%f91, %f15, %f51;
	add.s32 	%r22, %r22, 4;
	setp.lt.s32	%p8, %r22, %r8;
	@%p8 bra 	BB0_12;

BB0_13:
	cvta.to.global.u64 	%rd44, %rd6;
	cvta.to.global.u64 	%rd45, %rd5;
	cvta.to.global.u64 	%rd46, %rd4;
	mov.f32 	%f52, 0fBF800000;
	div.rn.f32 	%f53, %f52, %f12;
	mul.f32 	%f54, %f13, %f27;
	mul.f32 	%f55, %f13, %f28;
	mul.f32 	%f56, %f13, %f29;
	sub.f32 	%f57, %f56, %f55;
	add.f32 	%f58, %f57, %f57;
	mul.f32 	%f59, %f58, %f91;
	mul.f32 	%f60, %f14, %f29;
	sub.f32 	%f61, %f54, %f60;
	add.f32 	%f62, %f61, %f61;
	mul.f32 	%f63, %f62, %f91;
	mul.f32 	%f64, %f14, %f28;
	sub.f32 	%f65, %f64, %f54;
	add.f32 	%f66, %f65, %f65;
	mul.f32 	%f67, %f66, %f91;
	mul.f32 	%f68, %f3, %f10;
	mul.f32 	%f69, %f2, %f11;
	sub.f32 	%f70, %f69, %f68;
	mul.f32 	%f71, %f1, %f11;
	mul.f32 	%f72, %f3, %f9;
	sub.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f2, %f9;
	mul.f32 	%f75, %f1, %f10;
	sub.f32 	%f76, %f75, %f74;
	fma.rn.f32 	%f77, %f70, %f86, %f9;
	fma.rn.f32 	%f78, %f73, %f86, %f10;
	fma.rn.f32 	%f79, %f76, %f86, %f11;
	mul.f32 	%f80, %f53, %f77;
	mul.f32 	%f81, %f53, %f78;
	mul.f32 	%f82, %f53, %f79;
	sub.f32 	%f83, %f80, %f59;
	sub.f32 	%f84, %f81, %f63;
	sub.f32 	%f85, %f82, %f67;
	add.s64 	%rd48, %rd46, %rd20;
	st.global.f32 	[%rd48], %f83;
	add.s64 	%rd49, %rd45, %rd20;
	st.global.f32 	[%rd49], %f84;
	add.s64 	%rd50, %rd44, %rd20;
	st.global.f32 	[%rd50], %f85;

BB0_14:
	ret;
}


`
   lltorque2time_ptx_37 = `
.version 6.4
.target sm_37
.address_size 64

	// .globl	lltorque2time
.const .align 8 .f64 MUB = 0d3B266C5568970564;
.const .align 8 .f64 HBAR = 0d38E185A7054E4C91;
.const .align 8 .f64 GS = 0d4000000000000000;

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u64 lltorque2time_param_6,
	.param .u64 lltorque2time_param_7,
	.param .u64 lltorque2time_param_8,
	.param .u64 lltorque2time_param_9,
	.param .f32 lltorque2time_param_10,
	.param .f32 lltorque2time_param_11,
	.param .f32 lltorque2time_param_12,
	.param .f32 lltorque2time_param_13,
	.param .f32 lltorque2time_param_14,
	.param .u64 lltorque2time_param_15,
	.param .u64 lltorque2time_param_16,
	.param .u64 lltorque2time_param_17,
	.param .u64 lltorque2time_param_18,
	.param .u64 lltorque2time_param_19,
	.param .u64 lltorque2time_param_20,
	.param .u32 lltorque2time_param_21
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd4, [lltorque2time_param_0];
	ld.param.u64 	%rd5, [lltorque2time_param_1];
	ld.param.u64 	%rd6, [lltorque2time_param_2];
	ld.param.u64 	%rd7, [lltorque2time_param_3];
	ld.param.u64 	%rd8, [lltorque2time_param_4];
	ld.param.u64 	%rd9, [lltorque2time_param_5];
	ld.param.u64 	%rd10, [lltorque2time_param_6];
	ld.param.u64 	%rd11, [lltorque2time_param_7];
	ld.param.u64 	%rd12, [lltorque2time_param_8];
	ld.param.u64 	%rd13, [lltorque2time_param_9];
	ld.param.f32 	%f86, [lltorque2time_param_10];
	ld.param.f32 	%f26, [lltorque2time_param_11];
	ld.param.f32 	%f27, [lltorque2time_param_12];
	ld.param.f32 	%f28, [lltorque2time_param_13];
	ld.param.f32 	%f29, [lltorque2time_param_14];
	ld.param.u64 	%rd14, [lltorque2time_param_15];
	ld.param.u64 	%rd15, [lltorque2time_param_16];
	ld.param.u64 	%rd16, [lltorque2time_param_17];
	ld.param.u64 	%rd17, [lltorque2time_param_18];
	ld.param.u64 	%rd18, [lltorque2time_param_19];
	ld.param.u32 	%r8, [lltorque2time_param_21];
	mov.u32 	%r9, %nctaid.x;
	mov.u32 	%r10, %ctaid.y;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r1, %r12, %r13, %r14;
	setp.ge.s32	%p1, %r1, %r8;
	@%p1 bra 	BB0_14;

	cvta.to.global.u64 	%rd19, %rd7;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd20;
	ld.global.nc.f32 	%f2, [%rd23];
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd20;
	ld.global.nc.f32 	%f3, [%rd25];
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd20;
	ld.global.nc.f32 	%f4, [%rd27];
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd20;
	ld.global.nc.f32 	%f5, [%rd29];
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.nc.f32 	%f6, [%rd31];
	setp.eq.s64	%p2, %rd13, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd20;
	ld.global.nc.f32 	%f30, [%rd34];
	mul.f32 	%f86, %f30, %f86;

BB0_3:
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd35, %rd18;
	cvta.to.global.u64 	%rd36, %rd17;
	mul.f32 	%f32, %f3, %f5;
	mul.f32 	%f33, %f2, %f6;
	sub.f32 	%f9, %f33, %f32;
	mul.f32 	%f34, %f1, %f6;
	mul.f32 	%f35, %f3, %f4;
	sub.f32 	%f10, %f35, %f34;
	mul.f32 	%f36, %f2, %f4;
	mul.f32 	%f37, %f1, %f5;
	sub.f32 	%f11, %f37, %f36;
	fma.rn.f32 	%f12, %f86, %f86, 0f3F800000;
	add.s64 	%rd38, %rd35, %rd20;
	ld.global.nc.f32 	%f13, [%rd38];
	add.s64 	%rd39, %rd36, %rd20;
	ld.global.nc.f32 	%f14, [%rd39];
	mov.f32 	%f91, 0f00000000;
	setp.lt.s32	%p3, %r8, 1;
	@%p3 bra 	BB0_13;

	add.s64 	%rd41, %rd3, %rd20;
	ld.global.nc.f32 	%f41, [%rd41];
	add.s64 	%rd42, %rd2, %rd20;
	ld.global.nc.f32 	%f42, [%rd42];
	add.s64 	%rd43, %rd1, %rd20;
	ld.global.nc.f32 	%f43, [%rd43];
	mul.f32 	%f44, %f41, %f26;
	mul.f32 	%f45, %f42, %f26;
	mul.f32 	%f46, %f45, %f28;
	fma.rn.f32 	%f47, %f44, %f27, %f46;
	mul.f32 	%f48, %f43, %f26;
	fma.rn.f32 	%f15, %f48, %f29, %f47;
	and.b32  	%r18, %r8, 3;
	mov.f32 	%f91, 0f00000000;
	mov.u32 	%r20, 1;
	mov.u32 	%r22, 0;
	setp.eq.s32	%p4, %r18, 0;
	@%p4 bra 	BB0_11;

	setp.eq.s32	%p5, %r18, 1;
	@%p5 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r20, %r22;
	bra.uni 	BB0_10;

BB0_7:
	setp.eq.s32	%p6, %r18, 2;
	@%p6 bra 	BB0_9;

	add.f32 	%f91, %f15, 0f00000000;
	mov.u32 	%r20, 2;

BB0_9:
	add.f32 	%f91, %f15, %f91;

BB0_10:
	add.f32 	%f91, %f15, %f91;
	add.s32 	%r22, %r20, 1;

BB0_11:
	setp.lt.u32	%p7, %r8, 4;
	@%p7 bra 	BB0_13;

BB0_12:
	add.f32 	%f49, %f15, %f91;
	add.f32 	%f50, %f15, %f49;
	add.f32 	%f51, %f15, %f50;
	add.f32 	%f91, %f15, %f51;
	add.s32 	%r22, %r22, 4;
	setp.lt.s32	%p8, %r22, %r8;
	@%p8 bra 	BB0_12;

BB0_13:
	cvta.to.global.u64 	%rd44, %rd6;
	cvta.to.global.u64 	%rd45, %rd5;
	cvta.to.global.u64 	%rd46, %rd4;
	mov.f32 	%f52, 0fBF800000;
	div.rn.f32 	%f53, %f52, %f12;
	mul.f32 	%f54, %f13, %f27;
	mul.f32 	%f55, %f13, %f28;
	mul.f32 	%f56, %f13, %f29;
	sub.f32 	%f57, %f56, %f55;
	add.f32 	%f58, %f57, %f57;
	mul.f32 	%f59, %f58, %f91;
	mul.f32 	%f60, %f14, %f29;
	sub.f32 	%f61, %f54, %f60;
	add.f32 	%f62, %f61, %f61;
	mul.f32 	%f63, %f62, %f91;
	mul.f32 	%f64, %f14, %f28;
	sub.f32 	%f65, %f64, %f54;
	add.f32 	%f66, %f65, %f65;
	mul.f32 	%f67, %f66, %f91;
	mul.f32 	%f68, %f3, %f10;
	mul.f32 	%f69, %f2, %f11;
	sub.f32 	%f70, %f69, %f68;
	mul.f32 	%f71, %f1, %f11;
	mul.f32 	%f72, %f3, %f9;
	sub.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f2, %f9;
	mul.f32 	%f75, %f1, %f10;
	sub.f32 	%f76, %f75, %f74;
	fma.rn.f32 	%f77, %f70, %f86, %f9;
	fma.rn.f32 	%f78, %f73, %f86, %f10;
	fma.rn.f32 	%f79, %f76, %f86, %f11;
	mul.f32 	%f80, %f53, %f77;
	mul.f32 	%f81, %f53, %f78;
	mul.f32 	%f82, %f53, %f79;
	sub.f32 	%f83, %f80, %f59;
	sub.f32 	%f84, %f81, %f63;
	sub.f32 	%f85, %f82, %f67;
	add.s64 	%rd48, %rd46, %rd20;
	st.global.f32 	[%rd48], %f83;
	add.s64 	%rd49, %rd45, %rd20;
	st.global.f32 	[%rd49], %f84;
	add.s64 	%rd50, %rd44, %rd20;
	st.global.f32 	[%rd50], %f85;

BB0_14:
	ret;
}


`
   lltorque2time_ptx_50 = `
.version 6.4
.target sm_50
.address_size 64

	// .globl	lltorque2time
.const .align 8 .f64 MUB = 0d3B266C5568970564;
.const .align 8 .f64 HBAR = 0d38E185A7054E4C91;
.const .align 8 .f64 GS = 0d4000000000000000;

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u64 lltorque2time_param_6,
	.param .u64 lltorque2time_param_7,
	.param .u64 lltorque2time_param_8,
	.param .u64 lltorque2time_param_9,
	.param .f32 lltorque2time_param_10,
	.param .f32 lltorque2time_param_11,
	.param .f32 lltorque2time_param_12,
	.param .f32 lltorque2time_param_13,
	.param .f32 lltorque2time_param_14,
	.param .u64 lltorque2time_param_15,
	.param .u64 lltorque2time_param_16,
	.param .u64 lltorque2time_param_17,
	.param .u64 lltorque2time_param_18,
	.param .u64 lltorque2time_param_19,
	.param .u64 lltorque2time_param_20,
	.param .u32 lltorque2time_param_21
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd4, [lltorque2time_param_0];
	ld.param.u64 	%rd5, [lltorque2time_param_1];
	ld.param.u64 	%rd6, [lltorque2time_param_2];
	ld.param.u64 	%rd7, [lltorque2time_param_3];
	ld.param.u64 	%rd8, [lltorque2time_param_4];
	ld.param.u64 	%rd9, [lltorque2time_param_5];
	ld.param.u64 	%rd10, [lltorque2time_param_6];
	ld.param.u64 	%rd11, [lltorque2time_param_7];
	ld.param.u64 	%rd12, [lltorque2time_param_8];
	ld.param.u64 	%rd13, [lltorque2time_param_9];
	ld.param.f32 	%f86, [lltorque2time_param_10];
	ld.param.f32 	%f26, [lltorque2time_param_11];
	ld.param.f32 	%f27, [lltorque2time_param_12];
	ld.param.f32 	%f28, [lltorque2time_param_13];
	ld.param.f32 	%f29, [lltorque2time_param_14];
	ld.param.u64 	%rd14, [lltorque2time_param_15];
	ld.param.u64 	%rd15, [lltorque2time_param_16];
	ld.param.u64 	%rd16, [lltorque2time_param_17];
	ld.param.u64 	%rd17, [lltorque2time_param_18];
	ld.param.u64 	%rd18, [lltorque2time_param_19];
	ld.param.u32 	%r8, [lltorque2time_param_21];
	mov.u32 	%r9, %nctaid.x;
	mov.u32 	%r10, %ctaid.y;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r1, %r12, %r13, %r14;
	setp.ge.s32	%p1, %r1, %r8;
	@%p1 bra 	BB0_14;

	cvta.to.global.u64 	%rd19, %rd7;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd20;
	ld.global.nc.f32 	%f2, [%rd23];
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd20;
	ld.global.nc.f32 	%f3, [%rd25];
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd20;
	ld.global.nc.f32 	%f4, [%rd27];
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd20;
	ld.global.nc.f32 	%f5, [%rd29];
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.nc.f32 	%f6, [%rd31];
	setp.eq.s64	%p2, %rd13, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd20;
	ld.global.nc.f32 	%f30, [%rd34];
	mul.f32 	%f86, %f30, %f86;

BB0_3:
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd35, %rd18;
	cvta.to.global.u64 	%rd36, %rd17;
	mul.f32 	%f32, %f3, %f5;
	mul.f32 	%f33, %f2, %f6;
	sub.f32 	%f9, %f33, %f32;
	mul.f32 	%f34, %f1, %f6;
	mul.f32 	%f35, %f3, %f4;
	sub.f32 	%f10, %f35, %f34;
	mul.f32 	%f36, %f2, %f4;
	mul.f32 	%f37, %f1, %f5;
	sub.f32 	%f11, %f37, %f36;
	fma.rn.f32 	%f12, %f86, %f86, 0f3F800000;
	add.s64 	%rd38, %rd35, %rd20;
	ld.global.nc.f32 	%f13, [%rd38];
	add.s64 	%rd39, %rd36, %rd20;
	ld.global.nc.f32 	%f14, [%rd39];
	mov.f32 	%f91, 0f00000000;
	setp.lt.s32	%p3, %r8, 1;
	@%p3 bra 	BB0_13;

	add.s64 	%rd41, %rd3, %rd20;
	ld.global.nc.f32 	%f41, [%rd41];
	add.s64 	%rd42, %rd2, %rd20;
	ld.global.nc.f32 	%f42, [%rd42];
	add.s64 	%rd43, %rd1, %rd20;
	ld.global.nc.f32 	%f43, [%rd43];
	mul.f32 	%f44, %f41, %f26;
	mul.f32 	%f45, %f42, %f26;
	mul.f32 	%f46, %f45, %f28;
	fma.rn.f32 	%f47, %f44, %f27, %f46;
	mul.f32 	%f48, %f43, %f26;
	fma.rn.f32 	%f15, %f48, %f29, %f47;
	and.b32  	%r18, %r8, 3;
	mov.f32 	%f91, 0f00000000;
	mov.u32 	%r20, 1;
	mov.u32 	%r22, 0;
	setp.eq.s32	%p4, %r18, 0;
	@%p4 bra 	BB0_11;

	setp.eq.s32	%p5, %r18, 1;
	@%p5 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r20, %r22;
	bra.uni 	BB0_10;

BB0_7:
	setp.eq.s32	%p6, %r18, 2;
	@%p6 bra 	BB0_9;

	add.f32 	%f91, %f15, 0f00000000;
	mov.u32 	%r20, 2;

BB0_9:
	add.f32 	%f91, %f15, %f91;

BB0_10:
	add.f32 	%f91, %f15, %f91;
	add.s32 	%r22, %r20, 1;

BB0_11:
	setp.lt.u32	%p7, %r8, 4;
	@%p7 bra 	BB0_13;

BB0_12:
	add.f32 	%f49, %f15, %f91;
	add.f32 	%f50, %f15, %f49;
	add.f32 	%f51, %f15, %f50;
	add.f32 	%f91, %f15, %f51;
	add.s32 	%r22, %r22, 4;
	setp.lt.s32	%p8, %r22, %r8;
	@%p8 bra 	BB0_12;

BB0_13:
	cvta.to.global.u64 	%rd44, %rd6;
	cvta.to.global.u64 	%rd45, %rd5;
	cvta.to.global.u64 	%rd46, %rd4;
	mov.f32 	%f52, 0fBF800000;
	div.rn.f32 	%f53, %f52, %f12;
	mul.f32 	%f54, %f13, %f27;
	mul.f32 	%f55, %f13, %f28;
	mul.f32 	%f56, %f13, %f29;
	sub.f32 	%f57, %f56, %f55;
	add.f32 	%f58, %f57, %f57;
	mul.f32 	%f59, %f58, %f91;
	mul.f32 	%f60, %f14, %f29;
	sub.f32 	%f61, %f54, %f60;
	add.f32 	%f62, %f61, %f61;
	mul.f32 	%f63, %f62, %f91;
	mul.f32 	%f64, %f14, %f28;
	sub.f32 	%f65, %f64, %f54;
	add.f32 	%f66, %f65, %f65;
	mul.f32 	%f67, %f66, %f91;
	mul.f32 	%f68, %f3, %f10;
	mul.f32 	%f69, %f2, %f11;
	sub.f32 	%f70, %f69, %f68;
	mul.f32 	%f71, %f1, %f11;
	mul.f32 	%f72, %f3, %f9;
	sub.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f2, %f9;
	mul.f32 	%f75, %f1, %f10;
	sub.f32 	%f76, %f75, %f74;
	fma.rn.f32 	%f77, %f70, %f86, %f9;
	fma.rn.f32 	%f78, %f73, %f86, %f10;
	fma.rn.f32 	%f79, %f76, %f86, %f11;
	mul.f32 	%f80, %f53, %f77;
	mul.f32 	%f81, %f53, %f78;
	mul.f32 	%f82, %f53, %f79;
	sub.f32 	%f83, %f80, %f59;
	sub.f32 	%f84, %f81, %f63;
	sub.f32 	%f85, %f82, %f67;
	add.s64 	%rd48, %rd46, %rd20;
	st.global.f32 	[%rd48], %f83;
	add.s64 	%rd49, %rd45, %rd20;
	st.global.f32 	[%rd49], %f84;
	add.s64 	%rd50, %rd44, %rd20;
	st.global.f32 	[%rd50], %f85;

BB0_14:
	ret;
}


`
   lltorque2time_ptx_52 = `
.version 6.4
.target sm_52
.address_size 64

	// .globl	lltorque2time
.const .align 8 .f64 MUB = 0d3B266C5568970564;
.const .align 8 .f64 HBAR = 0d38E185A7054E4C91;
.const .align 8 .f64 GS = 0d4000000000000000;

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u64 lltorque2time_param_6,
	.param .u64 lltorque2time_param_7,
	.param .u64 lltorque2time_param_8,
	.param .u64 lltorque2time_param_9,
	.param .f32 lltorque2time_param_10,
	.param .f32 lltorque2time_param_11,
	.param .f32 lltorque2time_param_12,
	.param .f32 lltorque2time_param_13,
	.param .f32 lltorque2time_param_14,
	.param .u64 lltorque2time_param_15,
	.param .u64 lltorque2time_param_16,
	.param .u64 lltorque2time_param_17,
	.param .u64 lltorque2time_param_18,
	.param .u64 lltorque2time_param_19,
	.param .u64 lltorque2time_param_20,
	.param .u32 lltorque2time_param_21
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd4, [lltorque2time_param_0];
	ld.param.u64 	%rd5, [lltorque2time_param_1];
	ld.param.u64 	%rd6, [lltorque2time_param_2];
	ld.param.u64 	%rd7, [lltorque2time_param_3];
	ld.param.u64 	%rd8, [lltorque2time_param_4];
	ld.param.u64 	%rd9, [lltorque2time_param_5];
	ld.param.u64 	%rd10, [lltorque2time_param_6];
	ld.param.u64 	%rd11, [lltorque2time_param_7];
	ld.param.u64 	%rd12, [lltorque2time_param_8];
	ld.param.u64 	%rd13, [lltorque2time_param_9];
	ld.param.f32 	%f86, [lltorque2time_param_10];
	ld.param.f32 	%f26, [lltorque2time_param_11];
	ld.param.f32 	%f27, [lltorque2time_param_12];
	ld.param.f32 	%f28, [lltorque2time_param_13];
	ld.param.f32 	%f29, [lltorque2time_param_14];
	ld.param.u64 	%rd14, [lltorque2time_param_15];
	ld.param.u64 	%rd15, [lltorque2time_param_16];
	ld.param.u64 	%rd16, [lltorque2time_param_17];
	ld.param.u64 	%rd17, [lltorque2time_param_18];
	ld.param.u64 	%rd18, [lltorque2time_param_19];
	ld.param.u32 	%r8, [lltorque2time_param_21];
	mov.u32 	%r9, %nctaid.x;
	mov.u32 	%r10, %ctaid.y;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r1, %r12, %r13, %r14;
	setp.ge.s32	%p1, %r1, %r8;
	@%p1 bra 	BB0_14;

	cvta.to.global.u64 	%rd19, %rd7;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd20;
	ld.global.nc.f32 	%f2, [%rd23];
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd20;
	ld.global.nc.f32 	%f3, [%rd25];
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd20;
	ld.global.nc.f32 	%f4, [%rd27];
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd20;
	ld.global.nc.f32 	%f5, [%rd29];
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.nc.f32 	%f6, [%rd31];
	setp.eq.s64	%p2, %rd13, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd20;
	ld.global.nc.f32 	%f30, [%rd34];
	mul.f32 	%f86, %f30, %f86;

BB0_3:
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd35, %rd18;
	cvta.to.global.u64 	%rd36, %rd17;
	mul.f32 	%f32, %f3, %f5;
	mul.f32 	%f33, %f2, %f6;
	sub.f32 	%f9, %f33, %f32;
	mul.f32 	%f34, %f1, %f6;
	mul.f32 	%f35, %f3, %f4;
	sub.f32 	%f10, %f35, %f34;
	mul.f32 	%f36, %f2, %f4;
	mul.f32 	%f37, %f1, %f5;
	sub.f32 	%f11, %f37, %f36;
	fma.rn.f32 	%f12, %f86, %f86, 0f3F800000;
	add.s64 	%rd38, %rd35, %rd20;
	ld.global.nc.f32 	%f13, [%rd38];
	add.s64 	%rd39, %rd36, %rd20;
	ld.global.nc.f32 	%f14, [%rd39];
	mov.f32 	%f91, 0f00000000;
	setp.lt.s32	%p3, %r8, 1;
	@%p3 bra 	BB0_13;

	add.s64 	%rd41, %rd3, %rd20;
	ld.global.nc.f32 	%f41, [%rd41];
	add.s64 	%rd42, %rd2, %rd20;
	ld.global.nc.f32 	%f42, [%rd42];
	add.s64 	%rd43, %rd1, %rd20;
	ld.global.nc.f32 	%f43, [%rd43];
	mul.f32 	%f44, %f41, %f26;
	mul.f32 	%f45, %f42, %f26;
	mul.f32 	%f46, %f45, %f28;
	fma.rn.f32 	%f47, %f44, %f27, %f46;
	mul.f32 	%f48, %f43, %f26;
	fma.rn.f32 	%f15, %f48, %f29, %f47;
	and.b32  	%r18, %r8, 3;
	mov.f32 	%f91, 0f00000000;
	mov.u32 	%r20, 1;
	mov.u32 	%r22, 0;
	setp.eq.s32	%p4, %r18, 0;
	@%p4 bra 	BB0_11;

	setp.eq.s32	%p5, %r18, 1;
	@%p5 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r20, %r22;
	bra.uni 	BB0_10;

BB0_7:
	setp.eq.s32	%p6, %r18, 2;
	@%p6 bra 	BB0_9;

	add.f32 	%f91, %f15, 0f00000000;
	mov.u32 	%r20, 2;

BB0_9:
	add.f32 	%f91, %f15, %f91;

BB0_10:
	add.f32 	%f91, %f15, %f91;
	add.s32 	%r22, %r20, 1;

BB0_11:
	setp.lt.u32	%p7, %r8, 4;
	@%p7 bra 	BB0_13;

BB0_12:
	add.f32 	%f49, %f15, %f91;
	add.f32 	%f50, %f15, %f49;
	add.f32 	%f51, %f15, %f50;
	add.f32 	%f91, %f15, %f51;
	add.s32 	%r22, %r22, 4;
	setp.lt.s32	%p8, %r22, %r8;
	@%p8 bra 	BB0_12;

BB0_13:
	cvta.to.global.u64 	%rd44, %rd6;
	cvta.to.global.u64 	%rd45, %rd5;
	cvta.to.global.u64 	%rd46, %rd4;
	mov.f32 	%f52, 0fBF800000;
	div.rn.f32 	%f53, %f52, %f12;
	mul.f32 	%f54, %f13, %f27;
	mul.f32 	%f55, %f13, %f28;
	mul.f32 	%f56, %f13, %f29;
	sub.f32 	%f57, %f56, %f55;
	add.f32 	%f58, %f57, %f57;
	mul.f32 	%f59, %f58, %f91;
	mul.f32 	%f60, %f14, %f29;
	sub.f32 	%f61, %f54, %f60;
	add.f32 	%f62, %f61, %f61;
	mul.f32 	%f63, %f62, %f91;
	mul.f32 	%f64, %f14, %f28;
	sub.f32 	%f65, %f64, %f54;
	add.f32 	%f66, %f65, %f65;
	mul.f32 	%f67, %f66, %f91;
	mul.f32 	%f68, %f3, %f10;
	mul.f32 	%f69, %f2, %f11;
	sub.f32 	%f70, %f69, %f68;
	mul.f32 	%f71, %f1, %f11;
	mul.f32 	%f72, %f3, %f9;
	sub.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f2, %f9;
	mul.f32 	%f75, %f1, %f10;
	sub.f32 	%f76, %f75, %f74;
	fma.rn.f32 	%f77, %f70, %f86, %f9;
	fma.rn.f32 	%f78, %f73, %f86, %f10;
	fma.rn.f32 	%f79, %f76, %f86, %f11;
	mul.f32 	%f80, %f53, %f77;
	mul.f32 	%f81, %f53, %f78;
	mul.f32 	%f82, %f53, %f79;
	sub.f32 	%f83, %f80, %f59;
	sub.f32 	%f84, %f81, %f63;
	sub.f32 	%f85, %f82, %f67;
	add.s64 	%rd48, %rd46, %rd20;
	st.global.f32 	[%rd48], %f83;
	add.s64 	%rd49, %rd45, %rd20;
	st.global.f32 	[%rd49], %f84;
	add.s64 	%rd50, %rd44, %rd20;
	st.global.f32 	[%rd50], %f85;

BB0_14:
	ret;
}


`
   lltorque2time_ptx_53 = `
.version 6.4
.target sm_53
.address_size 64

	// .globl	lltorque2time
.const .align 8 .f64 MUB = 0d3B266C5568970564;
.const .align 8 .f64 HBAR = 0d38E185A7054E4C91;
.const .align 8 .f64 GS = 0d4000000000000000;

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u64 lltorque2time_param_6,
	.param .u64 lltorque2time_param_7,
	.param .u64 lltorque2time_param_8,
	.param .u64 lltorque2time_param_9,
	.param .f32 lltorque2time_param_10,
	.param .f32 lltorque2time_param_11,
	.param .f32 lltorque2time_param_12,
	.param .f32 lltorque2time_param_13,
	.param .f32 lltorque2time_param_14,
	.param .u64 lltorque2time_param_15,
	.param .u64 lltorque2time_param_16,
	.param .u64 lltorque2time_param_17,
	.param .u64 lltorque2time_param_18,
	.param .u64 lltorque2time_param_19,
	.param .u64 lltorque2time_param_20,
	.param .u32 lltorque2time_param_21
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd4, [lltorque2time_param_0];
	ld.param.u64 	%rd5, [lltorque2time_param_1];
	ld.param.u64 	%rd6, [lltorque2time_param_2];
	ld.param.u64 	%rd7, [lltorque2time_param_3];
	ld.param.u64 	%rd8, [lltorque2time_param_4];
	ld.param.u64 	%rd9, [lltorque2time_param_5];
	ld.param.u64 	%rd10, [lltorque2time_param_6];
	ld.param.u64 	%rd11, [lltorque2time_param_7];
	ld.param.u64 	%rd12, [lltorque2time_param_8];
	ld.param.u64 	%rd13, [lltorque2time_param_9];
	ld.param.f32 	%f86, [lltorque2time_param_10];
	ld.param.f32 	%f26, [lltorque2time_param_11];
	ld.param.f32 	%f27, [lltorque2time_param_12];
	ld.param.f32 	%f28, [lltorque2time_param_13];
	ld.param.f32 	%f29, [lltorque2time_param_14];
	ld.param.u64 	%rd14, [lltorque2time_param_15];
	ld.param.u64 	%rd15, [lltorque2time_param_16];
	ld.param.u64 	%rd16, [lltorque2time_param_17];
	ld.param.u64 	%rd17, [lltorque2time_param_18];
	ld.param.u64 	%rd18, [lltorque2time_param_19];
	ld.param.u32 	%r8, [lltorque2time_param_21];
	mov.u32 	%r9, %nctaid.x;
	mov.u32 	%r10, %ctaid.y;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r1, %r12, %r13, %r14;
	setp.ge.s32	%p1, %r1, %r8;
	@%p1 bra 	BB0_14;

	cvta.to.global.u64 	%rd19, %rd7;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd20;
	ld.global.nc.f32 	%f2, [%rd23];
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd20;
	ld.global.nc.f32 	%f3, [%rd25];
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd20;
	ld.global.nc.f32 	%f4, [%rd27];
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd20;
	ld.global.nc.f32 	%f5, [%rd29];
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.nc.f32 	%f6, [%rd31];
	setp.eq.s64	%p2, %rd13, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd20;
	ld.global.nc.f32 	%f30, [%rd34];
	mul.f32 	%f86, %f30, %f86;

BB0_3:
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd35, %rd18;
	cvta.to.global.u64 	%rd36, %rd17;
	mul.f32 	%f32, %f3, %f5;
	mul.f32 	%f33, %f2, %f6;
	sub.f32 	%f9, %f33, %f32;
	mul.f32 	%f34, %f1, %f6;
	mul.f32 	%f35, %f3, %f4;
	sub.f32 	%f10, %f35, %f34;
	mul.f32 	%f36, %f2, %f4;
	mul.f32 	%f37, %f1, %f5;
	sub.f32 	%f11, %f37, %f36;
	fma.rn.f32 	%f12, %f86, %f86, 0f3F800000;
	add.s64 	%rd38, %rd35, %rd20;
	ld.global.nc.f32 	%f13, [%rd38];
	add.s64 	%rd39, %rd36, %rd20;
	ld.global.nc.f32 	%f14, [%rd39];
	mov.f32 	%f91, 0f00000000;
	setp.lt.s32	%p3, %r8, 1;
	@%p3 bra 	BB0_13;

	add.s64 	%rd41, %rd3, %rd20;
	ld.global.nc.f32 	%f41, [%rd41];
	add.s64 	%rd42, %rd2, %rd20;
	ld.global.nc.f32 	%f42, [%rd42];
	add.s64 	%rd43, %rd1, %rd20;
	ld.global.nc.f32 	%f43, [%rd43];
	mul.f32 	%f44, %f41, %f26;
	mul.f32 	%f45, %f42, %f26;
	mul.f32 	%f46, %f45, %f28;
	fma.rn.f32 	%f47, %f44, %f27, %f46;
	mul.f32 	%f48, %f43, %f26;
	fma.rn.f32 	%f15, %f48, %f29, %f47;
	and.b32  	%r18, %r8, 3;
	mov.f32 	%f91, 0f00000000;
	mov.u32 	%r20, 1;
	mov.u32 	%r22, 0;
	setp.eq.s32	%p4, %r18, 0;
	@%p4 bra 	BB0_11;

	setp.eq.s32	%p5, %r18, 1;
	@%p5 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r20, %r22;
	bra.uni 	BB0_10;

BB0_7:
	setp.eq.s32	%p6, %r18, 2;
	@%p6 bra 	BB0_9;

	add.f32 	%f91, %f15, 0f00000000;
	mov.u32 	%r20, 2;

BB0_9:
	add.f32 	%f91, %f15, %f91;

BB0_10:
	add.f32 	%f91, %f15, %f91;
	add.s32 	%r22, %r20, 1;

BB0_11:
	setp.lt.u32	%p7, %r8, 4;
	@%p7 bra 	BB0_13;

BB0_12:
	add.f32 	%f49, %f15, %f91;
	add.f32 	%f50, %f15, %f49;
	add.f32 	%f51, %f15, %f50;
	add.f32 	%f91, %f15, %f51;
	add.s32 	%r22, %r22, 4;
	setp.lt.s32	%p8, %r22, %r8;
	@%p8 bra 	BB0_12;

BB0_13:
	cvta.to.global.u64 	%rd44, %rd6;
	cvta.to.global.u64 	%rd45, %rd5;
	cvta.to.global.u64 	%rd46, %rd4;
	mov.f32 	%f52, 0fBF800000;
	div.rn.f32 	%f53, %f52, %f12;
	mul.f32 	%f54, %f13, %f27;
	mul.f32 	%f55, %f13, %f28;
	mul.f32 	%f56, %f13, %f29;
	sub.f32 	%f57, %f56, %f55;
	add.f32 	%f58, %f57, %f57;
	mul.f32 	%f59, %f58, %f91;
	mul.f32 	%f60, %f14, %f29;
	sub.f32 	%f61, %f54, %f60;
	add.f32 	%f62, %f61, %f61;
	mul.f32 	%f63, %f62, %f91;
	mul.f32 	%f64, %f14, %f28;
	sub.f32 	%f65, %f64, %f54;
	add.f32 	%f66, %f65, %f65;
	mul.f32 	%f67, %f66, %f91;
	mul.f32 	%f68, %f3, %f10;
	mul.f32 	%f69, %f2, %f11;
	sub.f32 	%f70, %f69, %f68;
	mul.f32 	%f71, %f1, %f11;
	mul.f32 	%f72, %f3, %f9;
	sub.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f2, %f9;
	mul.f32 	%f75, %f1, %f10;
	sub.f32 	%f76, %f75, %f74;
	fma.rn.f32 	%f77, %f70, %f86, %f9;
	fma.rn.f32 	%f78, %f73, %f86, %f10;
	fma.rn.f32 	%f79, %f76, %f86, %f11;
	mul.f32 	%f80, %f53, %f77;
	mul.f32 	%f81, %f53, %f78;
	mul.f32 	%f82, %f53, %f79;
	sub.f32 	%f83, %f80, %f59;
	sub.f32 	%f84, %f81, %f63;
	sub.f32 	%f85, %f82, %f67;
	add.s64 	%rd48, %rd46, %rd20;
	st.global.f32 	[%rd48], %f83;
	add.s64 	%rd49, %rd45, %rd20;
	st.global.f32 	[%rd49], %f84;
	add.s64 	%rd50, %rd44, %rd20;
	st.global.f32 	[%rd50], %f85;

BB0_14:
	ret;
}


`
   lltorque2time_ptx_60 = `
.version 6.4
.target sm_60
.address_size 64

	// .globl	lltorque2time
.const .align 8 .f64 MUB = 0d3B266C5568970564;
.const .align 8 .f64 HBAR = 0d38E185A7054E4C91;
.const .align 8 .f64 GS = 0d4000000000000000;

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u64 lltorque2time_param_6,
	.param .u64 lltorque2time_param_7,
	.param .u64 lltorque2time_param_8,
	.param .u64 lltorque2time_param_9,
	.param .f32 lltorque2time_param_10,
	.param .f32 lltorque2time_param_11,
	.param .f32 lltorque2time_param_12,
	.param .f32 lltorque2time_param_13,
	.param .f32 lltorque2time_param_14,
	.param .u64 lltorque2time_param_15,
	.param .u64 lltorque2time_param_16,
	.param .u64 lltorque2time_param_17,
	.param .u64 lltorque2time_param_18,
	.param .u64 lltorque2time_param_19,
	.param .u64 lltorque2time_param_20,
	.param .u32 lltorque2time_param_21
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd4, [lltorque2time_param_0];
	ld.param.u64 	%rd5, [lltorque2time_param_1];
	ld.param.u64 	%rd6, [lltorque2time_param_2];
	ld.param.u64 	%rd7, [lltorque2time_param_3];
	ld.param.u64 	%rd8, [lltorque2time_param_4];
	ld.param.u64 	%rd9, [lltorque2time_param_5];
	ld.param.u64 	%rd10, [lltorque2time_param_6];
	ld.param.u64 	%rd11, [lltorque2time_param_7];
	ld.param.u64 	%rd12, [lltorque2time_param_8];
	ld.param.u64 	%rd13, [lltorque2time_param_9];
	ld.param.f32 	%f86, [lltorque2time_param_10];
	ld.param.f32 	%f26, [lltorque2time_param_11];
	ld.param.f32 	%f27, [lltorque2time_param_12];
	ld.param.f32 	%f28, [lltorque2time_param_13];
	ld.param.f32 	%f29, [lltorque2time_param_14];
	ld.param.u64 	%rd14, [lltorque2time_param_15];
	ld.param.u64 	%rd15, [lltorque2time_param_16];
	ld.param.u64 	%rd16, [lltorque2time_param_17];
	ld.param.u64 	%rd17, [lltorque2time_param_18];
	ld.param.u64 	%rd18, [lltorque2time_param_19];
	ld.param.u32 	%r8, [lltorque2time_param_21];
	mov.u32 	%r9, %nctaid.x;
	mov.u32 	%r10, %ctaid.y;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r1, %r12, %r13, %r14;
	setp.ge.s32	%p1, %r1, %r8;
	@%p1 bra 	BB0_14;

	cvta.to.global.u64 	%rd19, %rd7;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd20;
	ld.global.nc.f32 	%f2, [%rd23];
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd20;
	ld.global.nc.f32 	%f3, [%rd25];
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd20;
	ld.global.nc.f32 	%f4, [%rd27];
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd20;
	ld.global.nc.f32 	%f5, [%rd29];
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.nc.f32 	%f6, [%rd31];
	setp.eq.s64	%p2, %rd13, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd20;
	ld.global.nc.f32 	%f30, [%rd34];
	mul.f32 	%f86, %f30, %f86;

BB0_3:
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd35, %rd18;
	cvta.to.global.u64 	%rd36, %rd17;
	mul.f32 	%f32, %f3, %f5;
	mul.f32 	%f33, %f2, %f6;
	sub.f32 	%f9, %f33, %f32;
	mul.f32 	%f34, %f1, %f6;
	mul.f32 	%f35, %f3, %f4;
	sub.f32 	%f10, %f35, %f34;
	mul.f32 	%f36, %f2, %f4;
	mul.f32 	%f37, %f1, %f5;
	sub.f32 	%f11, %f37, %f36;
	fma.rn.f32 	%f12, %f86, %f86, 0f3F800000;
	add.s64 	%rd38, %rd35, %rd20;
	ld.global.nc.f32 	%f13, [%rd38];
	add.s64 	%rd39, %rd36, %rd20;
	ld.global.nc.f32 	%f14, [%rd39];
	mov.f32 	%f91, 0f00000000;
	setp.lt.s32	%p3, %r8, 1;
	@%p3 bra 	BB0_13;

	add.s64 	%rd41, %rd3, %rd20;
	ld.global.nc.f32 	%f41, [%rd41];
	add.s64 	%rd42, %rd2, %rd20;
	ld.global.nc.f32 	%f42, [%rd42];
	add.s64 	%rd43, %rd1, %rd20;
	ld.global.nc.f32 	%f43, [%rd43];
	mul.f32 	%f44, %f41, %f26;
	mul.f32 	%f45, %f42, %f26;
	mul.f32 	%f46, %f45, %f28;
	fma.rn.f32 	%f47, %f44, %f27, %f46;
	mul.f32 	%f48, %f43, %f26;
	fma.rn.f32 	%f15, %f48, %f29, %f47;
	and.b32  	%r18, %r8, 3;
	mov.f32 	%f91, 0f00000000;
	mov.u32 	%r20, 1;
	mov.u32 	%r22, 0;
	setp.eq.s32	%p4, %r18, 0;
	@%p4 bra 	BB0_11;

	setp.eq.s32	%p5, %r18, 1;
	@%p5 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r20, %r22;
	bra.uni 	BB0_10;

BB0_7:
	setp.eq.s32	%p6, %r18, 2;
	@%p6 bra 	BB0_9;

	add.f32 	%f91, %f15, 0f00000000;
	mov.u32 	%r20, 2;

BB0_9:
	add.f32 	%f91, %f15, %f91;

BB0_10:
	add.f32 	%f91, %f15, %f91;
	add.s32 	%r22, %r20, 1;

BB0_11:
	setp.lt.u32	%p7, %r8, 4;
	@%p7 bra 	BB0_13;

BB0_12:
	add.f32 	%f49, %f15, %f91;
	add.f32 	%f50, %f15, %f49;
	add.f32 	%f51, %f15, %f50;
	add.f32 	%f91, %f15, %f51;
	add.s32 	%r22, %r22, 4;
	setp.lt.s32	%p8, %r22, %r8;
	@%p8 bra 	BB0_12;

BB0_13:
	cvta.to.global.u64 	%rd44, %rd6;
	cvta.to.global.u64 	%rd45, %rd5;
	cvta.to.global.u64 	%rd46, %rd4;
	mov.f32 	%f52, 0fBF800000;
	div.rn.f32 	%f53, %f52, %f12;
	mul.f32 	%f54, %f13, %f27;
	mul.f32 	%f55, %f13, %f28;
	mul.f32 	%f56, %f13, %f29;
	sub.f32 	%f57, %f56, %f55;
	add.f32 	%f58, %f57, %f57;
	mul.f32 	%f59, %f58, %f91;
	mul.f32 	%f60, %f14, %f29;
	sub.f32 	%f61, %f54, %f60;
	add.f32 	%f62, %f61, %f61;
	mul.f32 	%f63, %f62, %f91;
	mul.f32 	%f64, %f14, %f28;
	sub.f32 	%f65, %f64, %f54;
	add.f32 	%f66, %f65, %f65;
	mul.f32 	%f67, %f66, %f91;
	mul.f32 	%f68, %f3, %f10;
	mul.f32 	%f69, %f2, %f11;
	sub.f32 	%f70, %f69, %f68;
	mul.f32 	%f71, %f1, %f11;
	mul.f32 	%f72, %f3, %f9;
	sub.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f2, %f9;
	mul.f32 	%f75, %f1, %f10;
	sub.f32 	%f76, %f75, %f74;
	fma.rn.f32 	%f77, %f70, %f86, %f9;
	fma.rn.f32 	%f78, %f73, %f86, %f10;
	fma.rn.f32 	%f79, %f76, %f86, %f11;
	mul.f32 	%f80, %f53, %f77;
	mul.f32 	%f81, %f53, %f78;
	mul.f32 	%f82, %f53, %f79;
	sub.f32 	%f83, %f80, %f59;
	sub.f32 	%f84, %f81, %f63;
	sub.f32 	%f85, %f82, %f67;
	add.s64 	%rd48, %rd46, %rd20;
	st.global.f32 	[%rd48], %f83;
	add.s64 	%rd49, %rd45, %rd20;
	st.global.f32 	[%rd49], %f84;
	add.s64 	%rd50, %rd44, %rd20;
	st.global.f32 	[%rd50], %f85;

BB0_14:
	ret;
}


`
   lltorque2time_ptx_61 = `
.version 6.4
.target sm_61
.address_size 64

	// .globl	lltorque2time
.const .align 8 .f64 MUB = 0d3B266C5568970564;
.const .align 8 .f64 HBAR = 0d38E185A7054E4C91;
.const .align 8 .f64 GS = 0d4000000000000000;

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u64 lltorque2time_param_6,
	.param .u64 lltorque2time_param_7,
	.param .u64 lltorque2time_param_8,
	.param .u64 lltorque2time_param_9,
	.param .f32 lltorque2time_param_10,
	.param .f32 lltorque2time_param_11,
	.param .f32 lltorque2time_param_12,
	.param .f32 lltorque2time_param_13,
	.param .f32 lltorque2time_param_14,
	.param .u64 lltorque2time_param_15,
	.param .u64 lltorque2time_param_16,
	.param .u64 lltorque2time_param_17,
	.param .u64 lltorque2time_param_18,
	.param .u64 lltorque2time_param_19,
	.param .u64 lltorque2time_param_20,
	.param .u32 lltorque2time_param_21
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd4, [lltorque2time_param_0];
	ld.param.u64 	%rd5, [lltorque2time_param_1];
	ld.param.u64 	%rd6, [lltorque2time_param_2];
	ld.param.u64 	%rd7, [lltorque2time_param_3];
	ld.param.u64 	%rd8, [lltorque2time_param_4];
	ld.param.u64 	%rd9, [lltorque2time_param_5];
	ld.param.u64 	%rd10, [lltorque2time_param_6];
	ld.param.u64 	%rd11, [lltorque2time_param_7];
	ld.param.u64 	%rd12, [lltorque2time_param_8];
	ld.param.u64 	%rd13, [lltorque2time_param_9];
	ld.param.f32 	%f86, [lltorque2time_param_10];
	ld.param.f32 	%f26, [lltorque2time_param_11];
	ld.param.f32 	%f27, [lltorque2time_param_12];
	ld.param.f32 	%f28, [lltorque2time_param_13];
	ld.param.f32 	%f29, [lltorque2time_param_14];
	ld.param.u64 	%rd14, [lltorque2time_param_15];
	ld.param.u64 	%rd15, [lltorque2time_param_16];
	ld.param.u64 	%rd16, [lltorque2time_param_17];
	ld.param.u64 	%rd17, [lltorque2time_param_18];
	ld.param.u64 	%rd18, [lltorque2time_param_19];
	ld.param.u32 	%r8, [lltorque2time_param_21];
	mov.u32 	%r9, %nctaid.x;
	mov.u32 	%r10, %ctaid.y;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r1, %r12, %r13, %r14;
	setp.ge.s32	%p1, %r1, %r8;
	@%p1 bra 	BB0_14;

	cvta.to.global.u64 	%rd19, %rd7;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd20;
	ld.global.nc.f32 	%f2, [%rd23];
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd20;
	ld.global.nc.f32 	%f3, [%rd25];
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd20;
	ld.global.nc.f32 	%f4, [%rd27];
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd20;
	ld.global.nc.f32 	%f5, [%rd29];
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.nc.f32 	%f6, [%rd31];
	setp.eq.s64	%p2, %rd13, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd20;
	ld.global.nc.f32 	%f30, [%rd34];
	mul.f32 	%f86, %f30, %f86;

BB0_3:
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd35, %rd18;
	cvta.to.global.u64 	%rd36, %rd17;
	mul.f32 	%f32, %f3, %f5;
	mul.f32 	%f33, %f2, %f6;
	sub.f32 	%f9, %f33, %f32;
	mul.f32 	%f34, %f1, %f6;
	mul.f32 	%f35, %f3, %f4;
	sub.f32 	%f10, %f35, %f34;
	mul.f32 	%f36, %f2, %f4;
	mul.f32 	%f37, %f1, %f5;
	sub.f32 	%f11, %f37, %f36;
	fma.rn.f32 	%f12, %f86, %f86, 0f3F800000;
	add.s64 	%rd38, %rd35, %rd20;
	ld.global.nc.f32 	%f13, [%rd38];
	add.s64 	%rd39, %rd36, %rd20;
	ld.global.nc.f32 	%f14, [%rd39];
	mov.f32 	%f91, 0f00000000;
	setp.lt.s32	%p3, %r8, 1;
	@%p3 bra 	BB0_13;

	add.s64 	%rd41, %rd3, %rd20;
	ld.global.nc.f32 	%f41, [%rd41];
	add.s64 	%rd42, %rd2, %rd20;
	ld.global.nc.f32 	%f42, [%rd42];
	add.s64 	%rd43, %rd1, %rd20;
	ld.global.nc.f32 	%f43, [%rd43];
	mul.f32 	%f44, %f41, %f26;
	mul.f32 	%f45, %f42, %f26;
	mul.f32 	%f46, %f45, %f28;
	fma.rn.f32 	%f47, %f44, %f27, %f46;
	mul.f32 	%f48, %f43, %f26;
	fma.rn.f32 	%f15, %f48, %f29, %f47;
	and.b32  	%r18, %r8, 3;
	mov.f32 	%f91, 0f00000000;
	mov.u32 	%r20, 1;
	mov.u32 	%r22, 0;
	setp.eq.s32	%p4, %r18, 0;
	@%p4 bra 	BB0_11;

	setp.eq.s32	%p5, %r18, 1;
	@%p5 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r20, %r22;
	bra.uni 	BB0_10;

BB0_7:
	setp.eq.s32	%p6, %r18, 2;
	@%p6 bra 	BB0_9;

	add.f32 	%f91, %f15, 0f00000000;
	mov.u32 	%r20, 2;

BB0_9:
	add.f32 	%f91, %f15, %f91;

BB0_10:
	add.f32 	%f91, %f15, %f91;
	add.s32 	%r22, %r20, 1;

BB0_11:
	setp.lt.u32	%p7, %r8, 4;
	@%p7 bra 	BB0_13;

BB0_12:
	add.f32 	%f49, %f15, %f91;
	add.f32 	%f50, %f15, %f49;
	add.f32 	%f51, %f15, %f50;
	add.f32 	%f91, %f15, %f51;
	add.s32 	%r22, %r22, 4;
	setp.lt.s32	%p8, %r22, %r8;
	@%p8 bra 	BB0_12;

BB0_13:
	cvta.to.global.u64 	%rd44, %rd6;
	cvta.to.global.u64 	%rd45, %rd5;
	cvta.to.global.u64 	%rd46, %rd4;
	mov.f32 	%f52, 0fBF800000;
	div.rn.f32 	%f53, %f52, %f12;
	mul.f32 	%f54, %f13, %f27;
	mul.f32 	%f55, %f13, %f28;
	mul.f32 	%f56, %f13, %f29;
	sub.f32 	%f57, %f56, %f55;
	add.f32 	%f58, %f57, %f57;
	mul.f32 	%f59, %f58, %f91;
	mul.f32 	%f60, %f14, %f29;
	sub.f32 	%f61, %f54, %f60;
	add.f32 	%f62, %f61, %f61;
	mul.f32 	%f63, %f62, %f91;
	mul.f32 	%f64, %f14, %f28;
	sub.f32 	%f65, %f64, %f54;
	add.f32 	%f66, %f65, %f65;
	mul.f32 	%f67, %f66, %f91;
	mul.f32 	%f68, %f3, %f10;
	mul.f32 	%f69, %f2, %f11;
	sub.f32 	%f70, %f69, %f68;
	mul.f32 	%f71, %f1, %f11;
	mul.f32 	%f72, %f3, %f9;
	sub.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f2, %f9;
	mul.f32 	%f75, %f1, %f10;
	sub.f32 	%f76, %f75, %f74;
	fma.rn.f32 	%f77, %f70, %f86, %f9;
	fma.rn.f32 	%f78, %f73, %f86, %f10;
	fma.rn.f32 	%f79, %f76, %f86, %f11;
	mul.f32 	%f80, %f53, %f77;
	mul.f32 	%f81, %f53, %f78;
	mul.f32 	%f82, %f53, %f79;
	sub.f32 	%f83, %f80, %f59;
	sub.f32 	%f84, %f81, %f63;
	sub.f32 	%f85, %f82, %f67;
	add.s64 	%rd48, %rd46, %rd20;
	st.global.f32 	[%rd48], %f83;
	add.s64 	%rd49, %rd45, %rd20;
	st.global.f32 	[%rd49], %f84;
	add.s64 	%rd50, %rd44, %rd20;
	st.global.f32 	[%rd50], %f85;

BB0_14:
	ret;
}


`
   lltorque2time_ptx_70 = `
.version 6.4
.target sm_70
.address_size 64

	// .globl	lltorque2time
.const .align 8 .f64 MUB = 0d3B266C5568970564;
.const .align 8 .f64 HBAR = 0d38E185A7054E4C91;
.const .align 8 .f64 GS = 0d4000000000000000;

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u64 lltorque2time_param_6,
	.param .u64 lltorque2time_param_7,
	.param .u64 lltorque2time_param_8,
	.param .u64 lltorque2time_param_9,
	.param .f32 lltorque2time_param_10,
	.param .f32 lltorque2time_param_11,
	.param .f32 lltorque2time_param_12,
	.param .f32 lltorque2time_param_13,
	.param .f32 lltorque2time_param_14,
	.param .u64 lltorque2time_param_15,
	.param .u64 lltorque2time_param_16,
	.param .u64 lltorque2time_param_17,
	.param .u64 lltorque2time_param_18,
	.param .u64 lltorque2time_param_19,
	.param .u64 lltorque2time_param_20,
	.param .u32 lltorque2time_param_21
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd4, [lltorque2time_param_0];
	ld.param.u64 	%rd5, [lltorque2time_param_1];
	ld.param.u64 	%rd6, [lltorque2time_param_2];
	ld.param.u64 	%rd7, [lltorque2time_param_3];
	ld.param.u64 	%rd8, [lltorque2time_param_4];
	ld.param.u64 	%rd9, [lltorque2time_param_5];
	ld.param.u64 	%rd10, [lltorque2time_param_6];
	ld.param.u64 	%rd11, [lltorque2time_param_7];
	ld.param.u64 	%rd12, [lltorque2time_param_8];
	ld.param.u64 	%rd13, [lltorque2time_param_9];
	ld.param.f32 	%f86, [lltorque2time_param_10];
	ld.param.f32 	%f26, [lltorque2time_param_11];
	ld.param.f32 	%f27, [lltorque2time_param_12];
	ld.param.f32 	%f28, [lltorque2time_param_13];
	ld.param.f32 	%f29, [lltorque2time_param_14];
	ld.param.u64 	%rd14, [lltorque2time_param_15];
	ld.param.u64 	%rd15, [lltorque2time_param_16];
	ld.param.u64 	%rd16, [lltorque2time_param_17];
	ld.param.u64 	%rd17, [lltorque2time_param_18];
	ld.param.u64 	%rd18, [lltorque2time_param_19];
	ld.param.u32 	%r8, [lltorque2time_param_21];
	mov.u32 	%r9, %nctaid.x;
	mov.u32 	%r10, %ctaid.y;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r1, %r12, %r13, %r14;
	setp.ge.s32	%p1, %r1, %r8;
	@%p1 bra 	BB0_14;

	cvta.to.global.u64 	%rd19, %rd7;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd20;
	ld.global.nc.f32 	%f2, [%rd23];
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd20;
	ld.global.nc.f32 	%f3, [%rd25];
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd20;
	ld.global.nc.f32 	%f4, [%rd27];
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd20;
	ld.global.nc.f32 	%f5, [%rd29];
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.nc.f32 	%f6, [%rd31];
	setp.eq.s64	%p2, %rd13, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd20;
	ld.global.nc.f32 	%f30, [%rd34];
	mul.f32 	%f86, %f30, %f86;

BB0_3:
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd35, %rd18;
	cvta.to.global.u64 	%rd36, %rd17;
	mul.f32 	%f32, %f3, %f5;
	mul.f32 	%f33, %f2, %f6;
	sub.f32 	%f9, %f33, %f32;
	mul.f32 	%f34, %f1, %f6;
	mul.f32 	%f35, %f3, %f4;
	sub.f32 	%f10, %f35, %f34;
	mul.f32 	%f36, %f2, %f4;
	mul.f32 	%f37, %f1, %f5;
	sub.f32 	%f11, %f37, %f36;
	fma.rn.f32 	%f12, %f86, %f86, 0f3F800000;
	add.s64 	%rd38, %rd35, %rd20;
	ld.global.nc.f32 	%f13, [%rd38];
	add.s64 	%rd39, %rd36, %rd20;
	ld.global.nc.f32 	%f14, [%rd39];
	mov.f32 	%f91, 0f00000000;
	setp.lt.s32	%p3, %r8, 1;
	@%p3 bra 	BB0_13;

	add.s64 	%rd41, %rd3, %rd20;
	ld.global.nc.f32 	%f41, [%rd41];
	add.s64 	%rd42, %rd2, %rd20;
	ld.global.nc.f32 	%f42, [%rd42];
	add.s64 	%rd43, %rd1, %rd20;
	ld.global.nc.f32 	%f43, [%rd43];
	mul.f32 	%f44, %f41, %f26;
	mul.f32 	%f45, %f42, %f26;
	mul.f32 	%f46, %f45, %f28;
	fma.rn.f32 	%f47, %f44, %f27, %f46;
	mul.f32 	%f48, %f43, %f26;
	fma.rn.f32 	%f15, %f48, %f29, %f47;
	and.b32  	%r18, %r8, 3;
	mov.f32 	%f91, 0f00000000;
	mov.u32 	%r20, 1;
	mov.u32 	%r22, 0;
	setp.eq.s32	%p4, %r18, 0;
	@%p4 bra 	BB0_11;

	setp.eq.s32	%p5, %r18, 1;
	@%p5 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r20, %r22;
	bra.uni 	BB0_10;

BB0_7:
	setp.eq.s32	%p6, %r18, 2;
	@%p6 bra 	BB0_9;

	add.f32 	%f91, %f15, 0f00000000;
	mov.u32 	%r20, 2;

BB0_9:
	add.f32 	%f91, %f15, %f91;

BB0_10:
	add.f32 	%f91, %f15, %f91;
	add.s32 	%r22, %r20, 1;

BB0_11:
	setp.lt.u32	%p7, %r8, 4;
	@%p7 bra 	BB0_13;

BB0_12:
	add.f32 	%f49, %f15, %f91;
	add.f32 	%f50, %f15, %f49;
	add.f32 	%f51, %f15, %f50;
	add.f32 	%f91, %f15, %f51;
	add.s32 	%r22, %r22, 4;
	setp.lt.s32	%p8, %r22, %r8;
	@%p8 bra 	BB0_12;

BB0_13:
	cvta.to.global.u64 	%rd44, %rd6;
	cvta.to.global.u64 	%rd45, %rd5;
	cvta.to.global.u64 	%rd46, %rd4;
	mov.f32 	%f52, 0fBF800000;
	div.rn.f32 	%f53, %f52, %f12;
	mul.f32 	%f54, %f13, %f27;
	mul.f32 	%f55, %f13, %f28;
	mul.f32 	%f56, %f13, %f29;
	sub.f32 	%f57, %f56, %f55;
	add.f32 	%f58, %f57, %f57;
	mul.f32 	%f59, %f58, %f91;
	mul.f32 	%f60, %f14, %f29;
	sub.f32 	%f61, %f54, %f60;
	add.f32 	%f62, %f61, %f61;
	mul.f32 	%f63, %f62, %f91;
	mul.f32 	%f64, %f14, %f28;
	sub.f32 	%f65, %f64, %f54;
	add.f32 	%f66, %f65, %f65;
	mul.f32 	%f67, %f66, %f91;
	mul.f32 	%f68, %f3, %f10;
	mul.f32 	%f69, %f2, %f11;
	sub.f32 	%f70, %f69, %f68;
	mul.f32 	%f71, %f1, %f11;
	mul.f32 	%f72, %f3, %f9;
	sub.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f2, %f9;
	mul.f32 	%f75, %f1, %f10;
	sub.f32 	%f76, %f75, %f74;
	fma.rn.f32 	%f77, %f70, %f86, %f9;
	fma.rn.f32 	%f78, %f73, %f86, %f10;
	fma.rn.f32 	%f79, %f76, %f86, %f11;
	mul.f32 	%f80, %f53, %f77;
	mul.f32 	%f81, %f53, %f78;
	mul.f32 	%f82, %f53, %f79;
	sub.f32 	%f83, %f80, %f59;
	sub.f32 	%f84, %f81, %f63;
	sub.f32 	%f85, %f82, %f67;
	add.s64 	%rd48, %rd46, %rd20;
	st.global.f32 	[%rd48], %f83;
	add.s64 	%rd49, %rd45, %rd20;
	st.global.f32 	[%rd49], %f84;
	add.s64 	%rd50, %rd44, %rd20;
	st.global.f32 	[%rd50], %f85;

BB0_14:
	ret;
}


`
   lltorque2time_ptx_75 = `
.version 6.4
.target sm_75
.address_size 64

	// .globl	lltorque2time
.const .align 8 .f64 MUB = 0d3B266C5568970564;
.const .align 8 .f64 HBAR = 0d38E185A7054E4C91;
.const .align 8 .f64 GS = 0d4000000000000000;

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u64 lltorque2time_param_6,
	.param .u64 lltorque2time_param_7,
	.param .u64 lltorque2time_param_8,
	.param .u64 lltorque2time_param_9,
	.param .f32 lltorque2time_param_10,
	.param .f32 lltorque2time_param_11,
	.param .f32 lltorque2time_param_12,
	.param .f32 lltorque2time_param_13,
	.param .f32 lltorque2time_param_14,
	.param .u64 lltorque2time_param_15,
	.param .u64 lltorque2time_param_16,
	.param .u64 lltorque2time_param_17,
	.param .u64 lltorque2time_param_18,
	.param .u64 lltorque2time_param_19,
	.param .u64 lltorque2time_param_20,
	.param .u32 lltorque2time_param_21
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd4, [lltorque2time_param_0];
	ld.param.u64 	%rd5, [lltorque2time_param_1];
	ld.param.u64 	%rd6, [lltorque2time_param_2];
	ld.param.u64 	%rd7, [lltorque2time_param_3];
	ld.param.u64 	%rd8, [lltorque2time_param_4];
	ld.param.u64 	%rd9, [lltorque2time_param_5];
	ld.param.u64 	%rd10, [lltorque2time_param_6];
	ld.param.u64 	%rd11, [lltorque2time_param_7];
	ld.param.u64 	%rd12, [lltorque2time_param_8];
	ld.param.u64 	%rd13, [lltorque2time_param_9];
	ld.param.f32 	%f86, [lltorque2time_param_10];
	ld.param.f32 	%f26, [lltorque2time_param_11];
	ld.param.f32 	%f27, [lltorque2time_param_12];
	ld.param.f32 	%f28, [lltorque2time_param_13];
	ld.param.f32 	%f29, [lltorque2time_param_14];
	ld.param.u64 	%rd14, [lltorque2time_param_15];
	ld.param.u64 	%rd15, [lltorque2time_param_16];
	ld.param.u64 	%rd16, [lltorque2time_param_17];
	ld.param.u64 	%rd17, [lltorque2time_param_18];
	ld.param.u64 	%rd18, [lltorque2time_param_19];
	ld.param.u32 	%r8, [lltorque2time_param_21];
	mov.u32 	%r9, %nctaid.x;
	mov.u32 	%r10, %ctaid.y;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r1, %r12, %r13, %r14;
	setp.ge.s32	%p1, %r1, %r8;
	@%p1 bra 	BB0_14;

	cvta.to.global.u64 	%rd19, %rd7;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd20;
	ld.global.nc.f32 	%f2, [%rd23];
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd20;
	ld.global.nc.f32 	%f3, [%rd25];
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd20;
	ld.global.nc.f32 	%f4, [%rd27];
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd20;
	ld.global.nc.f32 	%f5, [%rd29];
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.nc.f32 	%f6, [%rd31];
	setp.eq.s64	%p2, %rd13, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd20;
	ld.global.nc.f32 	%f30, [%rd34];
	mul.f32 	%f86, %f30, %f86;

BB0_3:
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd35, %rd18;
	cvta.to.global.u64 	%rd36, %rd17;
	mul.f32 	%f32, %f3, %f5;
	mul.f32 	%f33, %f2, %f6;
	sub.f32 	%f9, %f33, %f32;
	mul.f32 	%f34, %f1, %f6;
	mul.f32 	%f35, %f3, %f4;
	sub.f32 	%f10, %f35, %f34;
	mul.f32 	%f36, %f2, %f4;
	mul.f32 	%f37, %f1, %f5;
	sub.f32 	%f11, %f37, %f36;
	fma.rn.f32 	%f12, %f86, %f86, 0f3F800000;
	add.s64 	%rd38, %rd35, %rd20;
	ld.global.nc.f32 	%f13, [%rd38];
	add.s64 	%rd39, %rd36, %rd20;
	ld.global.nc.f32 	%f14, [%rd39];
	mov.f32 	%f91, 0f00000000;
	setp.lt.s32	%p3, %r8, 1;
	@%p3 bra 	BB0_13;

	add.s64 	%rd41, %rd3, %rd20;
	ld.global.nc.f32 	%f41, [%rd41];
	add.s64 	%rd42, %rd2, %rd20;
	ld.global.nc.f32 	%f42, [%rd42];
	add.s64 	%rd43, %rd1, %rd20;
	ld.global.nc.f32 	%f43, [%rd43];
	mul.f32 	%f44, %f41, %f26;
	mul.f32 	%f45, %f42, %f26;
	mul.f32 	%f46, %f45, %f28;
	fma.rn.f32 	%f47, %f44, %f27, %f46;
	mul.f32 	%f48, %f43, %f26;
	fma.rn.f32 	%f15, %f48, %f29, %f47;
	and.b32  	%r18, %r8, 3;
	mov.f32 	%f91, 0f00000000;
	mov.u32 	%r20, 1;
	mov.u32 	%r22, 0;
	setp.eq.s32	%p4, %r18, 0;
	@%p4 bra 	BB0_11;

	setp.eq.s32	%p5, %r18, 1;
	@%p5 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r20, %r22;
	bra.uni 	BB0_10;

BB0_7:
	setp.eq.s32	%p6, %r18, 2;
	@%p6 bra 	BB0_9;

	add.f32 	%f91, %f15, 0f00000000;
	mov.u32 	%r20, 2;

BB0_9:
	add.f32 	%f91, %f15, %f91;

BB0_10:
	add.f32 	%f91, %f15, %f91;
	add.s32 	%r22, %r20, 1;

BB0_11:
	setp.lt.u32	%p7, %r8, 4;
	@%p7 bra 	BB0_13;

BB0_12:
	add.f32 	%f49, %f15, %f91;
	add.f32 	%f50, %f15, %f49;
	add.f32 	%f51, %f15, %f50;
	add.f32 	%f91, %f15, %f51;
	add.s32 	%r22, %r22, 4;
	setp.lt.s32	%p8, %r22, %r8;
	@%p8 bra 	BB0_12;

BB0_13:
	cvta.to.global.u64 	%rd44, %rd6;
	cvta.to.global.u64 	%rd45, %rd5;
	cvta.to.global.u64 	%rd46, %rd4;
	mov.f32 	%f52, 0fBF800000;
	div.rn.f32 	%f53, %f52, %f12;
	mul.f32 	%f54, %f13, %f27;
	mul.f32 	%f55, %f13, %f28;
	mul.f32 	%f56, %f13, %f29;
	sub.f32 	%f57, %f56, %f55;
	add.f32 	%f58, %f57, %f57;
	mul.f32 	%f59, %f58, %f91;
	mul.f32 	%f60, %f14, %f29;
	sub.f32 	%f61, %f54, %f60;
	add.f32 	%f62, %f61, %f61;
	mul.f32 	%f63, %f62, %f91;
	mul.f32 	%f64, %f14, %f28;
	sub.f32 	%f65, %f64, %f54;
	add.f32 	%f66, %f65, %f65;
	mul.f32 	%f67, %f66, %f91;
	mul.f32 	%f68, %f3, %f10;
	mul.f32 	%f69, %f2, %f11;
	sub.f32 	%f70, %f69, %f68;
	mul.f32 	%f71, %f1, %f11;
	mul.f32 	%f72, %f3, %f9;
	sub.f32 	%f73, %f72, %f71;
	mul.f32 	%f74, %f2, %f9;
	mul.f32 	%f75, %f1, %f10;
	sub.f32 	%f76, %f75, %f74;
	fma.rn.f32 	%f77, %f70, %f86, %f9;
	fma.rn.f32 	%f78, %f73, %f86, %f10;
	fma.rn.f32 	%f79, %f76, %f86, %f11;
	mul.f32 	%f80, %f53, %f77;
	mul.f32 	%f81, %f53, %f78;
	mul.f32 	%f82, %f53, %f79;
	sub.f32 	%f83, %f80, %f59;
	sub.f32 	%f84, %f81, %f63;
	sub.f32 	%f85, %f82, %f67;
	add.s64 	%rd48, %rd46, %rd20;
	st.global.f32 	[%rd48], %f83;
	add.s64 	%rd49, %rd45, %rd20;
	st.global.f32 	[%rd49], %f84;
	add.s64 	%rd50, %rd44, %rd20;
	st.global.f32 	[%rd50], %f85;

BB0_14:
	ret;
}


`
 )
