package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for lltorque2time kernel
var lltorque2time_code cu.Function

// Stores the arguments for lltorque2time kernel invocation
type lltorque2time_args_t struct{
	 arg_tx unsafe.Pointer
	 arg_ty unsafe.Pointer
	 arg_tz unsafe.Pointer
	 arg_new_term_x unsafe.Pointer
	 arg_new_term_y unsafe.Pointer
	 arg_new_term_z unsafe.Pointer
	 arg_N int
	 argptr [7]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for lltorque2time kernel invocation
var lltorque2time_args lltorque2time_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 lltorque2time_args.argptr[0] = unsafe.Pointer(&lltorque2time_args.arg_tx)
	 lltorque2time_args.argptr[1] = unsafe.Pointer(&lltorque2time_args.arg_ty)
	 lltorque2time_args.argptr[2] = unsafe.Pointer(&lltorque2time_args.arg_tz)
	 lltorque2time_args.argptr[3] = unsafe.Pointer(&lltorque2time_args.arg_new_term_x)
	 lltorque2time_args.argptr[4] = unsafe.Pointer(&lltorque2time_args.arg_new_term_y)
	 lltorque2time_args.argptr[5] = unsafe.Pointer(&lltorque2time_args.arg_new_term_z)
	 lltorque2time_args.argptr[6] = unsafe.Pointer(&lltorque2time_args.arg_N)
	 }

// Wrapper for lltorque2time CUDA kernel, asynchronous.
func k_lltorque2time_async ( tx unsafe.Pointer, ty unsafe.Pointer, tz unsafe.Pointer, new_term_x unsafe.Pointer, new_term_y unsafe.Pointer, new_term_z unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("lltorque2time")
	}

	lltorque2time_args.Lock()
	defer lltorque2time_args.Unlock()

	if lltorque2time_code == 0{
		lltorque2time_code = fatbinLoad(lltorque2time_map, "lltorque2time")
	}

	 lltorque2time_args.arg_tx = tx
	 lltorque2time_args.arg_ty = ty
	 lltorque2time_args.arg_tz = tz
	 lltorque2time_args.arg_new_term_x = new_term_x
	 lltorque2time_args.arg_new_term_y = new_term_y
	 lltorque2time_args.arg_new_term_z = new_term_z
	 lltorque2time_args.arg_N = N
	

	args := lltorque2time_args.argptr[:]
	cu.LaunchKernel(lltorque2time_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("lltorque2time")
	}
}

// maps compute capability on PTX code for lltorque2time kernel.
var lltorque2time_map = map[int]string{ 0: "" ,
30: lltorque2time_ptx_30 ,
35: lltorque2time_ptx_35 ,
37: lltorque2time_ptx_37 ,
50: lltorque2time_ptx_50 ,
52: lltorque2time_ptx_52 ,
53: lltorque2time_ptx_53 ,
60: lltorque2time_ptx_60 ,
61: lltorque2time_ptx_61 ,
70: lltorque2time_ptx_70 ,
75: lltorque2time_ptx_75  }

// lltorque2time PTX code for various compute capabilities.
const(
  lltorque2time_ptx_30 = `
.version 6.4
.target sm_30
.address_size 64

	// .globl	lltorque2time

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u32 lltorque2time_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [lltorque2time_param_0];
	ld.param.u64 	%rd2, [lltorque2time_param_1];
	ld.param.u64 	%rd3, [lltorque2time_param_2];
	ld.param.u64 	%rd4, [lltorque2time_param_3];
	ld.param.u64 	%rd5, [lltorque2time_param_4];
	ld.param.u64 	%rd6, [lltorque2time_param_5];
	ld.param.u32 	%r2, [lltorque2time_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f1, [%rd11];
	ld.global.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	st.global.f32 	[%rd11], %f3;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	ld.global.f32 	%f4, [%rd15];
	ld.global.f32 	%f5, [%rd13];
	sub.f32 	%f6, %f4, %f5;
	st.global.f32 	[%rd15], %f6;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.f32 	%f7, [%rd19];
	ld.global.f32 	%f8, [%rd17];
	sub.f32 	%f9, %f7, %f8;
	st.global.f32 	[%rd19], %f9;

BB0_2:
	ret;
}


`
   lltorque2time_ptx_35 = `
.version 6.4
.target sm_35
.address_size 64

	// .globl	lltorque2time

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u32 lltorque2time_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [lltorque2time_param_0];
	ld.param.u64 	%rd2, [lltorque2time_param_1];
	ld.param.u64 	%rd3, [lltorque2time_param_2];
	ld.param.u64 	%rd4, [lltorque2time_param_3];
	ld.param.u64 	%rd5, [lltorque2time_param_4];
	ld.param.u64 	%rd6, [lltorque2time_param_5];
	ld.param.u32 	%r2, [lltorque2time_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f1, [%rd11];
	ld.global.nc.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	st.global.f32 	[%rd11], %f3;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	ld.global.f32 	%f4, [%rd15];
	ld.global.nc.f32 	%f5, [%rd13];
	sub.f32 	%f6, %f4, %f5;
	st.global.f32 	[%rd15], %f6;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.f32 	%f7, [%rd19];
	ld.global.nc.f32 	%f8, [%rd17];
	sub.f32 	%f9, %f7, %f8;
	st.global.f32 	[%rd19], %f9;

BB0_2:
	ret;
}


`
   lltorque2time_ptx_37 = `
.version 6.4
.target sm_37
.address_size 64

	// .globl	lltorque2time

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u32 lltorque2time_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [lltorque2time_param_0];
	ld.param.u64 	%rd2, [lltorque2time_param_1];
	ld.param.u64 	%rd3, [lltorque2time_param_2];
	ld.param.u64 	%rd4, [lltorque2time_param_3];
	ld.param.u64 	%rd5, [lltorque2time_param_4];
	ld.param.u64 	%rd6, [lltorque2time_param_5];
	ld.param.u32 	%r2, [lltorque2time_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f1, [%rd11];
	ld.global.nc.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	st.global.f32 	[%rd11], %f3;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	ld.global.f32 	%f4, [%rd15];
	ld.global.nc.f32 	%f5, [%rd13];
	sub.f32 	%f6, %f4, %f5;
	st.global.f32 	[%rd15], %f6;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.f32 	%f7, [%rd19];
	ld.global.nc.f32 	%f8, [%rd17];
	sub.f32 	%f9, %f7, %f8;
	st.global.f32 	[%rd19], %f9;

BB0_2:
	ret;
}


`
   lltorque2time_ptx_50 = `
.version 6.4
.target sm_50
.address_size 64

	// .globl	lltorque2time

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u32 lltorque2time_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [lltorque2time_param_0];
	ld.param.u64 	%rd2, [lltorque2time_param_1];
	ld.param.u64 	%rd3, [lltorque2time_param_2];
	ld.param.u64 	%rd4, [lltorque2time_param_3];
	ld.param.u64 	%rd5, [lltorque2time_param_4];
	ld.param.u64 	%rd6, [lltorque2time_param_5];
	ld.param.u32 	%r2, [lltorque2time_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f1, [%rd11];
	ld.global.nc.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	st.global.f32 	[%rd11], %f3;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	ld.global.f32 	%f4, [%rd15];
	ld.global.nc.f32 	%f5, [%rd13];
	sub.f32 	%f6, %f4, %f5;
	st.global.f32 	[%rd15], %f6;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.f32 	%f7, [%rd19];
	ld.global.nc.f32 	%f8, [%rd17];
	sub.f32 	%f9, %f7, %f8;
	st.global.f32 	[%rd19], %f9;

BB0_2:
	ret;
}


`
   lltorque2time_ptx_52 = `
.version 6.4
.target sm_52
.address_size 64

	// .globl	lltorque2time

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u32 lltorque2time_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [lltorque2time_param_0];
	ld.param.u64 	%rd2, [lltorque2time_param_1];
	ld.param.u64 	%rd3, [lltorque2time_param_2];
	ld.param.u64 	%rd4, [lltorque2time_param_3];
	ld.param.u64 	%rd5, [lltorque2time_param_4];
	ld.param.u64 	%rd6, [lltorque2time_param_5];
	ld.param.u32 	%r2, [lltorque2time_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f1, [%rd11];
	ld.global.nc.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	st.global.f32 	[%rd11], %f3;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	ld.global.f32 	%f4, [%rd15];
	ld.global.nc.f32 	%f5, [%rd13];
	sub.f32 	%f6, %f4, %f5;
	st.global.f32 	[%rd15], %f6;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.f32 	%f7, [%rd19];
	ld.global.nc.f32 	%f8, [%rd17];
	sub.f32 	%f9, %f7, %f8;
	st.global.f32 	[%rd19], %f9;

BB0_2:
	ret;
}


`
   lltorque2time_ptx_53 = `
.version 6.4
.target sm_53
.address_size 64

	// .globl	lltorque2time

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u32 lltorque2time_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [lltorque2time_param_0];
	ld.param.u64 	%rd2, [lltorque2time_param_1];
	ld.param.u64 	%rd3, [lltorque2time_param_2];
	ld.param.u64 	%rd4, [lltorque2time_param_3];
	ld.param.u64 	%rd5, [lltorque2time_param_4];
	ld.param.u64 	%rd6, [lltorque2time_param_5];
	ld.param.u32 	%r2, [lltorque2time_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f1, [%rd11];
	ld.global.nc.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	st.global.f32 	[%rd11], %f3;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	ld.global.f32 	%f4, [%rd15];
	ld.global.nc.f32 	%f5, [%rd13];
	sub.f32 	%f6, %f4, %f5;
	st.global.f32 	[%rd15], %f6;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.f32 	%f7, [%rd19];
	ld.global.nc.f32 	%f8, [%rd17];
	sub.f32 	%f9, %f7, %f8;
	st.global.f32 	[%rd19], %f9;

BB0_2:
	ret;
}


`
   lltorque2time_ptx_60 = `
.version 6.4
.target sm_60
.address_size 64

	// .globl	lltorque2time

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u32 lltorque2time_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [lltorque2time_param_0];
	ld.param.u64 	%rd2, [lltorque2time_param_1];
	ld.param.u64 	%rd3, [lltorque2time_param_2];
	ld.param.u64 	%rd4, [lltorque2time_param_3];
	ld.param.u64 	%rd5, [lltorque2time_param_4];
	ld.param.u64 	%rd6, [lltorque2time_param_5];
	ld.param.u32 	%r2, [lltorque2time_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f1, [%rd11];
	ld.global.nc.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	st.global.f32 	[%rd11], %f3;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	ld.global.f32 	%f4, [%rd15];
	ld.global.nc.f32 	%f5, [%rd13];
	sub.f32 	%f6, %f4, %f5;
	st.global.f32 	[%rd15], %f6;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.f32 	%f7, [%rd19];
	ld.global.nc.f32 	%f8, [%rd17];
	sub.f32 	%f9, %f7, %f8;
	st.global.f32 	[%rd19], %f9;

BB0_2:
	ret;
}


`
   lltorque2time_ptx_61 = `
.version 6.4
.target sm_61
.address_size 64

	// .globl	lltorque2time

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u32 lltorque2time_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [lltorque2time_param_0];
	ld.param.u64 	%rd2, [lltorque2time_param_1];
	ld.param.u64 	%rd3, [lltorque2time_param_2];
	ld.param.u64 	%rd4, [lltorque2time_param_3];
	ld.param.u64 	%rd5, [lltorque2time_param_4];
	ld.param.u64 	%rd6, [lltorque2time_param_5];
	ld.param.u32 	%r2, [lltorque2time_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f1, [%rd11];
	ld.global.nc.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	st.global.f32 	[%rd11], %f3;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	ld.global.f32 	%f4, [%rd15];
	ld.global.nc.f32 	%f5, [%rd13];
	sub.f32 	%f6, %f4, %f5;
	st.global.f32 	[%rd15], %f6;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.f32 	%f7, [%rd19];
	ld.global.nc.f32 	%f8, [%rd17];
	sub.f32 	%f9, %f7, %f8;
	st.global.f32 	[%rd19], %f9;

BB0_2:
	ret;
}


`
   lltorque2time_ptx_70 = `
.version 6.4
.target sm_70
.address_size 64

	// .globl	lltorque2time

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u32 lltorque2time_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [lltorque2time_param_0];
	ld.param.u64 	%rd2, [lltorque2time_param_1];
	ld.param.u64 	%rd3, [lltorque2time_param_2];
	ld.param.u64 	%rd4, [lltorque2time_param_3];
	ld.param.u64 	%rd5, [lltorque2time_param_4];
	ld.param.u64 	%rd6, [lltorque2time_param_5];
	ld.param.u32 	%r2, [lltorque2time_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f1, [%rd11];
	ld.global.nc.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	st.global.f32 	[%rd11], %f3;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	ld.global.f32 	%f4, [%rd15];
	ld.global.nc.f32 	%f5, [%rd13];
	sub.f32 	%f6, %f4, %f5;
	st.global.f32 	[%rd15], %f6;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.f32 	%f7, [%rd19];
	ld.global.nc.f32 	%f8, [%rd17];
	sub.f32 	%f9, %f7, %f8;
	st.global.f32 	[%rd19], %f9;

BB0_2:
	ret;
}


`
   lltorque2time_ptx_75 = `
.version 6.4
.target sm_75
.address_size 64

	// .globl	lltorque2time

.visible .entry lltorque2time(
	.param .u64 lltorque2time_param_0,
	.param .u64 lltorque2time_param_1,
	.param .u64 lltorque2time_param_2,
	.param .u64 lltorque2time_param_3,
	.param .u64 lltorque2time_param_4,
	.param .u64 lltorque2time_param_5,
	.param .u32 lltorque2time_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [lltorque2time_param_0];
	ld.param.u64 	%rd2, [lltorque2time_param_1];
	ld.param.u64 	%rd3, [lltorque2time_param_2];
	ld.param.u64 	%rd4, [lltorque2time_param_3];
	ld.param.u64 	%rd5, [lltorque2time_param_4];
	ld.param.u64 	%rd6, [lltorque2time_param_5];
	ld.param.u32 	%r2, [lltorque2time_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f1, [%rd11];
	ld.global.nc.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	st.global.f32 	[%rd11], %f3;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	ld.global.f32 	%f4, [%rd15];
	ld.global.nc.f32 	%f5, [%rd13];
	sub.f32 	%f6, %f4, %f5;
	st.global.f32 	[%rd15], %f6;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.f32 	%f7, [%rd19];
	ld.global.nc.f32 	%f8, [%rd17];
	sub.f32 	%f9, %f7, %f8;
	st.global.f32 	[%rd19], %f9;

BB0_2:
	ret;
}


`
 )
