package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for mdatatemp kernel
var mdatatemp_code cu.Function

// Stores the arguments for mdatatemp kernel invocation
type mdatatemp_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_mx_temp unsafe.Pointer
	 arg_my_temp unsafe.Pointer
	 arg_mz_temp unsafe.Pointer
	 arg_dt float32
	 arg_size_x int
	 arg_size_y int
	 arg_size_z int
	 arg_N int
	 argptr [9]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for mdatatemp kernel invocation
var mdatatemp_args mdatatemp_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 mdatatemp_args.argptr[0] = unsafe.Pointer(&mdatatemp_args.arg_dst)
	 mdatatemp_args.argptr[1] = unsafe.Pointer(&mdatatemp_args.arg_mx_temp)
	 mdatatemp_args.argptr[2] = unsafe.Pointer(&mdatatemp_args.arg_my_temp)
	 mdatatemp_args.argptr[3] = unsafe.Pointer(&mdatatemp_args.arg_mz_temp)
	 mdatatemp_args.argptr[4] = unsafe.Pointer(&mdatatemp_args.arg_dt)
	 mdatatemp_args.argptr[5] = unsafe.Pointer(&mdatatemp_args.arg_size_x)
	 mdatatemp_args.argptr[6] = unsafe.Pointer(&mdatatemp_args.arg_size_y)
	 mdatatemp_args.argptr[7] = unsafe.Pointer(&mdatatemp_args.arg_size_z)
	 mdatatemp_args.argptr[8] = unsafe.Pointer(&mdatatemp_args.arg_N)
	 }

// Wrapper for mdatatemp CUDA kernel, asynchronous.
func k_mdatatemp_async ( dst unsafe.Pointer, mx_temp unsafe.Pointer, my_temp unsafe.Pointer, mz_temp unsafe.Pointer, dt float32, size_x int, size_y int, size_z int, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("mdatatemp")
	}

	mdatatemp_args.Lock()
	defer mdatatemp_args.Unlock()

	if mdatatemp_code == 0{
		mdatatemp_code = fatbinLoad(mdatatemp_map, "mdatatemp")
	}

	 mdatatemp_args.arg_dst = dst
	 mdatatemp_args.arg_mx_temp = mx_temp
	 mdatatemp_args.arg_my_temp = my_temp
	 mdatatemp_args.arg_mz_temp = mz_temp
	 mdatatemp_args.arg_dt = dt
	 mdatatemp_args.arg_size_x = size_x
	 mdatatemp_args.arg_size_y = size_y
	 mdatatemp_args.arg_size_z = size_z
	 mdatatemp_args.arg_N = N
	

	args := mdatatemp_args.argptr[:]
	cu.LaunchKernel(mdatatemp_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("mdatatemp")
	}
}

// maps compute capability on PTX code for mdatatemp kernel.
var mdatatemp_map = map[int]string{ 0: "" ,
30: mdatatemp_ptx_30 ,
35: mdatatemp_ptx_35 ,
37: mdatatemp_ptx_37 ,
50: mdatatemp_ptx_50 ,
52: mdatatemp_ptx_52 ,
53: mdatatemp_ptx_53 ,
60: mdatatemp_ptx_60 ,
61: mdatatemp_ptx_61 ,
70: mdatatemp_ptx_70 ,
75: mdatatemp_ptx_75  }

// mdatatemp PTX code for various compute capabilities.
const(
  mdatatemp_ptx_30 = `
.version 6.4
.target sm_30
.address_size 64

	// .globl	mdatatemp

.visible .entry mdatatemp(
	.param .u64 mdatatemp_param_0,
	.param .u64 mdatatemp_param_1,
	.param .u64 mdatatemp_param_2,
	.param .u64 mdatatemp_param_3,
	.param .f32 mdatatemp_param_4,
	.param .u32 mdatatemp_param_5,
	.param .u32 mdatatemp_param_6,
	.param .u32 mdatatemp_param_7
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd4, [mdatatemp_param_0];
	ld.param.u32 	%r25, [mdatatemp_param_5];
	ld.param.u32 	%r26, [mdatatemp_param_6];
	ld.param.u32 	%r27, [mdatatemp_param_7];
	setp.lt.s32	%p1, %r27, 1;
	@%p1 bra 	BB0_17;

	mov.u32 	%r29, 0;
	mov.u32 	%r40, %r29;
	mov.u32 	%r53, %r29;

BB0_2:
	setp.lt.s32	%p2, %r26, 1;
	mov.u32 	%r42, %r29;
	@%p2 bra 	BB0_16;

BB0_3:
	setp.lt.s32	%p3, %r25, 1;
	@%p3 bra 	BB0_15;

	and.b32  	%r35, %r25, 3;
	mov.u32 	%r46, 1;
	mov.u32 	%r51, 0;
	setp.eq.s32	%p4, %r35, 0;
	@%p4 bra 	BB0_5;

	setp.eq.s32	%p5, %r35, 1;
	@%p5 bra 	BB0_7;
	bra.uni 	BB0_8;

BB0_7:
	mov.u32 	%r46, %r51;
	bra.uni 	BB0_11;

BB0_5:
	mov.u32 	%r49, %r53;
	mov.u32 	%r53, %r51;
	bra.uni 	BB0_12;

BB0_8:
	setp.eq.s32	%p6, %r35, 2;
	@%p6 bra 	BB0_10;

	cvt.rn.f32.s32	%f1, %r53;
	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r53, 4;
	add.s64 	%rd7, %rd5, %rd6;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r53, %r53, 1;
	mov.u32 	%r46, 2;

BB0_10:
	cvta.to.global.u64 	%rd8, %rd4;
	mul.wide.s32 	%rd9, %r53, 4;
	add.s64 	%rd10, %rd8, %rd9;
	cvt.rn.f32.s32	%f2, %r53;
	st.global.f32 	[%rd10], %f2;
	add.s32 	%r53, %r53, 1;

BB0_11:
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r53, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvt.rn.f32.s32	%f3, %r53;
	st.global.f32 	[%rd13], %f3;
	add.s32 	%r49, %r53, 1;
	add.s32 	%r51, %r46, 1;
	mov.u32 	%r53, %r49;

BB0_12:
	setp.lt.u32	%p7, %r25, 4;
	@%p7 bra 	BB0_15;

	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd14, %rd15;
	mov.u32 	%r53, %r49;

BB0_14:
	cvt.rn.f32.s32	%f4, %r53;
	st.global.f32 	[%rd16], %f4;
	add.s32 	%r37, %r53, 1;
	cvt.rn.f32.s32	%f5, %r37;
	st.global.f32 	[%rd16+4], %f5;
	add.s32 	%r38, %r53, 2;
	cvt.rn.f32.s32	%f6, %r38;
	st.global.f32 	[%rd16+8], %f6;
	add.s32 	%r39, %r53, 3;
	cvt.rn.f32.s32	%f7, %r39;
	st.global.f32 	[%rd16+12], %f7;
	add.s32 	%r53, %r53, 4;
	add.s64 	%rd16, %rd16, 16;
	add.s32 	%r51, %r51, 4;
	setp.lt.s32	%p8, %r51, %r25;
	@%p8 bra 	BB0_14;

BB0_15:
	add.s32 	%r42, %r42, 1;
	setp.lt.s32	%p9, %r42, %r26;
	@%p9 bra 	BB0_3;

BB0_16:
	add.s32 	%r40, %r40, 1;
	setp.lt.s32	%p10, %r40, %r27;
	@%p10 bra 	BB0_2;

BB0_17:
	ret;
}


`
   mdatatemp_ptx_35 = `
.version 6.4
.target sm_35
.address_size 64

	// .globl	mdatatemp

.visible .entry mdatatemp(
	.param .u64 mdatatemp_param_0,
	.param .u64 mdatatemp_param_1,
	.param .u64 mdatatemp_param_2,
	.param .u64 mdatatemp_param_3,
	.param .f32 mdatatemp_param_4,
	.param .u32 mdatatemp_param_5,
	.param .u32 mdatatemp_param_6,
	.param .u32 mdatatemp_param_7
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd4, [mdatatemp_param_0];
	ld.param.u32 	%r25, [mdatatemp_param_5];
	ld.param.u32 	%r26, [mdatatemp_param_6];
	ld.param.u32 	%r27, [mdatatemp_param_7];
	setp.lt.s32	%p1, %r27, 1;
	@%p1 bra 	BB0_17;

	mov.u32 	%r29, 0;
	mov.u32 	%r40, %r29;
	mov.u32 	%r53, %r29;

BB0_2:
	setp.lt.s32	%p2, %r26, 1;
	mov.u32 	%r42, %r29;
	@%p2 bra 	BB0_16;

BB0_3:
	setp.lt.s32	%p3, %r25, 1;
	@%p3 bra 	BB0_15;

	and.b32  	%r35, %r25, 3;
	mov.u32 	%r46, 1;
	mov.u32 	%r51, 0;
	setp.eq.s32	%p4, %r35, 0;
	@%p4 bra 	BB0_5;

	setp.eq.s32	%p5, %r35, 1;
	@%p5 bra 	BB0_7;
	bra.uni 	BB0_8;

BB0_7:
	mov.u32 	%r46, %r51;
	bra.uni 	BB0_11;

BB0_5:
	mov.u32 	%r49, %r53;
	mov.u32 	%r53, %r51;
	bra.uni 	BB0_12;

BB0_8:
	setp.eq.s32	%p6, %r35, 2;
	@%p6 bra 	BB0_10;

	cvt.rn.f32.s32	%f1, %r53;
	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r53, 4;
	add.s64 	%rd7, %rd5, %rd6;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r53, %r53, 1;
	mov.u32 	%r46, 2;

BB0_10:
	cvta.to.global.u64 	%rd8, %rd4;
	mul.wide.s32 	%rd9, %r53, 4;
	add.s64 	%rd10, %rd8, %rd9;
	cvt.rn.f32.s32	%f2, %r53;
	st.global.f32 	[%rd10], %f2;
	add.s32 	%r53, %r53, 1;

BB0_11:
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r53, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvt.rn.f32.s32	%f3, %r53;
	st.global.f32 	[%rd13], %f3;
	add.s32 	%r49, %r53, 1;
	add.s32 	%r51, %r46, 1;
	mov.u32 	%r53, %r49;

BB0_12:
	setp.lt.u32	%p7, %r25, 4;
	@%p7 bra 	BB0_15;

	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd14, %rd15;
	mov.u32 	%r53, %r49;

BB0_14:
	cvt.rn.f32.s32	%f4, %r53;
	st.global.f32 	[%rd16], %f4;
	add.s32 	%r37, %r53, 1;
	cvt.rn.f32.s32	%f5, %r37;
	st.global.f32 	[%rd16+4], %f5;
	add.s32 	%r38, %r53, 2;
	cvt.rn.f32.s32	%f6, %r38;
	st.global.f32 	[%rd16+8], %f6;
	add.s32 	%r39, %r53, 3;
	cvt.rn.f32.s32	%f7, %r39;
	st.global.f32 	[%rd16+12], %f7;
	add.s32 	%r53, %r53, 4;
	add.s64 	%rd16, %rd16, 16;
	add.s32 	%r51, %r51, 4;
	setp.lt.s32	%p8, %r51, %r25;
	@%p8 bra 	BB0_14;

BB0_15:
	add.s32 	%r42, %r42, 1;
	setp.lt.s32	%p9, %r42, %r26;
	@%p9 bra 	BB0_3;

BB0_16:
	add.s32 	%r40, %r40, 1;
	setp.lt.s32	%p10, %r40, %r27;
	@%p10 bra 	BB0_2;

BB0_17:
	ret;
}


`
   mdatatemp_ptx_37 = `
.version 6.4
.target sm_37
.address_size 64

	// .globl	mdatatemp

.visible .entry mdatatemp(
	.param .u64 mdatatemp_param_0,
	.param .u64 mdatatemp_param_1,
	.param .u64 mdatatemp_param_2,
	.param .u64 mdatatemp_param_3,
	.param .f32 mdatatemp_param_4,
	.param .u32 mdatatemp_param_5,
	.param .u32 mdatatemp_param_6,
	.param .u32 mdatatemp_param_7
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd4, [mdatatemp_param_0];
	ld.param.u32 	%r25, [mdatatemp_param_5];
	ld.param.u32 	%r26, [mdatatemp_param_6];
	ld.param.u32 	%r27, [mdatatemp_param_7];
	setp.lt.s32	%p1, %r27, 1;
	@%p1 bra 	BB0_17;

	mov.u32 	%r29, 0;
	mov.u32 	%r40, %r29;
	mov.u32 	%r53, %r29;

BB0_2:
	setp.lt.s32	%p2, %r26, 1;
	mov.u32 	%r42, %r29;
	@%p2 bra 	BB0_16;

BB0_3:
	setp.lt.s32	%p3, %r25, 1;
	@%p3 bra 	BB0_15;

	and.b32  	%r35, %r25, 3;
	mov.u32 	%r46, 1;
	mov.u32 	%r51, 0;
	setp.eq.s32	%p4, %r35, 0;
	@%p4 bra 	BB0_5;

	setp.eq.s32	%p5, %r35, 1;
	@%p5 bra 	BB0_7;
	bra.uni 	BB0_8;

BB0_7:
	mov.u32 	%r46, %r51;
	bra.uni 	BB0_11;

BB0_5:
	mov.u32 	%r49, %r53;
	mov.u32 	%r53, %r51;
	bra.uni 	BB0_12;

BB0_8:
	setp.eq.s32	%p6, %r35, 2;
	@%p6 bra 	BB0_10;

	cvt.rn.f32.s32	%f1, %r53;
	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r53, 4;
	add.s64 	%rd7, %rd5, %rd6;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r53, %r53, 1;
	mov.u32 	%r46, 2;

BB0_10:
	cvta.to.global.u64 	%rd8, %rd4;
	mul.wide.s32 	%rd9, %r53, 4;
	add.s64 	%rd10, %rd8, %rd9;
	cvt.rn.f32.s32	%f2, %r53;
	st.global.f32 	[%rd10], %f2;
	add.s32 	%r53, %r53, 1;

BB0_11:
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r53, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvt.rn.f32.s32	%f3, %r53;
	st.global.f32 	[%rd13], %f3;
	add.s32 	%r49, %r53, 1;
	add.s32 	%r51, %r46, 1;
	mov.u32 	%r53, %r49;

BB0_12:
	setp.lt.u32	%p7, %r25, 4;
	@%p7 bra 	BB0_15;

	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd14, %rd15;
	mov.u32 	%r53, %r49;

BB0_14:
	cvt.rn.f32.s32	%f4, %r53;
	st.global.f32 	[%rd16], %f4;
	add.s32 	%r37, %r53, 1;
	cvt.rn.f32.s32	%f5, %r37;
	st.global.f32 	[%rd16+4], %f5;
	add.s32 	%r38, %r53, 2;
	cvt.rn.f32.s32	%f6, %r38;
	st.global.f32 	[%rd16+8], %f6;
	add.s32 	%r39, %r53, 3;
	cvt.rn.f32.s32	%f7, %r39;
	st.global.f32 	[%rd16+12], %f7;
	add.s32 	%r53, %r53, 4;
	add.s64 	%rd16, %rd16, 16;
	add.s32 	%r51, %r51, 4;
	setp.lt.s32	%p8, %r51, %r25;
	@%p8 bra 	BB0_14;

BB0_15:
	add.s32 	%r42, %r42, 1;
	setp.lt.s32	%p9, %r42, %r26;
	@%p9 bra 	BB0_3;

BB0_16:
	add.s32 	%r40, %r40, 1;
	setp.lt.s32	%p10, %r40, %r27;
	@%p10 bra 	BB0_2;

BB0_17:
	ret;
}


`
   mdatatemp_ptx_50 = `
.version 6.4
.target sm_50
.address_size 64

	// .globl	mdatatemp

.visible .entry mdatatemp(
	.param .u64 mdatatemp_param_0,
	.param .u64 mdatatemp_param_1,
	.param .u64 mdatatemp_param_2,
	.param .u64 mdatatemp_param_3,
	.param .f32 mdatatemp_param_4,
	.param .u32 mdatatemp_param_5,
	.param .u32 mdatatemp_param_6,
	.param .u32 mdatatemp_param_7
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd4, [mdatatemp_param_0];
	ld.param.u32 	%r25, [mdatatemp_param_5];
	ld.param.u32 	%r26, [mdatatemp_param_6];
	ld.param.u32 	%r27, [mdatatemp_param_7];
	setp.lt.s32	%p1, %r27, 1;
	@%p1 bra 	BB0_17;

	mov.u32 	%r29, 0;
	mov.u32 	%r40, %r29;
	mov.u32 	%r53, %r29;

BB0_2:
	setp.lt.s32	%p2, %r26, 1;
	mov.u32 	%r42, %r29;
	@%p2 bra 	BB0_16;

BB0_3:
	setp.lt.s32	%p3, %r25, 1;
	@%p3 bra 	BB0_15;

	and.b32  	%r35, %r25, 3;
	mov.u32 	%r46, 1;
	mov.u32 	%r51, 0;
	setp.eq.s32	%p4, %r35, 0;
	@%p4 bra 	BB0_5;

	setp.eq.s32	%p5, %r35, 1;
	@%p5 bra 	BB0_7;
	bra.uni 	BB0_8;

BB0_7:
	mov.u32 	%r46, %r51;
	bra.uni 	BB0_11;

BB0_5:
	mov.u32 	%r49, %r53;
	mov.u32 	%r53, %r51;
	bra.uni 	BB0_12;

BB0_8:
	setp.eq.s32	%p6, %r35, 2;
	@%p6 bra 	BB0_10;

	cvt.rn.f32.s32	%f1, %r53;
	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r53, 4;
	add.s64 	%rd7, %rd5, %rd6;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r53, %r53, 1;
	mov.u32 	%r46, 2;

BB0_10:
	cvta.to.global.u64 	%rd8, %rd4;
	mul.wide.s32 	%rd9, %r53, 4;
	add.s64 	%rd10, %rd8, %rd9;
	cvt.rn.f32.s32	%f2, %r53;
	st.global.f32 	[%rd10], %f2;
	add.s32 	%r53, %r53, 1;

BB0_11:
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r53, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvt.rn.f32.s32	%f3, %r53;
	st.global.f32 	[%rd13], %f3;
	add.s32 	%r49, %r53, 1;
	add.s32 	%r51, %r46, 1;
	mov.u32 	%r53, %r49;

BB0_12:
	setp.lt.u32	%p7, %r25, 4;
	@%p7 bra 	BB0_15;

	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd14, %rd15;
	mov.u32 	%r53, %r49;

BB0_14:
	cvt.rn.f32.s32	%f4, %r53;
	st.global.f32 	[%rd16], %f4;
	add.s32 	%r37, %r53, 1;
	cvt.rn.f32.s32	%f5, %r37;
	st.global.f32 	[%rd16+4], %f5;
	add.s32 	%r38, %r53, 2;
	cvt.rn.f32.s32	%f6, %r38;
	st.global.f32 	[%rd16+8], %f6;
	add.s32 	%r39, %r53, 3;
	cvt.rn.f32.s32	%f7, %r39;
	st.global.f32 	[%rd16+12], %f7;
	add.s32 	%r53, %r53, 4;
	add.s64 	%rd16, %rd16, 16;
	add.s32 	%r51, %r51, 4;
	setp.lt.s32	%p8, %r51, %r25;
	@%p8 bra 	BB0_14;

BB0_15:
	add.s32 	%r42, %r42, 1;
	setp.lt.s32	%p9, %r42, %r26;
	@%p9 bra 	BB0_3;

BB0_16:
	add.s32 	%r40, %r40, 1;
	setp.lt.s32	%p10, %r40, %r27;
	@%p10 bra 	BB0_2;

BB0_17:
	ret;
}


`
   mdatatemp_ptx_52 = `
.version 6.4
.target sm_52
.address_size 64

	// .globl	mdatatemp

.visible .entry mdatatemp(
	.param .u64 mdatatemp_param_0,
	.param .u64 mdatatemp_param_1,
	.param .u64 mdatatemp_param_2,
	.param .u64 mdatatemp_param_3,
	.param .f32 mdatatemp_param_4,
	.param .u32 mdatatemp_param_5,
	.param .u32 mdatatemp_param_6,
	.param .u32 mdatatemp_param_7
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd4, [mdatatemp_param_0];
	ld.param.u32 	%r25, [mdatatemp_param_5];
	ld.param.u32 	%r26, [mdatatemp_param_6];
	ld.param.u32 	%r27, [mdatatemp_param_7];
	setp.lt.s32	%p1, %r27, 1;
	@%p1 bra 	BB0_17;

	mov.u32 	%r29, 0;
	mov.u32 	%r40, %r29;
	mov.u32 	%r53, %r29;

BB0_2:
	setp.lt.s32	%p2, %r26, 1;
	mov.u32 	%r42, %r29;
	@%p2 bra 	BB0_16;

BB0_3:
	setp.lt.s32	%p3, %r25, 1;
	@%p3 bra 	BB0_15;

	and.b32  	%r35, %r25, 3;
	mov.u32 	%r46, 1;
	mov.u32 	%r51, 0;
	setp.eq.s32	%p4, %r35, 0;
	@%p4 bra 	BB0_5;

	setp.eq.s32	%p5, %r35, 1;
	@%p5 bra 	BB0_7;
	bra.uni 	BB0_8;

BB0_7:
	mov.u32 	%r46, %r51;
	bra.uni 	BB0_11;

BB0_5:
	mov.u32 	%r49, %r53;
	mov.u32 	%r53, %r51;
	bra.uni 	BB0_12;

BB0_8:
	setp.eq.s32	%p6, %r35, 2;
	@%p6 bra 	BB0_10;

	cvt.rn.f32.s32	%f1, %r53;
	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r53, 4;
	add.s64 	%rd7, %rd5, %rd6;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r53, %r53, 1;
	mov.u32 	%r46, 2;

BB0_10:
	cvta.to.global.u64 	%rd8, %rd4;
	mul.wide.s32 	%rd9, %r53, 4;
	add.s64 	%rd10, %rd8, %rd9;
	cvt.rn.f32.s32	%f2, %r53;
	st.global.f32 	[%rd10], %f2;
	add.s32 	%r53, %r53, 1;

BB0_11:
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r53, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvt.rn.f32.s32	%f3, %r53;
	st.global.f32 	[%rd13], %f3;
	add.s32 	%r49, %r53, 1;
	add.s32 	%r51, %r46, 1;
	mov.u32 	%r53, %r49;

BB0_12:
	setp.lt.u32	%p7, %r25, 4;
	@%p7 bra 	BB0_15;

	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd14, %rd15;
	mov.u32 	%r53, %r49;

BB0_14:
	cvt.rn.f32.s32	%f4, %r53;
	st.global.f32 	[%rd16], %f4;
	add.s32 	%r37, %r53, 1;
	cvt.rn.f32.s32	%f5, %r37;
	st.global.f32 	[%rd16+4], %f5;
	add.s32 	%r38, %r53, 2;
	cvt.rn.f32.s32	%f6, %r38;
	st.global.f32 	[%rd16+8], %f6;
	add.s32 	%r39, %r53, 3;
	cvt.rn.f32.s32	%f7, %r39;
	st.global.f32 	[%rd16+12], %f7;
	add.s32 	%r53, %r53, 4;
	add.s64 	%rd16, %rd16, 16;
	add.s32 	%r51, %r51, 4;
	setp.lt.s32	%p8, %r51, %r25;
	@%p8 bra 	BB0_14;

BB0_15:
	add.s32 	%r42, %r42, 1;
	setp.lt.s32	%p9, %r42, %r26;
	@%p9 bra 	BB0_3;

BB0_16:
	add.s32 	%r40, %r40, 1;
	setp.lt.s32	%p10, %r40, %r27;
	@%p10 bra 	BB0_2;

BB0_17:
	ret;
}


`
   mdatatemp_ptx_53 = `
.version 6.4
.target sm_53
.address_size 64

	// .globl	mdatatemp

.visible .entry mdatatemp(
	.param .u64 mdatatemp_param_0,
	.param .u64 mdatatemp_param_1,
	.param .u64 mdatatemp_param_2,
	.param .u64 mdatatemp_param_3,
	.param .f32 mdatatemp_param_4,
	.param .u32 mdatatemp_param_5,
	.param .u32 mdatatemp_param_6,
	.param .u32 mdatatemp_param_7
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd4, [mdatatemp_param_0];
	ld.param.u32 	%r25, [mdatatemp_param_5];
	ld.param.u32 	%r26, [mdatatemp_param_6];
	ld.param.u32 	%r27, [mdatatemp_param_7];
	setp.lt.s32	%p1, %r27, 1;
	@%p1 bra 	BB0_17;

	mov.u32 	%r29, 0;
	mov.u32 	%r40, %r29;
	mov.u32 	%r53, %r29;

BB0_2:
	setp.lt.s32	%p2, %r26, 1;
	mov.u32 	%r42, %r29;
	@%p2 bra 	BB0_16;

BB0_3:
	setp.lt.s32	%p3, %r25, 1;
	@%p3 bra 	BB0_15;

	and.b32  	%r35, %r25, 3;
	mov.u32 	%r46, 1;
	mov.u32 	%r51, 0;
	setp.eq.s32	%p4, %r35, 0;
	@%p4 bra 	BB0_5;

	setp.eq.s32	%p5, %r35, 1;
	@%p5 bra 	BB0_7;
	bra.uni 	BB0_8;

BB0_7:
	mov.u32 	%r46, %r51;
	bra.uni 	BB0_11;

BB0_5:
	mov.u32 	%r49, %r53;
	mov.u32 	%r53, %r51;
	bra.uni 	BB0_12;

BB0_8:
	setp.eq.s32	%p6, %r35, 2;
	@%p6 bra 	BB0_10;

	cvt.rn.f32.s32	%f1, %r53;
	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r53, 4;
	add.s64 	%rd7, %rd5, %rd6;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r53, %r53, 1;
	mov.u32 	%r46, 2;

BB0_10:
	cvta.to.global.u64 	%rd8, %rd4;
	mul.wide.s32 	%rd9, %r53, 4;
	add.s64 	%rd10, %rd8, %rd9;
	cvt.rn.f32.s32	%f2, %r53;
	st.global.f32 	[%rd10], %f2;
	add.s32 	%r53, %r53, 1;

BB0_11:
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r53, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvt.rn.f32.s32	%f3, %r53;
	st.global.f32 	[%rd13], %f3;
	add.s32 	%r49, %r53, 1;
	add.s32 	%r51, %r46, 1;
	mov.u32 	%r53, %r49;

BB0_12:
	setp.lt.u32	%p7, %r25, 4;
	@%p7 bra 	BB0_15;

	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd14, %rd15;
	mov.u32 	%r53, %r49;

BB0_14:
	cvt.rn.f32.s32	%f4, %r53;
	st.global.f32 	[%rd16], %f4;
	add.s32 	%r37, %r53, 1;
	cvt.rn.f32.s32	%f5, %r37;
	st.global.f32 	[%rd16+4], %f5;
	add.s32 	%r38, %r53, 2;
	cvt.rn.f32.s32	%f6, %r38;
	st.global.f32 	[%rd16+8], %f6;
	add.s32 	%r39, %r53, 3;
	cvt.rn.f32.s32	%f7, %r39;
	st.global.f32 	[%rd16+12], %f7;
	add.s32 	%r53, %r53, 4;
	add.s64 	%rd16, %rd16, 16;
	add.s32 	%r51, %r51, 4;
	setp.lt.s32	%p8, %r51, %r25;
	@%p8 bra 	BB0_14;

BB0_15:
	add.s32 	%r42, %r42, 1;
	setp.lt.s32	%p9, %r42, %r26;
	@%p9 bra 	BB0_3;

BB0_16:
	add.s32 	%r40, %r40, 1;
	setp.lt.s32	%p10, %r40, %r27;
	@%p10 bra 	BB0_2;

BB0_17:
	ret;
}


`
   mdatatemp_ptx_60 = `
.version 6.4
.target sm_60
.address_size 64

	// .globl	mdatatemp

.visible .entry mdatatemp(
	.param .u64 mdatatemp_param_0,
	.param .u64 mdatatemp_param_1,
	.param .u64 mdatatemp_param_2,
	.param .u64 mdatatemp_param_3,
	.param .f32 mdatatemp_param_4,
	.param .u32 mdatatemp_param_5,
	.param .u32 mdatatemp_param_6,
	.param .u32 mdatatemp_param_7
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd4, [mdatatemp_param_0];
	ld.param.u32 	%r25, [mdatatemp_param_5];
	ld.param.u32 	%r26, [mdatatemp_param_6];
	ld.param.u32 	%r27, [mdatatemp_param_7];
	setp.lt.s32	%p1, %r27, 1;
	@%p1 bra 	BB0_17;

	mov.u32 	%r29, 0;
	mov.u32 	%r40, %r29;
	mov.u32 	%r53, %r29;

BB0_2:
	setp.lt.s32	%p2, %r26, 1;
	mov.u32 	%r42, %r29;
	@%p2 bra 	BB0_16;

BB0_3:
	setp.lt.s32	%p3, %r25, 1;
	@%p3 bra 	BB0_15;

	and.b32  	%r35, %r25, 3;
	mov.u32 	%r46, 1;
	mov.u32 	%r51, 0;
	setp.eq.s32	%p4, %r35, 0;
	@%p4 bra 	BB0_5;

	setp.eq.s32	%p5, %r35, 1;
	@%p5 bra 	BB0_7;
	bra.uni 	BB0_8;

BB0_7:
	mov.u32 	%r46, %r51;
	bra.uni 	BB0_11;

BB0_5:
	mov.u32 	%r49, %r53;
	mov.u32 	%r53, %r51;
	bra.uni 	BB0_12;

BB0_8:
	setp.eq.s32	%p6, %r35, 2;
	@%p6 bra 	BB0_10;

	cvt.rn.f32.s32	%f1, %r53;
	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r53, 4;
	add.s64 	%rd7, %rd5, %rd6;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r53, %r53, 1;
	mov.u32 	%r46, 2;

BB0_10:
	cvta.to.global.u64 	%rd8, %rd4;
	mul.wide.s32 	%rd9, %r53, 4;
	add.s64 	%rd10, %rd8, %rd9;
	cvt.rn.f32.s32	%f2, %r53;
	st.global.f32 	[%rd10], %f2;
	add.s32 	%r53, %r53, 1;

BB0_11:
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r53, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvt.rn.f32.s32	%f3, %r53;
	st.global.f32 	[%rd13], %f3;
	add.s32 	%r49, %r53, 1;
	add.s32 	%r51, %r46, 1;
	mov.u32 	%r53, %r49;

BB0_12:
	setp.lt.u32	%p7, %r25, 4;
	@%p7 bra 	BB0_15;

	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd14, %rd15;
	mov.u32 	%r53, %r49;

BB0_14:
	cvt.rn.f32.s32	%f4, %r53;
	st.global.f32 	[%rd16], %f4;
	add.s32 	%r37, %r53, 1;
	cvt.rn.f32.s32	%f5, %r37;
	st.global.f32 	[%rd16+4], %f5;
	add.s32 	%r38, %r53, 2;
	cvt.rn.f32.s32	%f6, %r38;
	st.global.f32 	[%rd16+8], %f6;
	add.s32 	%r39, %r53, 3;
	cvt.rn.f32.s32	%f7, %r39;
	st.global.f32 	[%rd16+12], %f7;
	add.s32 	%r53, %r53, 4;
	add.s64 	%rd16, %rd16, 16;
	add.s32 	%r51, %r51, 4;
	setp.lt.s32	%p8, %r51, %r25;
	@%p8 bra 	BB0_14;

BB0_15:
	add.s32 	%r42, %r42, 1;
	setp.lt.s32	%p9, %r42, %r26;
	@%p9 bra 	BB0_3;

BB0_16:
	add.s32 	%r40, %r40, 1;
	setp.lt.s32	%p10, %r40, %r27;
	@%p10 bra 	BB0_2;

BB0_17:
	ret;
}


`
   mdatatemp_ptx_61 = `
.version 6.4
.target sm_61
.address_size 64

	// .globl	mdatatemp

.visible .entry mdatatemp(
	.param .u64 mdatatemp_param_0,
	.param .u64 mdatatemp_param_1,
	.param .u64 mdatatemp_param_2,
	.param .u64 mdatatemp_param_3,
	.param .f32 mdatatemp_param_4,
	.param .u32 mdatatemp_param_5,
	.param .u32 mdatatemp_param_6,
	.param .u32 mdatatemp_param_7
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd4, [mdatatemp_param_0];
	ld.param.u32 	%r25, [mdatatemp_param_5];
	ld.param.u32 	%r26, [mdatatemp_param_6];
	ld.param.u32 	%r27, [mdatatemp_param_7];
	setp.lt.s32	%p1, %r27, 1;
	@%p1 bra 	BB0_17;

	mov.u32 	%r29, 0;
	mov.u32 	%r40, %r29;
	mov.u32 	%r53, %r29;

BB0_2:
	setp.lt.s32	%p2, %r26, 1;
	mov.u32 	%r42, %r29;
	@%p2 bra 	BB0_16;

BB0_3:
	setp.lt.s32	%p3, %r25, 1;
	@%p3 bra 	BB0_15;

	and.b32  	%r35, %r25, 3;
	mov.u32 	%r46, 1;
	mov.u32 	%r51, 0;
	setp.eq.s32	%p4, %r35, 0;
	@%p4 bra 	BB0_5;

	setp.eq.s32	%p5, %r35, 1;
	@%p5 bra 	BB0_7;
	bra.uni 	BB0_8;

BB0_7:
	mov.u32 	%r46, %r51;
	bra.uni 	BB0_11;

BB0_5:
	mov.u32 	%r49, %r53;
	mov.u32 	%r53, %r51;
	bra.uni 	BB0_12;

BB0_8:
	setp.eq.s32	%p6, %r35, 2;
	@%p6 bra 	BB0_10;

	cvt.rn.f32.s32	%f1, %r53;
	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r53, 4;
	add.s64 	%rd7, %rd5, %rd6;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r53, %r53, 1;
	mov.u32 	%r46, 2;

BB0_10:
	cvta.to.global.u64 	%rd8, %rd4;
	mul.wide.s32 	%rd9, %r53, 4;
	add.s64 	%rd10, %rd8, %rd9;
	cvt.rn.f32.s32	%f2, %r53;
	st.global.f32 	[%rd10], %f2;
	add.s32 	%r53, %r53, 1;

BB0_11:
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r53, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvt.rn.f32.s32	%f3, %r53;
	st.global.f32 	[%rd13], %f3;
	add.s32 	%r49, %r53, 1;
	add.s32 	%r51, %r46, 1;
	mov.u32 	%r53, %r49;

BB0_12:
	setp.lt.u32	%p7, %r25, 4;
	@%p7 bra 	BB0_15;

	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd14, %rd15;
	mov.u32 	%r53, %r49;

BB0_14:
	cvt.rn.f32.s32	%f4, %r53;
	st.global.f32 	[%rd16], %f4;
	add.s32 	%r37, %r53, 1;
	cvt.rn.f32.s32	%f5, %r37;
	st.global.f32 	[%rd16+4], %f5;
	add.s32 	%r38, %r53, 2;
	cvt.rn.f32.s32	%f6, %r38;
	st.global.f32 	[%rd16+8], %f6;
	add.s32 	%r39, %r53, 3;
	cvt.rn.f32.s32	%f7, %r39;
	st.global.f32 	[%rd16+12], %f7;
	add.s32 	%r53, %r53, 4;
	add.s64 	%rd16, %rd16, 16;
	add.s32 	%r51, %r51, 4;
	setp.lt.s32	%p8, %r51, %r25;
	@%p8 bra 	BB0_14;

BB0_15:
	add.s32 	%r42, %r42, 1;
	setp.lt.s32	%p9, %r42, %r26;
	@%p9 bra 	BB0_3;

BB0_16:
	add.s32 	%r40, %r40, 1;
	setp.lt.s32	%p10, %r40, %r27;
	@%p10 bra 	BB0_2;

BB0_17:
	ret;
}


`
   mdatatemp_ptx_70 = `
.version 6.4
.target sm_70
.address_size 64

	// .globl	mdatatemp

.visible .entry mdatatemp(
	.param .u64 mdatatemp_param_0,
	.param .u64 mdatatemp_param_1,
	.param .u64 mdatatemp_param_2,
	.param .u64 mdatatemp_param_3,
	.param .f32 mdatatemp_param_4,
	.param .u32 mdatatemp_param_5,
	.param .u32 mdatatemp_param_6,
	.param .u32 mdatatemp_param_7
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd4, [mdatatemp_param_0];
	ld.param.u32 	%r25, [mdatatemp_param_5];
	ld.param.u32 	%r26, [mdatatemp_param_6];
	ld.param.u32 	%r27, [mdatatemp_param_7];
	setp.lt.s32	%p1, %r27, 1;
	@%p1 bra 	BB0_17;

	mov.u32 	%r29, 0;
	mov.u32 	%r40, %r29;
	mov.u32 	%r53, %r29;

BB0_2:
	setp.lt.s32	%p2, %r26, 1;
	mov.u32 	%r42, %r29;
	@%p2 bra 	BB0_16;

BB0_3:
	setp.lt.s32	%p3, %r25, 1;
	@%p3 bra 	BB0_15;

	and.b32  	%r35, %r25, 3;
	mov.u32 	%r46, 1;
	mov.u32 	%r51, 0;
	setp.eq.s32	%p4, %r35, 0;
	@%p4 bra 	BB0_5;

	setp.eq.s32	%p5, %r35, 1;
	@%p5 bra 	BB0_7;
	bra.uni 	BB0_8;

BB0_7:
	mov.u32 	%r46, %r51;
	bra.uni 	BB0_11;

BB0_5:
	mov.u32 	%r49, %r53;
	mov.u32 	%r53, %r51;
	bra.uni 	BB0_12;

BB0_8:
	setp.eq.s32	%p6, %r35, 2;
	@%p6 bra 	BB0_10;

	cvt.rn.f32.s32	%f1, %r53;
	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r53, 4;
	add.s64 	%rd7, %rd5, %rd6;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r53, %r53, 1;
	mov.u32 	%r46, 2;

BB0_10:
	cvta.to.global.u64 	%rd8, %rd4;
	mul.wide.s32 	%rd9, %r53, 4;
	add.s64 	%rd10, %rd8, %rd9;
	cvt.rn.f32.s32	%f2, %r53;
	st.global.f32 	[%rd10], %f2;
	add.s32 	%r53, %r53, 1;

BB0_11:
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r53, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvt.rn.f32.s32	%f3, %r53;
	st.global.f32 	[%rd13], %f3;
	add.s32 	%r49, %r53, 1;
	add.s32 	%r51, %r46, 1;
	mov.u32 	%r53, %r49;

BB0_12:
	setp.lt.u32	%p7, %r25, 4;
	@%p7 bra 	BB0_15;

	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd14, %rd15;
	mov.u32 	%r53, %r49;

BB0_14:
	cvt.rn.f32.s32	%f4, %r53;
	st.global.f32 	[%rd16], %f4;
	add.s32 	%r37, %r53, 1;
	cvt.rn.f32.s32	%f5, %r37;
	st.global.f32 	[%rd16+4], %f5;
	add.s32 	%r38, %r53, 2;
	cvt.rn.f32.s32	%f6, %r38;
	st.global.f32 	[%rd16+8], %f6;
	add.s32 	%r39, %r53, 3;
	cvt.rn.f32.s32	%f7, %r39;
	st.global.f32 	[%rd16+12], %f7;
	add.s32 	%r53, %r53, 4;
	add.s64 	%rd16, %rd16, 16;
	add.s32 	%r51, %r51, 4;
	setp.lt.s32	%p8, %r51, %r25;
	@%p8 bra 	BB0_14;

BB0_15:
	add.s32 	%r42, %r42, 1;
	setp.lt.s32	%p9, %r42, %r26;
	@%p9 bra 	BB0_3;

BB0_16:
	add.s32 	%r40, %r40, 1;
	setp.lt.s32	%p10, %r40, %r27;
	@%p10 bra 	BB0_2;

BB0_17:
	ret;
}


`
   mdatatemp_ptx_75 = `
.version 6.4
.target sm_75
.address_size 64

	// .globl	mdatatemp

.visible .entry mdatatemp(
	.param .u64 mdatatemp_param_0,
	.param .u64 mdatatemp_param_1,
	.param .u64 mdatatemp_param_2,
	.param .u64 mdatatemp_param_3,
	.param .f32 mdatatemp_param_4,
	.param .u32 mdatatemp_param_5,
	.param .u32 mdatatemp_param_6,
	.param .u32 mdatatemp_param_7
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd4, [mdatatemp_param_0];
	ld.param.u32 	%r25, [mdatatemp_param_5];
	ld.param.u32 	%r26, [mdatatemp_param_6];
	ld.param.u32 	%r27, [mdatatemp_param_7];
	setp.lt.s32	%p1, %r27, 1;
	@%p1 bra 	BB0_17;

	mov.u32 	%r29, 0;
	mov.u32 	%r40, %r29;
	mov.u32 	%r53, %r29;

BB0_2:
	setp.lt.s32	%p2, %r26, 1;
	mov.u32 	%r42, %r29;
	@%p2 bra 	BB0_16;

BB0_3:
	setp.lt.s32	%p3, %r25, 1;
	@%p3 bra 	BB0_15;

	and.b32  	%r35, %r25, 3;
	mov.u32 	%r46, 1;
	mov.u32 	%r51, 0;
	setp.eq.s32	%p4, %r35, 0;
	@%p4 bra 	BB0_5;

	setp.eq.s32	%p5, %r35, 1;
	@%p5 bra 	BB0_7;
	bra.uni 	BB0_8;

BB0_7:
	mov.u32 	%r46, %r51;
	bra.uni 	BB0_11;

BB0_5:
	mov.u32 	%r49, %r53;
	mov.u32 	%r53, %r51;
	bra.uni 	BB0_12;

BB0_8:
	setp.eq.s32	%p6, %r35, 2;
	@%p6 bra 	BB0_10;

	cvt.rn.f32.s32	%f1, %r53;
	cvta.to.global.u64 	%rd5, %rd4;
	mul.wide.s32 	%rd6, %r53, 4;
	add.s64 	%rd7, %rd5, %rd6;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r53, %r53, 1;
	mov.u32 	%r46, 2;

BB0_10:
	cvta.to.global.u64 	%rd8, %rd4;
	mul.wide.s32 	%rd9, %r53, 4;
	add.s64 	%rd10, %rd8, %rd9;
	cvt.rn.f32.s32	%f2, %r53;
	st.global.f32 	[%rd10], %f2;
	add.s32 	%r53, %r53, 1;

BB0_11:
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r53, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvt.rn.f32.s32	%f3, %r53;
	st.global.f32 	[%rd13], %f3;
	add.s32 	%r49, %r53, 1;
	add.s32 	%r51, %r46, 1;
	mov.u32 	%r53, %r49;

BB0_12:
	setp.lt.u32	%p7, %r25, 4;
	@%p7 bra 	BB0_15;

	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd14, %rd15;
	mov.u32 	%r53, %r49;

BB0_14:
	cvt.rn.f32.s32	%f4, %r53;
	st.global.f32 	[%rd16], %f4;
	add.s32 	%r37, %r53, 1;
	cvt.rn.f32.s32	%f5, %r37;
	st.global.f32 	[%rd16+4], %f5;
	add.s32 	%r38, %r53, 2;
	cvt.rn.f32.s32	%f6, %r38;
	st.global.f32 	[%rd16+8], %f6;
	add.s32 	%r39, %r53, 3;
	cvt.rn.f32.s32	%f7, %r39;
	st.global.f32 	[%rd16+12], %f7;
	add.s32 	%r53, %r53, 4;
	add.s64 	%rd16, %rd16, 16;
	add.s32 	%r51, %r51, 4;
	setp.lt.s32	%p8, %r51, %r25;
	@%p8 bra 	BB0_14;

BB0_15:
	add.s32 	%r42, %r42, 1;
	setp.lt.s32	%p9, %r42, %r26;
	@%p9 bra 	BB0_3;

BB0_16:
	add.s32 	%r40, %r40, 1;
	setp.lt.s32	%p10, %r40, %r27;
	@%p10 bra 	BB0_2;

BB0_17:
	ret;
}


`
 )
